### ISSUE TITLE
multlyering is white above continents

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1016]
when doing an overlay of a color contour plot (1)  and a line contour overlay (2), the area over the continents of (1) is not displayed anymore. This should be corrected.
**Contour Plot (1):**
![topview_cloud_plot](https://user-images.githubusercontent.com/32653190/121007757-7b235d80-c792-11eb-95ec-084dda1b242a.png)
**Overlay Contour (2):**
![topview_cloud_overlay](https://user-images.githubusercontent.com/32653190/121007788-824a6b80-c792-11eb-9d04-4aa154169192.png)
**Multilayering Result:**
![topview_cloud_multi](https://user-images.githubusercontent.com/32653190/121007817-8aa2a680-c792-11eb-92a3-5ff5fec8e44d.png)

**Comment by Marilyth** [comment]
This is not an issue with multilayering, but with transparency.
For some reason on your server the area over continents has the colour #FAFAFA instead of #FFFFFF, over the ocean the colour is correct.
Only #FFFFFF gets turned transparent which is why the continents aren't affected by it.

**Comment by jgrooss** [comment]
Ok, then this is maybe not in the mss code but in the server config. The overlay is defined in 
(FZJ) mss-cirrus-hl@icg1318:~/INSTANCE/config/plots3.py 
Does it have to do with "alpha=0.8" or with the line "countries = False" ? I don't see it.

**Comment by Marilyth** [comment]
I am very unsure myself. FA = 0.98*FF. 
I see one part in the code that uses 0.98 as a factor instead of white
https://github.com/Open-MSS/MSS/blob/e516945c699d5c96529ae5a6388a1c6d88f9a008/mslib/mswms/mpl_hsec.py#L344
But that doesn't explain why I can't reproduce it on my end. Why that line uses 0.98 I don't know, but I would maybe start with that..

**Comment by joernu76** [comment]
Strange, that this worked once. I will have a look.

**Comment by joernu76** [comment]
Fixed. My bad. My "hot patch" on the server was not aligned with the "clean patch" to MSS main branch.

**Comment by joernu76** [comment]
This was a mis-configuration of the production server.
