### ISSUE TITLE
MetPy flightlevel<->pressure conversion wrong after 11km

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1025]
As mentioned here https://github.com/Open-MSS/MSS/issues/1004 and here https://github.com/Unidata/MetPy/issues/1890
We would like to move away from our own implementations and move towards using more functions by MetPy.
Unfortunately their functions for [height_to_pressure_std](https://github.com/Unidata/MetPy/blob/06c3bac994911bb22ed9a7be5c3b752f3cd1d628/src/metpy/calc/basic.py#L564) and [pressure_to_height_std](https://github.com/Unidata/MetPy/blob/06c3bac994911bb22ed9a7be5c3b752f3cd1d628/src/metpy/calc/basic.py#L415) aren't taking into account a change of temperature, pressure and temperature gradient after the first 11km which needs to be fixed.

**Comment by Marilyth** [comment]
I opened a PR for it a while ago https://github.com/Unidata/MetPy/pull/2084
So far there has not been any reaction, however.

**Comment by ReimarBauer** [comment]
@joernu76 can we add this on our site?

**Comment by ReimarBauer** [comment]
Discussed this with @joernu76 today. We have an own solution which we tried to add to theire repo. The PR is not merged since ages.
