### ISSUE TITLE
problem with upgrading the python version

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1026]
When I try to update in an exiting mss env the python version from 3.9.2 to 3.9.4 it want to downgrade mss

```
conda install python=3.9.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/icg105/miniconda3/envs/mssenv

  added / updated specs:
    - python=3.9.4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mss-2.0.1                  |   py39hf3d152e_0         2.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.6 MB

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2021.4.13-~ --> conda-forge::ca-certificates-2021.5.30-ha878542_0
  certifi                          2020.12.5-py39hf3d152e_1 --> 2021.5.30-py39hf3d152e_0
  python                           3.9.2-hffdb5ce_0_cpython --> 3.9.4-hffdb5ce_0_cpython
  sqlite                pkgs/main::sqlite-3.35.0-hdfb4753_0 --> conda-forge::sqlite-3.35.5-h74cdb3f_0

The following packages will be DOWNGRADED:

  mss                                  4.0.0-py39hf3d152e_0 --> 2.0.1-py39hf3d152e_0
```

**Comment by ReimarBauer** [comment]
This happens as long as we have the fixation for sqlite to:

```
sqlite  <3.35.1
```

With Python 3.9.4 it needs to install sqlite 3.35.5.
This forces the downgrade of MSS to a version without this dependency.

**Comment by Marilyth** [comment]
Trying it locally, I don't run into errors anymore without the fixation.
We might be able to remove it.

**Comment by ReimarBauer** [comment]
sqlalchemy is packaged for different python versions https://anaconda.org/conda-forge/sqlalchemy/files while sqlite isn't https://anaconda.org/conda-forge/sqlite/files

The conda install tries always the newest. We likly have to skip the versions which don't work. Could you try to find out automated which are broken starting from old limitation to recent?

**Comment by ReimarBauer** [comment]
-  [x] sqlite=3.35.1
-  [x] sqlite=3.35.2
-  [x] sqlite=3.35.3
-  [x] sqlite=3.35.4
-  [x] sqlite=3.35.5

all these version verified to run with all tests of stable

**Comment by ReimarBauer** [comment]
lets look on sqlalchemy

- [x] sqlalchemy    1.4.0 build 1
- [x]  sqlalchemy    1.4.1
- [x]  sqlalchemy    1.4.2 
- [x]  sqlalchemy    1.4.3 
- [x]  sqlalchemy    1.4.4 
- [x]  sqlalchemy    1.4.5 build 1
- [x]  sqlalchemy    1.4.6 
- [x]  sqlalchemy    1.4.7 
- [x]  sqlalchemy    1.4.8 
- [x]  sqlalchemy    1.4.9 
- [x]  sqlalchemy    1.4.10 
- [x]  sqlalchemy    1.4.11
- [x]  sqlalchemy    1.4.12
- [x]  sqlalchemy    1.4.13
- [x]  sqlalchemy    1.4.14
- [x]  sqlalchemy    1.4.15
- [x]  sqlalchemy    1.4.16
- [x]  sqlalchemy    1.4.17
- [x]  sqlalchemy    1.4.18
