### ISSUE TITLE
create an API for automatation of msui

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1035]
based on the hackish retriever.py we recently used to automate creations of plots we could start to work on an API to do everything we can do by the MSS GUI.

Some useful tools:
 - https://fastapi.tiangolo.com/
 - https://swagger.io/

The API should enable to use the MSS functions on various userscripts and jupyter notebooks.

**Comment by jgrooss** [comment]
The "old" retriever.py script (version 4.0.4) did read the "automated plotting" section from the configuration file mss_settings.json. This does not work for the current version 6.0.5.
I would propose a script that gets all relevant information from a separate (new) config file that should include all relevant information as for example
 * list of parameters (layers) to be plotted
 * list of initial time steps and forecast hours
 * list of flight paths for which the (sideview) plots should be created
 * level, map section, style and resolution of the plot
 * dictionaries how the lengthy layer names should be translated to plot title/file name
 * naming convention of output plot files

All list entries above could of course be single entries.
Further it should be possible to call this "retriever" script by setting parameters (overwriting default from the above config file) like
  python retriever.py --tinit 2022-03-29T00:00:00 --fc_hours 12

**Comment by swsrkty** [comment]
I have a doubt:

> * https://fastapi.tiangolo.com/
> * https://swagger.io/
> 
> The API should enable to use the MSS functions on various userscripts and jupyter notebooks.

Why do we need to build a web API server? (because FastAPI and Swagger are used for web APIs). Can't users install mss locally and use something like `import mslib.autoplot` in their scripts or in Jupter notebooks? I'm trying to understand the use case, thanks!

**Comment by jgrooss** [comment]
I do not know what kind of interface is needed for this task. I am not a specialist on APIs. My simple understanding of this would be a python program on a system where mss UI is installed. The program would get for example pre-defined map sections, mss server credentials from the corresponding mss_settings.json and it would have a further settings file (or some other mechanism) that tells the script which plots to provide.

The use case I have in mind is that during a measurement campaign some specific kind of plot (layer, map section, forecast times) needs to be produced on a daily basis, whenever the new forecast simulation is ready.
A different use case would be e.g. after the campaign to get specific sideview plots for all actually flown flight paths in a loop

**Comment by ReimarBauer** [comment]
@sr1j we don't need to build a web api server. This was an idea how to do this differently.
A solution as you described is welcome.
