### ISSUE TITLE
more details on the MSS Frontpage

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1045]
I wish to see postcards / images from aircraft missions in a bootstrap carousel on our frontpage. Prefered between the yellow and the blue box.

![initial](https://user-images.githubusercontent.com/278728/122603777-2b3b7500-d075-11eb-9af4-add86d930c18.png)

Other ideas are welcome

**Comment by tushar5526** [comment]
Hi @ReimarBauer I would like to do it. Just a few things I need to clear before starting. 

- The screenshot provide above and the homepage here https://open-mss.github.io/ are quite different. There is no yellow section and no blue section. 

Can you clear this?

**Comment by ReimarBauer** [comment]
This is the frontpage of the wms or mscolab flask server.

It is based on twitter bootstrap and jquery which we added by xstatic python packages.

- https://github.com/Open-MSS/MSS/blob/develop/mslib/index.py
- https://github.com/Open-MSS/MSS/tree/develop/mslib/static

A live example is on http://open-mss.org/
(wms demo data server)

For development you can use a localhost server see
https://mss.readthedocs.io/en/stable/installation.html#server-based-installation

The index is on the root url.

**Comment by ReimarBauer** [comment]
At the moment this PR is ready there will be a plot gallery added to the menu

https://github.com/Open-MSS/MSS/pull/1042

**Comment by ReimarBauer** [comment]
The license of used images should be Creative Commons.

**Comment by tushar5526** [comment]
Thanks @ReimarBauer for the reply. It cleared things up. 
Should I will wait for `# 1042` to be merged before implementing the caraousel?

**Comment by ReimarBauer** [comment]
You can start, if there are merge conflicts you or @Marilyth have to solve them ;)

**Comment by ReimarBauer** [comment]
We collected some of campaign logos to be used here
https://fz-juelich.sciebo.de/s/PN0qa8GEWN0s20K

**Comment by ReimarBauer** [comment]
requested from some logos a better one. 

![frontpage](https://user-images.githubusercontent.com/278728/127773328-4c3e992e-f19e-45d4-9c70-172a254fcb6f.gif)
