### ISSUE TITLE
organize / reorganize Topics of the Development part

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1052]
By  the PR fixing 
https://github.com/Open-MSS/MSS/issues/719
we now have a lot more Level 1 Topics in our documentation.

The documentation is both for new users and also developers. 

The list of main topics (first level) should be short.
All development related documentations have to be in the section Development. May be they can be grouped or sorted into that section.

The current state is:

![menu_development](https://user-images.githubusercontent.com/278728/123512589-9b0aba80-d688-11eb-87ca-9070b147f7e4.png)

That needs to become improved

**Comment by Marilyth** [comment]
We also have a few redundant parts now, as well as inconsistencies.

Setting up a local environment does not talk about conda, nor about installing MSS dependencies.

Both `Setting up local environment` and `Setting up development environment` essentially try to convey the same information and do it differently.
I would suggest merging these two sections together and combining their information.
