### ISSUE TITLE
integrate recent Airbase data, e.g. from openaip

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1069]
https://www.openaip.net/

**Comment by ReimarBauer** [comment]
maybe related https://github.com/datasets/airport-codes

**Comment by ReimarBauer** [comment]
- https://github.com/leopieters/aviation-edge-api
- https://github.com/wmo-im/iwxxm
- https://github.com/commenthol/openflights-data
- https://github.com/E3V3A/MMM-FlightsAbove
- https://github.com/commenthol/openflights-data
- https://github.com/matthewgall/ourairports MIT pypi
- https://github.com/wmo-im/iwxxm

**Comment by Marilyth** [comment]
Unfortunately openaip does not provide a working API. The one they have is somehow limited to 3459 items, which convers around 3 countries.
The only way to get reliable data is to login and download it manually. Which I am not yet sure is automatable since the website went down, but I will try afterwards.

**Comment by Marilyth** [comment]
Using [openflights](https://github.com/jpatokal/openflights) to import airports is working fine.
I got IP banned from OpenAIP for trying to reverse engineer the login process for my script, so don't do that.

![airports](https://user-images.githubusercontent.com/19623152/124607839-8095c580-de6e-11eb-8d8a-405993245eee.gif)

**Comment by ReimarBauer** [comment]
Much airports :)
 Is this per API a request of data for the map section? Have you compared to ourairports.

**Comment by Marilyth** [comment]
These airports get loaded from this csv file here
https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
I haven't compared it to ourairports yet, but it would probably be preferable as their data is up to date.

**Comment by ReimarBauer** [comment]
ok, we should add a notice where the data gets used from in our NOTICE

https://github.com/Open-MSS/MSS/blob/develop/NOTICE

**Comment by Marilyth** [comment]
I added support for manually downloaded airbase files from openaip
I could not automate the process, and I believe automation is against their ToS or something.

All in all it is a lot of data I am not sure yet how to display.
![airbases](https://user-images.githubusercontent.com/19623152/126179446-78f5ad24-58d1-4d81-ba2f-d099fd5648be.gif)

**Comment by ReimarBauer** [comment]
the data has a share a like license. 
https://www.openaip.net/legal

We have to figure how scientific usage can be covered.
