### ISSUE TITLE
Delete Waypoints Confirm Dialog Box showing opposite order of Yes-No in Windows and Linux.

### ISSUE THREAD

**Issue by risehr** [Open-MSS/MSS#1076]
On Windows, when delete waypoint button is clicked, the confirm dialog box is like this:

![Capture](https://user-images.githubusercontent.com/54763705/124589628-d753cd00-de77-11eb-9298-e8d163300e61.PNG)
The default is `Yes` button here.

On Linux, when delete waypoint button is clicked, it shows like this:

![Screenshot from 2021-07-06 16-06-45](https://user-images.githubusercontent.com/54763705/124589750-f8b4b900-de77-11eb-8474-59c4831e7256.png)
The default is `No` here.

The order of Yes-No is also reversed in both the systems.

The qt version used is 5.12.9

![image](https://user-images.githubusercontent.com/54763705/124589965-37e30a00-de78-11eb-9f91-e112b57c21f4.png)

It should show similar in both the OS. The default should be `No` in the confirm dialog box.

**Comment by ReimarBauer** [comment]
May be we can set explicit the default button

https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mpl_pathinteractor.py#L597

```
            QtWidgets.QMessageBox.question(
                None, "Remove waypoint",
                f"Remove waypoint no.{row:d} at {wp.lat:.2f}/{wp.lon:.2f}, flightlevel {wp.flightlevel:.2f}?",
                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No) == QtWidgets.QMessageBox.Yes
```
A solution should be applied to all these Yes/No answers

**Comment by ReimarBauer** [comment]
To unify the behaviour we should set our "default". Because someone usually wants to delete when he enables that feature the "Yes" should be default

https://coderslegacy.com/python/pyqt5-qmessagebox/

msg.setDefaultButton(QMessageBox.Yes)

and if the escape button can be set this can be QMessageBox.No
