### ISSUE TITLE
mscolab not JavaScript friendly

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1095]
While developing the windy plugin I encountered a few oddities of mscolab which should be solved in order to be used with JavaScript.

1. API and Websocket don't return a CORS header, which is required for communication through JavaScript.
2. Some GET endpoints require request.form data. GET requests don't have a body, as such either query string request.args or the combined request.values should be used.

**Comment by ReimarBauer** [comment]
We have not thought before about using wms/mscolab by AJAX/JS. 

Some ideas about this:
- https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/
- https://stackoverflow.com/questions/29187933/flask-socketio-cors
- https://pypi.org/project/Flask-Cors/

We should work on this together with the feature for the windy plugin

**Comment by Marilyth** [comment]
Issue exists in develop still

**Comment by Marilyth** [comment]
Currently getting CORS errors again through windy
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://yourmss.org/socket.io/?EIO=3&transport=polling&t=NsGFwSf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
Seems to be an issue with the socket, not the API

**Comment by Marilyth** [comment]
Issue was caused by a socketio version incompatibility between the windy plugin and MSS.
It is fixed now.
