### ISSUE TITLE
Campaign-Defined Plot Gallery

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1129]
A very useful tool would be to have a campaign-defined plot gallery available on the MSS server URL.
That means a set of pre-defined (top view) plots that are important for the specific measurement campaign.
It could be built upon the "plot gallery" structure.
Pre-definition of the plots should include map projection section, list of parameters (also allow multilayer plots),
a list of  levels. The exact plot settings would be defined in a config file, like in retriever.py that uses "automated_plotting" in mss_settings.json

An exact website layout needs to be defined/discussed: 
There could be a page displaying all plots in a gallery and one for single plots.
Maybe also different galleries for different scientific themes (e.g. chemistry, clouds, gravitiy waves)
There could be a choice box to set the initialisation time and valid time. 
There could be a clickable arrow to move in valid time and initialisation time.

**Comment by ReimarBauer** [comment]
This sounds a bit like on demand plotting by using some AJAX components on the backend.
This leads in a direction of adding an alternative to our QT UI by an interactive web interface.

**Comment by jgrooss** [comment]
In principle, one could also have a UI-like web interface. I am not sure, whether we would need that, since the installation of the UI works very well. The idea behind this issue is somewhat different. I think, the value of such a gallery of pre-defined plots is to get a scientific overview without the need of clicking always the same buttons on the UI. 
So for a complete interactive access, I don't see why we must double the functunality of the UI

**Comment by joernu76** [comment]
In practice the plots should be pre-generated on a manual trigger (cronjob) for performance.
That is similar to the current state.

What would be missing is a control to switch between different times. init/valid. Maybe only valid for starters?

Beyond that one can think about several different UI features replicating, e.g. Andreas Dörnbracks website.

I think we are in a good position here to have *in addition* to the WMS server a website browsable without the MSUI.

Such a website would compliment the MSUI tool very well (for getting an overview compared to specific flight planning).
