### ISSUE TITLE
Tidy up mslib.utils

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1131]
The utils module has grown too large.

QT related stuff should be move to "msui.mss_qt". msui.mss_qt might be renamed mss.qt where we're at it.
(most stuff from dropEvent to CheckableComboBox)

The airspace related stuff should get its own submodule mslib.airspace or similarly named.

Config related stuff should go to a config submodule.

Some other stuff might also find a fitting home.

**Comment by ReimarBauer** [comment]
I think we should move all "helper" modules to utils. 

This would mean we keep only version.py and `__init__.py` on that mslib dir level. 
thermolib, ogcwms, netcdf4tools will be moved to mslib/utils too.

**Comment by aravindm711** [comment]
Since I'm working on the editor window, Is it okay if I work on moving the config related methods to config.py under utils in my GSoC branch? As I also want to add a couple more methods to enable us to load the mss_settings.json file just once while starting the software.
