### ISSUE TITLE
Documentation misleading w.r.t. to what *conda to install before installing mss

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1146]
The documentation might be interpreted that the user should install miniconda, anaconda *and* conda-forge, instead of either.

(The same is actuall true for the anaconda documentation, but we cannot change that).

Actually happened in practice.

**Comment by ReimarBauer** [comment]
What is the idea of the user for improving this?

**Comment by ReimarBauer** [comment]
This is the current description, that may be is too long or too short.


The fastest way to get the conda installer is to start with Miniconda or Miniforge. This is a small subset of the Anaconda package with only the conda installer and its dependencies. If you do prefer to use over 7K open-source packages install Anaconda.

**Comment by joernu76** [comment]
Simplest fix would probably be
"We recommend to install this for the local user. This does not require administrator permissions."
->
"We recommend to install either one of the options below. This does not require administrator permissions."

**Comment by joernu76** [comment]
Or simply give a single link.
My user installed all three...

**Comment by joernu76** [comment]
Giving a single option would probably be best. "either one" requires reading comprehension skills.

**Comment by joernu76** [comment]
Until miniforge has a better webpage, I would suggest picking miniconda as the sole documented option, as this installs the least superfluous packages. Users that use any Anaconda for their day-to-day work will probably know that they can simply use their own environment and how to install mss.
