### ISSUE TITLE
one click installation of MSS

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1151]
Since 5.0.0 we have an auto update feature in MSS. 

I'm interested in an install procedure which simplifies usage of the MSS client at all.
This has to use the conda-forge MSS package. 
This should simplify, getting miniconda, installing mamba, installing MSS, knowing about envs

We need a solution which covers the major platforms: Linux, Mac, Windows

e.g.

- download und run
- build on the users system by one click

further ideas welcome

**Comment by Marilyth** [comment]
Scripts are done, documentation should be updated.
