### ISSUE TITLE
update inform widgets needs to become blocking

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1152]
The "Do you want upgrade Y/N" feature widget should become blocking for all other windows on my desktop.

**Comment by Marilyth** [comment]
The message box that pops up is blocking the rest of MSS for me, on Windows and Debian.
Can you reproduce this somehow? @ReimarBauer

**Comment by ReimarBauer** [comment]
recognized it blocks the mss_pyui, but the already opened views are not get blocked. 
also shortcuts are not blocked

**Comment by ReimarBauer** [comment]
the notifiaction widget does block the mss_pyui verified on windows and linux. 

We discussed and consent that we don't want to block by MSS other programs on screen. Behaviour is correct and wanted.
