### ISSUE TITLE
shortcuts commands ideas

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1153]
I'm thinking about the "Current Shortcuts" by Alt+S

Currently I can read them and then use on my keyboard that shown Keystroke.
I also could select a line. e.g. "Table View Ctrl +T". 

The shortest way  to select now "Table View Ctrl +T" could be double click and open it from there.

When we could show there also all Buttons, Menu, Input entries, also those without a key code and add a search field this will give a kind of overview and a different navigation option.

For using pyautogui this also means we can enter a search string to that helper and it finds the button, without the need to have an image  to locate it on screen. Currently we need different images dependent on users screen depth and fonts used.

We could also think about having a Ctrl+F on any view which then searches this helper data and highlights the element we are looking for.

This behaviour is than quite similiar to browsers.

For pyautogui that would mean we highlight something and search for e.g. a yellow box
set the mouse pointer there and click.

**Comment by Marilyth** [comment]
So you are suggesting
- Being able to execute shortcuts via double click in the Shortcut dialog
- Include within the Shortcut dialog all interactive QObjects (sounds like it would be very confusing for a normal user)
- Include a filter/search for the Shortcut dialog
- Include a Ctrl+F shortcut on every window to highlight QObjects by their name (for ease of use for pyautogui)

Yes?
