### ISSUE TITLE
use upper case shortcuts

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1155]
We recognized that we describe in the keyboard shortcuts to press an Upper key,
e.g. ctrl+H for starting topview from the main window, but we compare to ctrl+h.

the ctrl+h is a superordinate command function on a Mac and  ignores the QT definitions of the app.

We suggest to change all comparison to compare to the upper key. This means we have to press ctrl+shift+h for topview (or use caps lock, ctrl +h)

**Comment by joernu76** [comment]
Stick with lower case letter, i.e. no shift.
