### ISSUE TITLE
Testing can collect plugins, that leads to a logged error messages

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1187]
Ever since the GSOC branches were merged, whenever I start MSS I am greeted with multiple error message boxes akin to the one attached. This is also happening in the Test-MSS action, causing around 65 unhandled message boxes to appear.
![Screenshot at 2021-08-30 15-36-28](https://user-images.githubusercontent.com/19623152/131348079-e4e2112b-c6fa-4340-af1e-645a5c8ac3ae.png)

**Comment by ReimarBauer** [comment]
this is likly because of a local mss_settings.json. e.g. the one for the cirrus-hl campaign had this in the config, because mscolab missed that before in the import filters, while the old style interface had it predefined.

**Comment by ReimarBauer** [comment]
We can discuss if we have plugins defined at all. Or if this should be a WARN message.

**Comment by ReimarBauer** [comment]
if the tests get that message to show up, than the access to the setup for tests got broken. They should use the defaults or a prior tests adds it.

**Comment by ReimarBauer** [comment]
during that time I also added reverse to the test order for the none xdist tests.

**Comment by ReimarBauer** [comment]
The tests and also the documentation needs a review.

**Comment by ReimarBauer** [comment]
#1193 may be related

**Comment by ReimarBauer** [comment]
meanwhile solved

**Comment by ReimarBauer** [comment]
This seems to got solved by general test refactoring. Reopen when you can provide an example.
