### ISSUE TITLE
python-mss overwriting mss shortcut

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#1197]
If MSS is installed and the user types "mss" in their console, MSS starts.
If then python-mss is installed afterwards and the user types "mss" into their console, python-mss starts and takes a screenshot.

Not particularly troublesome but I thought I would document this behaviour.

**Comment by ReimarBauer** [comment]
We renamed our shortcut to msui

**Comment by ReimarBauer** [comment]
With 7.0.1 we have a little helper script for informing the user about the renaming of the ui call. This gets now overwritten by the shortcut. msui will always work.
