### ISSUE TITLE
For logging, do not use f-strings. Use % for performance reasons etc.

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1205]
refactor all logging strings

**Comment by engineerrbae** [comment]
Hey Reimar,  to show you a sample I have added % to the below code. Is this how you wish to have changes in all the .py files

https://github.com/engineerrbae/MSS/blob/develop/conftest.py#L189


summary = "\n".join(["PyQt5.QtWidgets.QMessageBox.%s: %s" %(box()._extract_mock_name(),box.mock_calls[:-1])
for box in [q, i, c, w] if box.call_count > 0])
 warnings.warn("An unhandled message box popped up during your test!\n%s" %(summary))
 
 OR
 
 summary = "\n".join(["PyQt5.QtWidgets.QMessageBox.{ }: { }".format(box()._extract_mock_name(),box.mock_calls[:-1])
for box in [q, i, c, w] if box.call_count > 0])
 warnings.warn("An unhandled message box popped up during your test!\n{ }".format(summary))

Once you share I will move ahead with refactoring. 

Thanks.

**Comment by ReimarBauer** [comment]
We do want to change only the use of f-string in logging....() to `%` syntax. On all other places f-strings are better.

Joern wrote an explanaition copied from https://github.com/Open-MSS/MSS/pull/1202#discussion_r707259404

f-formatting is almost always faster than c-style formatting due to some particularly interesting implementation shenanigans. That is not the point here, however.

The idea here is that the formatting will not take place at all in case the logging level is above debug. Using an f-string always does the formatting even if nothing will be output. That can have an detrimental effect on performance with logging disabled.
Thus it is good style to always employ conditional formatting, which by necessity of backwards-compatability, is c-style formatting. For info/warn/error, which are basically always dumped or where the formatted string is needed anyway (e.g. for a popup message), one may deviate at discretion.

There is a "style" parameter, which can be triggered on a by call basis to use other formatters (e.g. the {} one). See
https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles
This seems very cumbersome for little gain.
f-strings cannot be used as the decision whether to format cannot be controlled by the logging class.

**Comment by engineerrbae** [comment]
Got it. f-string is an expression that is evaluated at runtime and it lacks logging optimizations. Also, logging by default follows % standards & adoption of its default standards going to make the logging fast & accurate & better statistically.

Can you share with me the directories wherein logging is part of the files? I will make the changes, please assign me this issue. I will do it.

**Comment by ReimarBauer** [comment]
Hi
I show how you can do this in pycharm-community after you opened the MSS dir. vscode also has this capabilties.
You can use there a text search or also one based on regular expressions,
![f-string_logging](https://user-images.githubusercontent.com/278728/133357976-d427dc6d-cb78-44ba-96c1-d78ed4b070a1.gif)

The regex I used:
`\blogging\.\w.*\(f`

After doing these changes you can verify the PEP8 style used in your local clone of the forked repo,see
https://mss.readthedocs.io/en/stable/development.html#forking-the-repo

github will do too ;)

**Comment by engineerrbae** [comment]
Thanks a lot. Sure, I will do it. What's the deadline to submit?

**Comment by engineerrbae** [comment]
Thanks a lot. Noted. I have started making changes at my end. And, what's the deadline to submit?

**Comment by engineerrbae** [comment]
Noted. Thanks a lot.  

I have started making changes at my end. And, what's the deadline to submit?

**Comment by ReimarBauer** [comment]
there is no deadline, it may be added to 6.0 or 7.0

**Comment by kawalpreettkaur** [comment]
@ReimarBauer Added % syntax to the logging files.

**Comment by DipanshuShukla** [comment]
i will be taking up this issue

**Comment by Ritwikrajsingh** [comment]
I want to work on this issue

**Comment by ReimarBauer** [comment]
@Ritwikrajsingh have a look on the PR list @DipanshuShukla is already working on this one

**Comment by nilupulmanodya** [comment]
I want to work on this.. please assign me @ReimarBauer
