### ISSUE TITLE
server emit_new_permission ignored by client or server does not emit to the other client

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1213]
use two different accounts on an mscolab development server.
create with user A  a new operation,
share this operation to user B

The server does emit_new_permission but the client ui did not get the signal

when both have the project in the list. revoking does work. 

also when the project once was in the list adding also works

**Comment by Marilyth** [comment]
I am not sure "ignored by client" is the right word.
More likely it is an issue with the server not sending it to the new client, since this also happens with Javascript clients.

**Comment by ReimarBauer** [comment]
ok, that is a good test. 

I have with the released 5.0.2 version the same problem on localhost. All clients/server running on localhost in the same environment. Also on localhost for me different envs don't make a difference.

When I try our open-mss.org server it works.  Just documenting it, so that we see that it had or could work.

![ourserver](https://user-images.githubusercontent.com/278728/133659421-aa1a88dc-1883-4c2c-81d1-f0166521731b.gif)

**Comment by ReimarBauer** [comment]
package list
[mscolabserver.txt](https://github.com/Open-MSS/MSS/files/7179991/mscolabserver.txt)

**Comment by Marilyth** [comment]
It seems to not only happen with emit_new_permission.
On Windy I do not get ANY websocket messages for my room, if the operation was newly created and I didn't relog.
No response for new chat messages, permission updates, etc.
Digging around in the socketio base_manager, it seems like the room for the operation is just not created, or the clients are not added to it properly before a relog.

**Comment by ReimarBauer** [comment]
A wrong value on room was the reason why it did not work in develop. 
```
sio.emit('my event', {'data': 'foobar'}, room=user_sid)
```
https://python-socketio.readthedocs.io/en/latest/server.html#emitting-events
