### ISSUE TITLE
MSCOLAB: make "add user" user-friendly

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1244]
In case a user has no log in to the MSCOLAB server, he has to add a user first.

Now:
1) The user creates a user with mail + password
2) The user has to type the login details he just used into the login fields and click the login button

Desired:
1) The user creates a user just as now
2) The user is automatically logged in
Bonus: 
The login details are automatically stored in the config file for future use.

**Comment by swsrkty** [comment]
I'm looking into this.
