### ISSUE TITLE
refactor tutorials

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1275]
We should develop a base class for tutorials.

It contains all the basic functions that make up a tutorial.

and will be extended by a command line interface to start a tutorial,
e.g. different options:

- Show me how to do this (play)
- Record what you do. (play and record)

A single tutorial is derived from this base class.

The functions in the tutorials are stored in single modules and then imported for a new tutorial

The goal is that a user can formulate queries, and from these a tutorial is created.

E.g. 

- Show me how to create an account,
- Show me how to log in and create an operation.

When the tutorial is compiled, it can be controlled with the execution options, e.g. play (play and record).

A number of tutorials get accessible from the help menu.

**Comment by ReimarBauer** [comment]
Played a bit with different posiblities of ffmpeg 

slicing

` ffmpeg -i input_wms.mp4 -ss 00:00:14 -to 00:04:03 -c:v libx264 -crf 30  -acodec mp2 input_wms2.mp4`
 
cropping

` ffmpeg -i input_wms2.mp4 -filter_complex "[0:v]crop=1920:1050:0:0[cropped]" -map "[cropped]" input_wms3.mp4`
 
speeding result 22 Seconds
 
` ffmpeg -i input_wms3.mp4 -filter:v "setpts=0.1*PTS" input_wms4.mp4`
 
scale

` ffmpeg -i input_wms4.mp4 -vf scale=1280:720 -preset slow -crf 18 input_wms5.mp4`
 
convert to git (first idea)

`  ffmpeg -i input_wms5.mp4 input_wms5.gif`

  
libx265

  `ffmpeg -i input_wms5.mp4 -vcodec libx265 -crf 28 input_wms6.mp4`

  
convert to gif (no size change compared to libx264)
  
  ` ffmpeg -i input_wms6.mp4 input_wms6.gif`
   
   
using filter

   
` ffmpeg -y -i input_wms6.mp4 -filter_complex "fps=5,scale=854:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=32[p];[s1][p]paletteuse=dither=bayer" input_wms6.gif`

This creates a 2.4MB gifcycle of the tutorial_wms rushing through the options in 22 sec

![input_wms6](https://user-images.githubusercontent.com/278728/172592365-1f09a33d-0feb-4840-b16f-65a1ddf68703.gif)

**Comment by ReimarBauer** [comment]
A first refactoring was already done.  Here are some more ideas which might be interesting for a gsoc project

**Comment by CipJusCodin** [comment]
If the end goal is to allow users to ask questions, which would then trigger the creation of a tutorial, in a video format (play, pause etc), it would make the user get used to UI very quickly with minimal effort. This project seems very interesting, I would like to work on this with you.

**Comment by ReimarBauer** [comment]
Today the mentoring organisation list gets announced  (I have no idea if we are in), if this is a request because of the GSOC label.

You may have seen that we already have manual created scripts in https://github.com/Open-MSS/MSS/tree/develop/tutorials the result is published on https://mss.readthedocs.io/en/stable/tutorial.html

I would prefer not only to have a video, because that gets pretty fast outdated and persists long. While a script can find the changed button or another button or its new location quite easy and can create a new video.

That is the link to the ideas page. 
https://open-mss.github.io/develop/GSOC/improve_tutorials

**Comment by ReimarBauer** [comment]
The tasks in the description may become later issues
