### ISSUE TITLE
mscolab password recovery 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1279]
with a server having email verification enabled we need a feature for resetting a mscolab user password

**Comment by ReimarBauer** [comment]
once we have SAML/AAI implemented https://github.com/Open-MSS/MSS/issues/1051 we can limit local user handling to server site

**Comment by nilupulmanodya** [comment]
Moin @ReimarBauer, I would like to work on this. Please assign it to me.
