### ISSUE TITLE
upload of avatar image for MSC 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1287]
currently we can use a remote url with an image from gravatar after enabled to be used instead of the letter symbol

We want to have an option to replace the gravatar url by an uploaded image.
The upload feature has to become added to the user profile 

The image has to be stored as 200x200 px and served as static file. It should be used on the main interface and the chat. (currently using in the chat is not implemented)

**Comment by sratslla** [comment]
I am working on this issue!

**Comment by ReimarBauer** [comment]
thx :)
