### ISSUE TITLE
Changing the flight-track in Main window does not change name in open TopView

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1289]
Currently, loading a new flight track does not update the flight track name within the TopView window (maybe affecting other views as well).

Desired state: Changing the flight track should update the name in the view as well.

Not checked for MSCOlab

**Comment by joernu76** [comment]
Already fixed in current version.

**Comment by ReimarBauer** [comment]
related
https://github.com/Open-MSS/MSS/pull/1210
