### ISSUE TITLE
mamba failing to install MSS through instructions in README

### ISSUE THREAD

**Issue by swsrkty** [Open-MSS/MSS#1299]
Mamba failing to install MSS.
While following the instructions for installing MSS in README, namely 
```
conda create -n mssenv mamba
$ conda activate mssenv
(mssenv) $ mamba install mss
```

the following error appears:
```
Encountered problems while solving.
Problem: nothing provides basemap 1.0.7 needed by mss-1.2.1-py27_0
```
Related: #613

**Comment by ReimarBauer** [comment]
We should use the same instructions  in the README as we do on the RTFD document

https://mss.readthedocs.io/en/stable/installation.html#install
