### ISSUE TITLE
Flight paths crossing the date line (longitude=180)

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1304]
When moving the top view map towards a shifted map that reaches over the date line (longitude=180), it is possible that the longitude registred of a way point gets below -180. A flight path whith this coordinate is correclty displayed, however the resulting side view panel is not.
The following plots show the temperature curtain for the 2 waypoints (lat:-40 lon -150) and (lat: -40, lon:130) and the same when the second lon is replaced by -230. Although the values below -180 are considered as not in the valid range in the table view, these way points can be created by clicking on the top view. For the such created invalid logitudes the sideview shows no data.
![sideview_Temperature1](https://user-images.githubusercontent.com/32653190/146218943-a95a6fec-c5d6-442d-afa2-87f1e0c39da0.png)
![sideview_Temperature2](https://user-images.githubusercontent.com/32653190/146218960-7ecc49ac-c048-4834-9996-db4c90658947.png)

This is important for missions near the date line e.g. in the Pacific

**Comment by jgrooss** [comment]
...and also no data are shown near the date line for way points with valid longitudes...

**Comment by joernu76** [comment]
Mmmrpf. Will have a look at that. I fixed the TopView recently. I assume that still works?

**Comment by joernu76** [comment]
@jgrooss This might also depend on how the data is supplied to the server. Which server supplied the data?

**Comment by jgrooss** [comment]
This was on https://forecast.fz-juelich.de/ti3ger, login details see rocket chat

**Comment by jgrooss** [comment]
A similar problem occurs in the top view plots, when having a model domain from longitudes 160 and 260
![topview_Temperature_200 0](https://user-images.githubusercontent.com/32653190/146565203-5feb7e28-ae76-423c-a685-431948b0a654.png)

**Comment by joernu76** [comment]
The horizontal problem occurs when data that is located left to the view is relocated to the right.
And then it seemingly interpolates over the humongous gap in the middle.
