### ISSUE TITLE
Can only use one 'export_plugins' and 'import_plugins' entry.

### ISSUE THREAD

**Issue by shawnusaf** [Open-MSS/MSS#1305]
Greetings from Boulder!,

In version 6.0.0 of the software when I put more than one plugin into "export_plugins": {} in the mss_settings.json file, it will always load the first plugin perfectly fine regardless of which one of my plugins I choose first, but every other one in the list after that does not install when starting up the MSS planner.  I am getting the following message box:

ERROR: Configuration
{'csv': <function load_from_csv at 0x7fc5d8571b80>, 'txt': <function import_foreflight at 0x7fc5e1b31310>}
throws <class 'ValueError'> error:
'actionImportFlightTracktxt' has already been set!

I get this message for each of my plugins (minus the first one listed in "export_plugins":{}), then the program comes all the way up, but only with the first plugin loaded.  The same happens for my "import_plugins":{} entries.

Thanks!

-Shawn Honomichl

**Comment by ReimarBauer** [comment]
Hi Shawn :)

I've seen this error message before too. Probably this happens when we use the same names for the functions. 

Please show me your snippet of the config file. I tried with this one, myt.py is a copy of text.py where I only renamed the function names and added the file to .config/mss. This snippet does not create this failure, 

```
"import_plugins": {
        "Text": ["text", "mslib.plugins.io.text", "load_from_txt", "default"],
	"MYT": ["myt", "myt", "load_from_myt", "default"]
    },

    "export_plugins": {
        "Text": ["text", "mslib.plugins.io.text", "save_to_txt", "default"],
        "KML": ["kml", "mslib.plugins.io.kml", "save_to_kml", "default"],
	"GPX": ["gpx", "mslib.plugins.io.gpx", "save_to_gpx", "default"]

    }
```
On import of plugins we should take care of the modules namespace

**Comment by shawnusaf** [comment]
Hi Reimar,

This makes sense.

This is what I have:

   "export_plugins": {
       "COPY PLAN TO CLIPBOARD":
["txt","foreflight_export2clipboardplugin","export_2clipboard"],
       "FOREFLIGHT PILOTS / EMAIL": ["txt",
"foreflight_export_plugin_for_pilots","export_csv_email"],
       "FOREFLIGHT / EMAIL": ["txt",
"foreflight_export_plugin","export_csv_email"],
       "GV_TO_EOL_CATALOG":
["txt","export_plan_to_eol_cat","email_gv_plan"],
       "WB57_TO_EOL_CATALOG":
["txt","export_plan_to_eol_cat","email_wb57_plan"]
    },

    "import_plugins": {
        "FOREFLIGHT":
["txt","foreflight_import_plugin","import_foreflight"],
        "FOREFLIGHT PASTE FROM CLIPBOARD":
["txt","foreflight_import_clipboard_plugin","import_foreflight_clipboard"]
    }

I do have a couple with the same name so I will tinker with the naming
conventions and see if that corrects the problem.

Thanks!

-Shawn

**Comment by shawnusaf** [comment]
Okay, I got this to work.  The thing that I had to change to make it work
were the "txt" entries.  I had to make it unique for each plugin.

One other question I have while I have you on email is, when I select an
import or export plugin, The 'export flight track' window automatically
comes up.  Is there a way to suppress this window in my export script?
Specifically, one of the functions is to just copy the flight plan to the
clipboard so that I can paste back and fourth directly into and from
Foreflight so I don't actually need to export the information to a file.
So, ideally I would like to just suppress the 'export flight track'
window.  Is that possible?

Thanks!

-Shawn

**Comment by ReimarBauer** [comment]
The 6.0.1 will allow again to have same extensions for many plugins. I introduced this problem by the mscolab import and later we unified this to become based on extensions. But this is not a good idea.

The solution for the initial problem is to first select the function and then output to a user file by using the filebrowser. By this we use the plugins name to destinguish the functions.

Copy to Clipboard or Export in a default format without other user request is a good idea. The clipboard format could be defined by the config and overwritten in the users settings. Likly this can be solved by defining a clipboard pickertype which then does not load the file browser dialog.  Please file an enhancement issue for this. 

Likly the mscolab function can be also used for this idea. This can be used to share any time the recent flight path with many users or tools. 
@Marilyth  had introduced a plugin for windy. https://github.com/Marilyth/windy-plugins

The tutorial final_mscolab from that dir shows an example for mscolab.
https://fz-juelich.sciebo.de/s/IzNGi24Ki68iV7t#/

**Comment by shawnusaf** [comment]
Thanks Reimar!,

I will file an enhancement for it.  I think it is a good enhancement as we
use our current clipboard copy function a lot to quickly bounce flight
plans back and forth between MSS and Foreflight to check for potential
issues with commercial airways, airway traffic, and other realtime airspace
issues.

-Shawn
