### ISSUE TITLE
leave Operation in properties menu

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1322]
Any user role besides creator needs to have the option to leave an operation.

After doing that the user needs to be disconnected from that operation, e.g. close open views

**Comment by swsrkty** [comment]
I'm looking into it.

**Comment by swsrkty** [comment]
I'm currently working on my GSoC project proposal so I'll continue working on this issue after April 19.

**Comment by swsrkty** [comment]
> After doing that the user needs to be disconnected from that operation, e.g. close open views

Hi @ReimarBauer, does the operation need to be removed from their operation list along with closing all the open views?

**Comment by ReimarBauer** [comment]
Hi @sr1j yes, on the user who is doing this action his list can be per request reloaded, Look for reload_operation_list()
