### ISSUE TITLE
download folder in .config/msui for openaip

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1332]
currently we download directly to the .config/MSS folder.

We should have an aip folder and use this.

**Comment by ReimarBauer** [comment]
from a users point of view I think we should have a downloads folder and maybe below this other subdirs. This helps to destinguish which files have been installed by using MSS to the system. Everything which is in downloads should be removable without making problems.

.config/msui
├── downloads
├── gravatars
├── plugins

And below downloads we could create e.g. an folder aip

**Comment by joernu76** [comment]
seems very reasonable!

**Comment by rootxrishabh** [comment]
To my understanding, we need to add some folders for openaip data to organize the data efficiently, so I will make a PR.
