### ISSUE TITLE
meta.yaml uses to much blanks for fixations

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1362]
We have in our meta.yaml https://github.com/Open-MSS/MSS/blob/develop/localbuild/meta.yaml
used fixations with one or more blanks. 

one blank is the correct definition

**Comment by shivamshan** [comment]
@ReimarBauer could you explain a bit more as to where enhancements could be done? are there any issues with the current fixations ?

**Comment by ReimarBauer** [comment]
The writings of the fixation is not absolutly correct and the linter falls over 2 blanks. We need only one blank after the name before the fixation

in e.g. https://github.com/Open-MSS/MSS/blob/develop/localbuild/meta.yaml#L31
we have two blanks before the operator, e.g. `>` it must be only one blank.

```
not good
- basemap  >1.2.1
better
- basemap >1.2.1
```
