### ISSUE TITLE
Include the use of NAVAID Waypoint naming convention

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#1363]
Pilots use the naming convention for waypoints in the format WPT012034
where WPT is the NAVAID ID, 012 is the heading and 034 is the distance
in nautical miles. This waypoint format is only used over land.  It
would be helpful to have the aibility to handle this format.

I was provided a python code developed by Jenna Samra and Jonathan
Franklin (SAO and Harvard University) and described by Pavel Romashkin
(NCAR RAF). I need to check, whether we are allowed to use this code
officially.

There is a database of these NAVAID waypoints e.g. in OPENAIP
https://www.openaip.net/navaids

Envisaged would be
(1) to create a flight path output plugin that is able to
automatically create the waypoint names in this format, either in a
ASCII text table or csv.

(2) an input plugin in which waypoints of this convention are
translated into real latitudes and longitudes

(3) potentially an automatic detection in the table view panel, if the
waypoints in this convention are typed into the name field.  It could
also include the NAVAID waypoints themselves.

**Comment by jgrooss** [comment]
I wrote a plugin from the information about the NAVAID Waypoint naming convention. It needs however the libraries   
geopy, geomag, and geographiclib.
The plugin file can be placedinto the config directory, but how can the libraries be added?
This text [navaid.py.txt](https://github.com/Open-MSS/MSS/files/8341211/navaid.py.txt) contains the code. It woud need to be renamed to navaid.py

**Comment by ReimarBauer** [comment]
@jgrooss Please add this to the documentations, e.g. add a docs/samples/plugings/navaid  dir. Put there this file and a README with a description. In this issue it will "vanish" after it gets closed.

Afterwards I can add a plugins document to the components section
https://github.com/Open-MSS/MSS/blob/develop/docs/components.rst
 
Meanwhile I prepare a build on conda-forge for geomag, https://github.com/conda-forge/staged-recipes/pull/18451

When that is ready it can installed by mamba install geopy geomag geographiclib.

**Comment by jgrooss** [comment]
ok. Should I open a branch for that and also include the navaid.py somewhere? Or should this stay a plugin to be provided separately?

**Comment by ReimarBauer** [comment]
I am working in your PR wait until I've finished that
