### ISSUE TITLE
remove a layer-less WMS server using the "trashcan" icon causes a segmentation fault

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1376]
Happens on stable 6.0.3

Steps to reproduce:
1) load current SouthTrac server (serving no layers)
2) remove the server using the trashcan icon in the layer selection
3) program crashes with a segmentation fault, probably within QT

**Comment by joernu76** [comment]
Did some debugging, but couldn't find a fault within the Python code...

**Comment by ReimarBauer** [comment]
@joernu76 can't reproduce with the ti3ger or the open-mss demo server in current develop and also not in 6.0.4.

**Comment by joernu76** [comment]
Mmmh. I will retry next week.

**Comment by joernu76** [comment]
I tried to replicate the issue with 6.0.3  and 6.0.4 and stable (in my current environment).
I also tried out GNOME and MATE window managers beside my typical mate/awesome mishmash.

I can still produce a crash for all versions and window managers within QT. Reviewing the code, I could not find an obvious cause and debugging the crash within C/C++ qt is beyond my current ressources.*

**Comment by joernu76** [comment]
As mentioned in the title, I believe it to be connected to the WMS server having *no* layers. The servers @ReimarBauer mentioned all have layers.
If it'd crash MSS for a server with layers, this would be a major bug, not a minor one.
