### ISSUE TITLE
write a pytest unittest for mslib.utils.config.merge_dict

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1386]
merge_dict is important for updating the users mss_settings.json file. 

We want it verified on each our test runs that it works as expected. 

So a test has to cover its functionality.

**Comment by ren276** [comment]
I am new to open source but want to work on this issue  !

**Comment by ReimarBauer** [comment]
Hi @ren276 
great :)

**Comment by Ritwikrajsingh** [comment]
i will work on this issue

**Comment by Ritwikrajsingh** [comment]
I am not able to formulate the structure of test cases. I request your guidance.

**Comment by ReimarBauer** [comment]
Have a look into the already existing
https://github.com/Open-MSS/MSS/blob/develop/mslib/utils/_tests/test_config.py

in principle you add there a def test_merge_dict():
having the function imported you can do a assert merge_dict(....) == ...

also have a look on

- https://semaphoreci.com/community/tutorials/testing-python-applications-with-pytest
- https://docs.pytest.org/en/6.2.x/example/simple.html
- https://mss.readthedocs.io/en/stable/development.html?highlight=pytest#run-tests
