### ISSUE TITLE
allow for custom atmospheric profile to calculate flight levels in vertical sections

### ISSUE THREAD

**Issue by jroettenbacher** [Open-MSS/MSS#1388]
Hi all,
we are currently conducting a campaign in the Arctic (HALO-(AC)³) and noticed that the cloud heights in the vertical sections are quite odd. This is close to Svalbard at 80° North and we should not get clouds above 10km...

![sideview_clouds](https://user-images.githubusercontent.com/44004932/157235101-64a57525-33d3-4aca-ad5c-0e7b6b9d050e.png)

The problem seems to be the conversion from pressure levels to flight levels/altitude. 
Here a standard atmosphere is used ([here](https://github.com/Open-MSS/MSS/blob/565f0443b688f97f1e400467bcda7d66bd93f5fd/mslib/utils/thermolib.py#L131)). 
It would be nice if there was a way to pass a custom atmospheric profile or choose between different regions (Arctic, Midlatitudes, Tropics).

Do you think this is feasable? 

Best wishes from Kiruna,
Johannes

**Comment by ReimarBauer** [comment]
Please have a look if this is the same problem, and if the fix does apply for you
- https://github.com/Open-MSS/MSS/issues/1364
- https://github.com/Open-MSS/MSS/pull/1360

**Comment by jroettenbacher** [comment]
Hi Reimar, 
thanks for the quick answer. I'm not sure if it can be solved that easily since one would need to implement several standard atmospheres and then give the user a choice which one to use to calculate the corresponding pressure altitude/flight level. However, we had a deeper look in the data and it seems, that the cause for the high clouds is not the scale but that what we see is a real thing... Just a very unexpected thing.

Another point that came up is, that it is probably not very useful to implement other standard atmospheres in a flight planning tool than the one used by pilots and air traffic control. One would only cause confusion in the long run.

I guess we can mark this issue as solved and keep it for the record. 

Best Johannes

**Comment by ReimarBauer** [comment]
Thx for clarifying.
