### ISSUE TITLE
Error after installation: "QWidget: must construct a QApplication before a widget"

### ISSUE THREAD

**Issue by bkirbus** [Open-MSS/MSS#1397]
Hi everyone,
greetings from the HALO-(AC)3 campaign in Kiruna/Sweden and on Svalbard. We have many users that installed MSS according to instructions ([readthedocs](https://mss.readthedocs.io/en/stable/)) but initially failed to start MSS. The error thrown reads

> "QWidget: must construct a QApplication before a widget"

It turns out there are issues with the "itsdangerous" package. Downgrading to 2.0.1 seems to resolve the error for all affected users, e.g. via
`pip install itsdangerous==2.0.1`

We found the solution here: [link](https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/).

Did you experience anything similiar?
Thanks, all the best
Benjamin

**Comment by ReimarBauer** [comment]
Hi Benjamin,
we did therefore a new release :)  Please check that you have 6.0.4 installed. This was changed in 6.0.3, see https://github.com/Open-MSS/MSS/releases/tag/6.0.3

You can easily update by conda activate mssenv and then call mss --update
https://mss.readthedocs.io/en/stable/installation.html?highlight=update#builtin-update

regards
Reimar

6.0.3 released 2022-02-18
6.0.4 released 2022-02-25
