### ISSUE TITLE
write tests for io plugins

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1432]
We have a set of io plugins in mslib which can be configured by the user in mss_settings.json.

There are yet no pytest scripts available for these modules.  For each plugin a seperate module e.g. test_csv.py script should be created in plugins.io._tests

**Comment by harivamsi9** [comment]
@ReimarBauer I wanna work on this issue. I have worked earlier on pytest library for Test Driven Development.

**Comment by ReimarBauer** [comment]
Welcome @harivamsi9 

you have it

**Comment by harivamsi9** [comment]
Hey @ReimarBauer, Can you please help me with what all test cases you want me to cover?

**Comment by ReimarBauer** [comment]
Have a look into https://github.com/Open-MSS/MSS/blob/develop/mslib/plugins/io/kml.py
there is one function which creates a result and a raise condition.
Both have to become covered by a test. 

then continue with the others of https://github.com/Open-MSS/MSS/tree/develop/mslib/plugins/io
