### ISSUE TITLE
The return_format variable in mswms should be renamed to mime_type

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1497]

**Comment by Shubham1450** [comment]
I want to work on this issue. Can you assign it to me.

**Comment by ReimarBauer** [comment]
Hi @Shubham1450 you have it :) Please send a PR to develop branch. Thx.

**Comment by Mr-Sunglasses** [comment]
Hey @ReimarBauer it seems like @Shubham1450 is no longer working on this issue, can I go ahead and start working on it ?
