### ISSUE TITLE
"Linear" plots

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#152]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/152) by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

An enhancement would also be to have a linear plot for a given flight route. This would be
a simple time/parameter plot of a model parameter (temperature, potential temperature, tracer x mixing ratio,...) interpolated along the proposed flight route. 
This plot type should be elected in the Menu "Views" next to the plot types "Top View" and "Side View".

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

This would be a useful feature. 
There are a couple of design questions, though.
Should "styles" similar to the hsec/vsec styles be pre-determined to have selections of parameters in a joint plot (rather straightforward), or should the user be able to customize that? Should the data be transmitted as transparent picture or as data?

A simple version using styles could reuse the wms_control interface and cover most use cases. The axes are typically defined in the frontend. For the y-axis, this might need to change here....

**Comment by ReimarBauer** [comment]
**Original comment by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

I see, that this cannot be realized in short time, but still this would be a very useful feature. Especially a linear plot of potential temperature (theta) along the flight path was needed during the last campaign and it had to be calculated offline.

**Comment by joernu76** [comment]
Adressed now by issue #833
