### ISSUE TITLE
show results on the ctrl+f highlighter without clicking

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1521]
We could use the ctrl+f to highlight while typing.

e.g. open msui
press ctrl +h (opens topview)
press ctrl +f  (opens search)
type Transparent 

the word Transparent is highlighted 

with "enter" the view is closed and highlighing of the word is removed

**Comment by ReimarBauer** [comment]
That may be useful for the tutorials. There the button before it gets clicked can be highlighted in a defined color.

**Comment by ReimarBauer** [comment]
in the example above there is only one result, currently we have to open the tree and then to click (for selection) on the word again

![result_of_search](https://user-images.githubusercontent.com/278728/221349083-276e5daf-f196-43e1-a6e3-666bf6933038.png)

It should behave for this case by only one occurency. This saves us for two extra clicks.

![prefered_solution](https://user-images.githubusercontent.com/278728/221349171-02a7a0c1-35da-4e8f-9fba-e6bfe07dfd09.png)

The functionality to close the search view by "enter" after selection is implemented.

**Comment by Mr-Sunglasses** [comment]
I would like to work on this issue could you please assign it to me.
