### ISSUE TITLE
changing flight path colour  (options) removes topview/sideview/linearview figure heading

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1528]

**Comment by ReimarBauer** [comment]
reproduced in 7.0.2

![reproduced](https://user-images.githubusercontent.com/278728/185858928-037c8d87-b523-4634-bd7d-f7202d0b3f86.gif)

**Comment by ReimarBauer** [comment]
using options in a view removes the title on top, side and liearview
