### ISSUE TITLE
Remote sensing tool tangent points not correct west of longitude 180°

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1565]
I was playing around with the "Remote Sensing Tools" in the Top View window, while experiencing the following (see screenshot):
![grafik](https://user-images.githubusercontent.com/114411636/192284047-936cd49f-1bbc-451e-bb38-35d8f1875150.png)

As you can see, tangent point locations are only displayed correctly east of longitude 180°, when crossing 180°. Adjusting the flight track to points only east of 180°, all tangent points are shown incorrectly. West of 180°, everything seems to be fine.
Tested with version 7.0.4.

**Comment by soerenjoh** [comment]
A little update: when only having longitudes east of 180° (only negative lons or only positive lons), I got this message:
![grafik](https://user-images.githubusercontent.com/114411636/192521852-2e40b970-9e9d-468c-882a-0454b7eba98f.png)

**Comment by joernu76** [comment]
Thanks. I'll have a look.

**Comment by joernu76** [comment]
The original issue should be fixed with the Merge Request. I cannot reproduce the second one.
@soerenjoh could you check the fix #1568 , if it fixes the crash and, if not, provide me with better instructions to provoke the crash?

**Comment by soerenjoh** [comment]
Thanks for the fix of the original issue. I found out that the crash is very difficult to provoke: It happens, when you clone a waypoint (e.g. for changing flight altitudes instantaneously). When moving one of the cloned way points a little horizontally, the crash does not occur. So, it's a different issue... I'll open it in a minute!
