### ISSUE TITLE
Wrapping issue in side view (and linear view) when crossing 180° longitude

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1566]
When having a flight path crossing 180° longitude, there are missing values at these longitudes in the side view (and also in linear view), as shown in the screenshot:
![grafik](https://user-images.githubusercontent.com/114411636/192292022-9b2c5601-80ab-47a5-ace4-eb515c7711d4.png)

It seems like, the model data is not wrapped correctly and simply goes from -180 to +180 degrees longitude?

**Comment by jgrooss** [comment]
This should be some interpolation issue. I can confirm this problem. In my case it is not present, if the positive longitude values are replaced by negative (lon-360) in the table view.

**Comment by soerenjoh** [comment]
For me, replacing longitudes by lon-360 in the table view did not help. I got then the following error message:
![grafik](https://user-images.githubusercontent.com/114411636/192457854-75135e5b-ae76-4179-bdd4-75611c20ff06.png)

Without knowing anything about the MSS code, I was sometimes encountering similar issues in my plotting scripts. I was able to solve them by repeating the last longitude column in the beginning (or vice versa) when reading in the data. Maybe this helps here as well?

**Comment by jgrooss** [comment]
this should also not be the solution, just a hint, where to search. But "data not available" is a different problem/issue

**Comment by jgrooss** [comment]
It means that the data are not available :-)  
Which server you are connecting? I currently play with https://forecast.fz-juelich.de/campaigns2022
Please do not use this in the next minutes...

**Comment by soerenjoh** [comment]
You are right, that was a different issue! I was using https://forecast.fz-juelich.de/campaigns2022 and using it the first time after opening the system again after hibernation.... I guess, it was trying to get time steps, which have been in the MSUI cache, but are not available anymore. Sorry for the confusion!

**Comment by jgrooss** [comment]
ok.  https://forecast.fz-juelich.de/campaigns2022 should be runnning again. Please contact me directly for problems with that.
Here remains the issue of interpolating across the date line.

**Comment by joernu76** [comment]
Wrapping data and interpolation is a long-standing problem in any software. 

MSWMS uses scipy.ndimage.map_coordinates, which is unaware of the wrap around. Following Sörens method would be a sensible fix IMO; in fact, the map_coordinates variable can do a grid_wrapping to the same effect.
*Either way* one needs to ensure that the dataset is global first.

Should be a straightforward fix in mslib/utils/coordinate.py
Volunteers?
