### ISSUE TITLE
Remote sensing tool results in crash, if two consecutive way points are in the same horizontal position

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1571]
As mentioned in #1516 , I was able to provoke a crash if I was either

- cloning a way point in the table view with enabled tangent points of the remote sensing tools 
- enabling the tangent points of the remote sensing tools when having two consecutive way points in the same horizontal position

An easy workaround for me as a user is to ensure that there are no two identical consecutive way points, before enabling the remote sensing tools, but maybe it could be checked by the remote sensing tool itself?

**Comment by joernu76** [comment]
I see how that poses a problem, but the tool should be able to handle that. Should be easy to fix.
