### ISSUE TITLE
Create proper tests for remote sensing widget

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1575]
This widget is nearly fully untested causing some issues in the last stable release.
The widget requires interaction with a flight path and the top view, so several components need to be instantiated for testing (or mocked).

Tests should involve flight paths crossing date line and having points of identical coordinates.

**Comment by joernu76** [comment]
Secondly, but more complicated, one could also try to make the implementation more readable/efficient. The usage of the list comprehensions is not very accessible.

**Comment by Mr-Sunglasses** [comment]
I would like to work on writing these tests, please assign this issue to me.
