### ISSUE TITLE
update documentation for gh command

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1587]
github has a new cli command for cloning etc.

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

**Comment by rootxrishabh** [comment]
Hey @ReimarBauer, I think I could work on this, just to be clear about the issue, we have to change the "git clone" command with the "gh repo clone" [here](https://github.com/Open-MSS/MSS/blob/develop/docs/development.rst#cloning-the-repo) right? Also, maybe I could mention how to install the "gh" command.

**Comment by ReimarBauer** [comment]
Not change, but add.
We want to keep `git clone`. There could be an example for `gh`.

**Comment by rootxrishabh** [comment]
Habe es! I will make some changes and submit a PR.
