### ISSUE TITLE
importing multiple flight trac should keep activated one

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1593]
currently when we import a flight track in standalone always this changes activation state.
We should keep the activated flight track. Only a user should do a new activation.

**Comment by joernu76** [comment]
I disagree, activating the newly imported flighttrack seems very sensible to me.
95% of the times I import a flight track, I want to have it activated.
I know there are other use cases with the new tool Jatin is programming, but I think mostly one wants to activate the newly imported/loaded flight path.

**Comment by joernu76** [comment]
If multiple flight paths are imported, the typical use case may be different and one could argue that neither should be activated. Activating any of the new ones is acceptable as well for me.

**Comment by ReimarBauer** [comment]
Currently importing in develop for flight tracks creates always new entries, as seen here, and the last one is then activated
![activation_last_imported](https://user-images.githubusercontent.com/278728/201615220-b3a69482-a383-4ebe-8307-edec0fcbfcf0.gif)

**Comment by ReimarBauer** [comment]
Our import is not changing the activated flight track, it creates a new one. In mscolab it will create a new revision.

Because we don't have revisions for flight tracks, new files are a good solution.

https://github.com/Open-MSS/MSS/issues/1316

**Comment by ReimarBauer** [comment]
When we import many flighttracks we don't change activation. This also speeds up the multiple flight path docking widget
