### ISSUE TITLE
refactor airdata

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1629]
This is a start to have tests for the current solution of airdata processing
https://github.com/Open-MSS/MSS/pull/1627

We should change global variables to global constants and reduce the dependencies so that the parts can functional be tested without so much mocking

**Comment by rootxrishabh** [comment]
Guten Abend @ReimarBauer, I would like to work on this. Please assign me.

**Comment by ReimarBauer** [comment]
Moin @rootxrishabh. I would prefer you finish first the existing PR, https://github.com/Open-MSS/MSS/pull/1671 Or how should we continue with this?

**Comment by rootxrishabh** [comment]
Moin @ReimarBauer, Let me finish what I have started, after that I would get to this promptly : )

**Comment by rootxrishabh** [comment]
Moin @ReimarBauer, I understand that there are 2 tasks for this PR.
1) Change global variables to global constants in airdata.py
2) Reorganize the code in test_airdata.py such that it is less dependent on the mock library.
Am I correct in the above observations?

**Comment by ReimarBauer** [comment]
Moin @rootxrishabh only first item on the list. 

Don't touch the tests until the  refactoring is done. They should show 0 failures, because they don't need a global var.

**Comment by ReimarBauer** [comment]
documentation:
- https://betterprogramming.pub/alternatives-to-using-globals-in-python-a3b2a7d5411b

- http://google.github.io/styleguide/pyguide.html
