### ISSUE TITLE
Update citations of MSS

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1638]
https://gmd.copernicus.org/articles/15/8983/2022/gmd-15-8983-2022.html

is published and we have to add it to docs and MSUI about

**Comment by rootxrishabh** [comment]
@ReimarBauer I will work on this.

**Comment by rootxrishabh** [comment]
Do I have to include the whole article in a separate file or just update an existing one?

**Comment by rootxrishabh** [comment]
Or maybe just link the whole article in the publication section of the docs.

**Comment by ReimarBauer** [comment]
Not the article but how it could be found, similar to the first one, see https://mss.readthedocs.io/en/stable/

**Comment by rootxrishabh** [comment]
@ReimarBauer I created a PR please check.
