### ISSUE TITLE
Document how to plot only one variable without any additional data available

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1639]
Some suggestion to add to the documentation: 
While trying to get a MSWMS server running with new model data, I tried to do a minimal example to just plot temperature on pressure levels. With the examples given in the documentation, always additional model variables (e.g. PV or Theta) were necessary. I suggest to include a very simple example of how to make a simple plot for a certain variable in the documentation. @joernu76 proposed the following approach, which worked out fine for me:

```python
mpl_hsec_styles.make_generic_class("HS_MyStyle_pl_air_temperature",'air_temperature','pl',[],[])
register_horizontal_layers = [
    (mpl_hsec_styles.HS_MyStyle_pl_air_temperature, ["model"]),
    ]
```

And for vertical plots:
```python
mpl_vsec_styles.make_generic_class("VS_MyStyle_pl_air_temperature",'air_temperature','pl',[],[])
register_vertical_layers = [
    (mpl_vsec_styles.VS_MyStyle_pl_air_temperature, ["model"]),
    ]
```

And for line plots simply:
```python
register_linear_layers = [
    (mpl_lsec_styles.LS_DefaultStyle, "air_temperature","pl", ["model"]),
    ]
```

However, this may be too much information for https://mss.readthedocs.io/en/stable/mswms.html , which is already too long in my opinion. It might be a good idea to also restructure this page.

**Comment by ReimarBauer** [comment]
While we restructure the documentation we have to keep urls valid because of linked from our publication. 

We maybe can describe a few minimized examples. These have to become test covered so that we learn when we need to improve them.
