### ISSUE TITLE
performance file selection

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1648]
This is a bug in develop for 8.0

When selecting a file by the "Select" button for performance in table view we currently get:

```
Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/performance_settings.py", line 105, in load_performance
    filename = get_open_filename(
TypeError: get_open_filename() got an unexpected keyword argument 'pickertag'
```

found by the performance tutorial ;)

**Comment by Jatin2020-24** [comment]
Similar can be found when selecting file with "satellite track" in "topview" -> (select to open control) ->  "Satellite Tracks" -> (...)
