### ISSUE TITLE
satellite prediction writes outside the graph

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1649]
The tutorial_satellitetrack.py found a problem using sattelite tracks

It seems when data is not in the range of the map text is printed outside, see example image

used data
docs/samples/satellite_tracks/satellite_predictor.txt

![sattelite_prediction_bug](https://user-images.githubusercontent.com/278728/211037222-0050552a-3951-4477-93ab-bdd3107876b1.png)

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this

**Comment by ReimarBauer** [comment]
you have it, please send a Pull Request to stable branch.

**Comment by ReimarBauer** [comment]
![tutorial_satellitetrack](https://user-images.githubusercontent.com/278728/215855008-55f6f107-0284-4974-9e79-bdc69eb504df.gif)

**Comment by ReimarBauer** [comment]
@jalajk24 have a look on the gifcycle to see where this function is located in the UI.

**Comment by HarshKhilawala** [comment]
@ReimarBauer I would like to work on it. Please assign this issue to me.

**Comment by Bond010** [comment]
This bug is due to incorrect configuration or incorrect data input.
