### ISSUE TITLE
[feature request] allow time browsing for several views simultaneously

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#166]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/166) by Andreas Hilboll (Bitbucket: [andreas-h](https://bitbucket.org/andreas-h), GitHub: [andreas-h](https://github.com/andreas-h)).**

----------------------------------------

It would be a nice feature if on the client, if the user could group several views (sideviews and topviews mixed) together for time browsing (i.e., changing init and valid times).

Use case:

User has several views opened (i.e., different altitude levels plus vertical section) and wants to see the temporal evolution.  Currently, user has to change valid time for each view individually, which is cumbersome.

Suggestion: In the main view of MSS (where i have the lists of hsects and vsects), allow the user to select several views and group (i.e., lock together) them somehow.  Then, if user changes valid or init time in one of the grouped views, all views get updated (i.e., time selection + plot).

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

This feature would certainly be useful. The question is how exactly the locking/unlocking should work in the UI, how it should be visualised, released, etc. 
Further, each layer may, in principle and also often practically, have different valid times.

Practically, this would cause a lot of co-dependence between different views, which as of now are independent and may be closed/opened at any time.
The model of having independent views with independent wms_control docking widgets does not really lend itself to this, implying that a clean, maintainable solution will be difficult to achieve.

**Comment by ReimarBauer** [comment]
We do provide a retriever script. By this one can create all sort of plots and also use other tools like peek for organizing data in gifcycles. I think that gives a majority of flexibility and also enables others to write frontends based on this.

**Comment by joernu76** [comment]
The multi-layering view offers extended functionality, which partially addressed this use-case. Beyond that, the implementation would be too complicated.
