### ISSUE TITLE
update our version string definition, see patch

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1660]
from https://github.com/conda-forge/mss-feedstock/pull/141
```
diff -ruN -x __pycache__ -x obj -x '*~' -x tags -x TAGS MSS-7.0.7.orig/mslib/version.py MSS-7.0.7/mslib/version.py
--- MSS-7.0.7.orig/mslib/version.py	2022-12-07 18:16:45.000000000 +0100
+++ MSS-7.0.7/mslib/version.py	2023-01-30 15:46:44.944598202 +0100
@@ -24,4 +24,4 @@
     See the License for the specific language governing permissions and
     limitations under the License.
 """
-__version__ = u'7.0.7.'
+__version__ = u'7.0.7'
```

Also check all code lines where we use that var.

With solving this we are compatible with recent setuptools.

and undo the fixation of setuptools in our meta.yaml

**Comment by rootxrishabh** [comment]
I'm not quite able to understand this, would be very helpful if @ReimarBauer could guide me a bit more.

**Comment by ReimarBauer** [comment]
The new rules by setuptools forbides a dot at the end of the version string.

The text shows the result of the diff comand. See `man diff`. Zklaus tried this on the build System with patching the code.
See `man patch`

Those lines show by - what gets removed and by + what gets added.


Check where Version is used and solve Problems by this change too.

Ignore the line with meta.yaml this is not here now.

**Comment by rootxrishabh** [comment]
Messed up my first PR, the second one looks ok to me.
