### ISSUE TITLE
missing image on our mswms/mscolab frontpage

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1673]
When you start the local host server, there is an image missing

http://127.0.0.1:8081/mss/install

![missing](https://user-images.githubusercontent.com/278728/221981783-97bbc7d8-b1c7-480a-8ef7-e4bd0526f827.png)

The image should be removed.

**Comment by nilupulmanodya** [comment]
@ReimarBauer  I want to work on this can you please assign me
