### ISSUE TITLE
Tutorial to run MSS in Docker.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [Open-MSS/MSS#1678]
It is an excellent practice to create a docker container for MSS to run on devices with less hassle to set up and hassle-free development.

**Comment by Mr-Sunglasses** [comment]
We can create a docker file by which we can mention in the docs, the steps to run it, and what you think @ReimarBauer .

**Comment by ReimarBauer** [comment]
We had this in the past in this repo, and moved it to an own repository.
it is documted on:

https://mss.readthedocs.io/en/stable/installation.html#use-docker

- https://github.com/Open-MSS/dockerhub
- https://github.com/Open-MSS/singularity

Seems something changed, the last version on dockerhub is 5 month old :(

We do use also a docker container for all the testings here, have a look on https://github.com/Open-MSS/dockertesting

**Comment by ReimarBauer** [comment]
the stable image (https://hub.docker.com/r/openmss/mss) is updated, but that needs to become improved. We should not have this on any commit, only when I set a release tag. Do you know @Mr-Sunglasses how this could be done? The stable image is for users, or none developers.

For the developer indeed it is a good idea to describe, how to use the same image we use for the testing setup here :)
With the regular rebuild  of these images this is pretty save that we catch new build issues early. 

We have to use as developers for stable and develop branch a different image. 

- https://hub.docker.com/r/openmss/testing-stable
- https://hub.docker.com/r/openmss/testing-develop

**Comment by ReimarBauer** [comment]
we should rename the created env in the tests to mssdev|mssstable after the release of 7.0.8. Then all other documentation is consistant. So this or a better description goes into development branch. When we have a good description, we should add it to the pages too. 
8.0.0 will be released before gsoc contribution start.


 
```
Initial or on each updated docker image
---------------------------------------
rm -rf $HOME/miniconda3/envs/mssenv # cleanup the existing env
mkdir $HOME/miniconda3/envs/mssenv  # create the dir to bind to
xhost +local:docker                 # may be needed
docker run -it --rm --mount type=volume,dst=/opt/conda/envs/mssenv,volume-driver=local,volume-opt=type=none,volume-opt=o=bind,volume-opt=device=$HOME/miniconda3/envs/mssenv --network host openmss/testing-stable # do the volume bind
exit                                # we are in the container, escape :)
sudo ln -s $HOME/miniconda3/envs/mssenv /opt/conda/envs/mssenv # we need the origin location linked because hashbangs interpreters are with that path. (only once needed)
conda activate mssenv               # activate env
cd workspace/MSS                    # go to your workspace MSS dir
export PYTHONPATH=`pwd`             # add it to the PYTHONPATH
python mslib/msui/msui.py           # test if the UI starts
pytest ...                          # run pytest

Next Time
---------

xhost +local:docker                 # may be needed
conda activate mssenv               # activate env
cd workspace/MSS                    # go to your workspace MSS dir
export PYTHONPATH=`pwd`             # add it to the PYTHONPATH
pytest                              # run pytest
```

**Comment by Mr-Sunglasses** [comment]
@ReimarBauer Will try to fix it before Gsoc start, I think I'll fix it by 15th March.

**Comment by ReimarBauer** [comment]
when its done, we can rename it to "Tutorial for developers to reuse testing Docker containers" a better name in the release history list.

**Comment by Mr-Sunglasses** [comment]
Yup will do it 👍🏻.

**Comment by ReimarBauer** [comment]
Just because a good place to add this comment :)


we could easily without a dependency to releases add better practises to the pages, e.g.
https://open-mss.github.io/develop/docker_images

pages cannot and should not try to cover the release related documentations. It is more like a supplement to mss.rtfd.io.

**Comment by ReimarBauer** [comment]
related https://github.com/Open-MSS/MSS/issues/1684

**Comment by CipJusCodin** [comment]
Hi, is this issue still open? I'm a beginner to open source contribution. I would be really grateful if someone could guide me or at least source me to basic issues I can help with.

**Comment by ReimarBauer** [comment]
Hi @CipJusCodin 
at the moment I can merge the PR linked to this, the issue gets closed.

Do you want to join us on slack? see https://open-mss.github.io/contributing/

The good first issues were already resolved by others. Let us maybe chat about your interest.

**Comment by CipJusCodin** [comment]
Yes sure. I have sent a mail request to join the slack workspace
