### ISSUE TITLE
Update to new test setup of upcoming major release

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1682]
We have changed the location of our tests. Instead of mslib we have to call it on tests dir

The documentation needs changes, in this section
development.rst#setup-local-testing

**Comment by HarshKhilawala** [comment]
@ReimarBauer Assign me please

**Comment by HarshKhilawala** [comment]
Thanks!

**Comment by HarshKhilawala** [comment]
@ReimarBauer It seems the develop branch already have corrected pytest directory as per this https://github.com/Open-MSS/MSS/blob/develop/docs/development.rst#run-tests . So do you want me to create PR for stable branch?

Correct me if I misinterpreted.

**Comment by ReimarBauer** [comment]
you are right, sorry not checked that before.

stable is the next bugfix release 7.0.8, it does not get any enhancements. All new stuff gets done in develop.
At the time we release 8.0.0 for a short time stable is identical with develop :)
Then it gets 8.0.x releases while develop will become later 9.0.0
