### ISSUE TITLE
pin  werkzeug to >=2.2.3

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1687]
we have no pinning for werkzeug, so it usually gets the newest version on update, we care by this that the update happens on installing 8.0.0

pin  werkzeug to >=2.2.3

I do that also in the new build

**Comment by ReimarBauer** [comment]
remove also line 50 pygeoif. it is duplicated, we keep its pinning until we can verify that the problem is solved requiring its need

**Comment by sratslla** [comment]
Please Assign it to me.
