### ISSUE TITLE
export PYTHONPATH is needed after reboot for developers

### ISSUE THREAD

**Issue by rootxrishabh** [Open-MSS/MSS#1695]
In the [setup instructions](https://open-mss.github.io/develop/Setup-Instructions), the PYTHONPATH variable has "/mss" at the end, however when the repo is cloned then the directory it creates is "MSS" which is upper case, this causes import error issues

**Comment by ReimarBauer** [comment]
This is correct behaviour, the example adds two pathes. 
`pwd` is a simple way to get an absolute path where you are.  So if you cloned to a workdir (default by eclipse) or PycharmProjects (default by pycharm) you can go into the MSS dir and use the command ```export PYTHONPATH=`pwd` ``` (less typing) When you use a setup for mswms you have to add the ~/mss dir too. Backticks surrounding are important :)

When you setup demodata, what you do to develop with the mswms server you have a directory ~/mss

and usually you clone to a workdir

We can't recommend to create demodata in the same dir as where you develop 

The discussed cmd is

```export PYTHONPATH="`pwd`:$HOME/mss"```

We add two pathes :)

**Comment by ReimarBauer** [comment]
Open-MSS is a github organization, you likly want to file issues for the pages to https://github.com/Open-MSS/Open-MSS.github.io

**Comment by ReimarBauer** [comment]
and if possible add also the failure output you find

**Comment by rootxrishabh** [comment]
> This is correct behaviour, the example adds two pathes. `pwd` is a simple way to get an absolute path where you are. So if you cloned to a workdir (default by eclipse) or PycharmProjects (default by pycharm) you can go into the MSS dir and use the command `` export PYTHONPATH=`pwd` `` (less typing) When you use a setup for mswms you have to add the ~/mss dir too. Backticks surrounding are important :)
> 
> When you setup demodata, what you do to develop with the mswms server you have a directory ~/mss
> 
> and usually you clone to a workdir
> 
> We can't recommend to create demodata in the same dir as where you develop
> 
> The discussed cmd is
> 
> `` export PYTHONPATH="`pwd`:$HOME/mss" ``
> 
> We add two pathes :)

Understood, this is the error that I got which I fixed after "export PYTHONPATH="`pwd`:$HOME/MSS" but I was thinking and I remember that I had gotten the same issue when I cloned the repo the first time and I used it again today but gotten the same error, I think the problem is that the variable is not being stored in the ".rc" file which requires the user to use the export command with each startup of the machine. [This](https://stackoverflow.com/questions/13046624/how-can-i-permanently-export-a-variable-in-linux) way we could make the variable permanent.

![image](https://user-images.githubusercontent.com/73490663/223235603-cd0915c9-6dfa-4c12-82cc-fa40dde42b0a.png)

**Comment by ReimarBauer** [comment]
you or anyone can do setup it when you have only one MSS installation the way you described. It is your decission to do it different but when we describe this, we have also to explain all kind of mistakes which than occure which can happen.

e.g.  by a defined path in .rc

![mismatch](https://user-images.githubusercontent.com/278728/223333468-dc5a55e5-8cec-425b-8213-8262aa5448b3.png)

So I prefer to describe it in a way that it always works and keeps room to bring in own ideas, thinking about how to improve it for your own situation. When I give courses with exercises I use the technique courage to the gap, so that the opposite can open own views and ideas for itself and it not only a copy of my thoughts become.

**Comment by ReimarBauer** [comment]
btw. the bash history is searchable, I repeat this command by "ctrl+r pwd"

**Comment by rootxrishabh** [comment]
> you or anyone can do setup it when you have only one MSS installation the way you described. It is your decission to do it different but when we describe this, we have also to explain all kind of mistakes which than occure which can happen.
> 
> e.g. by a defined path in .rc
> 
> ![mismatch](https://user-images.githubusercontent.com/278728/223333468-dc5a55e5-8cec-425b-8213-8262aa5448b3.png)
> 
> So I prefer to describe it in a way that it always works and keeps room to bring in own ideas, thinking about how to improve it for your own situation. When I give courses with exercises I use the technique courage to the gap, so that the opposite can open own views and ideas for itself and it not only a copy of my thoughts become.

Thank you for this information : )

**Comment by sratslla** [comment]
Hi @rishabh, This is something that I faced too. When I first used the export command it worked fine. But after rebooting my PC, it gave me import errors and thus I had to use the export command again. If adding this command in the ".rc" makes this default it will save a line every time the terminal is rerun. Maybe we should add this to the  [setup instructions](https://github.com/Open-MSS/Open-MSS.github.io/blob/gh-pages/docs/develop/Setup-Instructions.md) documentation which is for developers.

**Comment by rootxrishabh** [comment]
Hey @sratslla greetings for the day.
Yes, if we add the command to the ".rc" file(present in the home directory), we will not have to run the 'export PYTHONPATH="`pwd`:$HOME/mss"' every time we rerun the terminal.

The below is to be included in the ".rc" file.
PYTHONPATH='/home/rishabh/MSS:$HOME/mss'
export PYTHONPATH

**Comment by rootxrishabh** [comment]
@ReimarBauer I think this issue has served its purpose, should I go ahead and close it?

**Comment by rootxrishabh** [comment]
Or maybe I could open a similar issue in the docs repo and make changes [here](https://github.com/Open-MSS/Open-MSS.github.io/blob/gh-pages/docs/develop/Setup-Instructions.md)?

**Comment by ReimarBauer** [comment]
let it open as it currently is, I add a hint to the rtfd docs. We need first a new stable before we can change the pages.

There will be more changes for developers there when we have done the changes to the containers.
