### ISSUE TITLE
Airspaces/Airports info downloaded from OpenAIP produces error when download size is 0KB.

### ISSUE THREAD

**Issue by rootxrishabh** [Open-MSS/MSS#1700]
This was observed in this [PR](https://github.com/Open-MSS/MSS/pull/1671#issuecomment-1469562490), When we download the data of airports/airspaces in the MSUI, sometimes the file size that is downloaded is 0Kb, this only happens with the ".xml" files and not with the ".csv" files. Due to this airspaces can't be drawn and an error is thrown which states "ERROR: Tried to draw airspaces without asp files.".The function which draws the airspace is [here](https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mpl_map.py#L379).

Steps to reproduce - 

1) open msui #python mslib/msui/msui.py

2) Open top view and select airports/airspaces from (select to open control) and Update and download both airports and airspaces.

![221437815-cd963e68-8875-457b-9b86-7133d5a63489](https://user-images.githubusercontent.com/73490663/225405539-e7370dcc-b0cf-4c0d-9e85-419b95b3405c.gif)

3) Click on apply and check the CLI. The image is given below for reference when the error is produced.

![image](https://user-images.githubusercontent.com/73490663/225404622-fd2e0da6-aed1-4dec-bd6c-6723e7daf884.png)

**Comment by mahimakaushik-oss** [comment]
I am working on it

**Comment by ReimarBauer** [comment]
looks like this was fixed by https://github.com/Open-MSS/MSS/pull/1710

**Comment by ReimarBauer** [comment]
reopen when it happens again
