### ISSUE TITLE
Multiple Flightpath option resulting in an error

### ISSUE THREAD

**Issue by sratslla** [Open-MSS/MSS#1701]
Steps to Reproduce:-
-> python mslib/msui/msui.py
->open top view, we can see that the Web Map Service is open but in the drop-down menu (select to open control) is shown.
   Even on changing the control, the text does not change
   

https://user-images.githubusercontent.com/93277471/225754881-9fe3fa21-1d26-410a-afea-5a9853f2340e.mp4

**Comment by ReimarBauer** [comment]
I get this one

@Jatin2020-24 please have a look

```
Fatal error in MSS 7.0.8 on Linux-5.4.0-144-generic-x86_64-with-glibc2.27
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/topview.py", line 359, in openTool
    widget = mf.MultipleFlightpathControlWidget(parent=self, view=self.mpl.canvas,
  File "/home/reimar/PycharmProjects/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 130, in __init__
    self.color = self.ft_settings_dict["colour_ft_vertices"]
KeyError: 'colour_ft_vertices'
```

**Comment by ReimarBauer** [comment]
I am not sure if I understand what the Bug you describe in the movie is. We don't change the name of the combo box what is loaded, we keep there the Text  (select to open tool) because all opened widgets are tabs, see bottom of window.

**Comment by sratslla** [comment]
I thought it was a bug and was meant to change when we move between the options as it does with the region cbChangeMapSection ComboBox.

**Comment by ReimarBauer** [comment]
When we would only open one then we could obviously name it to this one, but we can do also something like this

![behaviour](https://user-images.githubusercontent.com/278728/225778854-cd4f4aac-e873-4fca-a5d5-37d988cace09.gif)

By many it is a question which one should be named there, so keeping the current sentence is very flexibel.

**Comment by sratslla** [comment]
Yes, I recently learned about this. It's really cool.

**Comment by sratslla** [comment]
https://user-images.githubusercontent.com/93277471/225779592-b20c3b9b-2166-4f57-9fac-14358b2a0398.mp4

I think this is the error you saw.

**Comment by ReimarBauer** [comment]
I was also investigatiing by try and error a problem in how I could test my changes for the auto installer and didn't readed here.

**Comment by ReimarBauer** [comment]
> 

this needs now also a fix, I guess that is in the docking widget itselfs.

**Comment by sratslla** [comment]
I will give it a try tomorrow. 
Good Night :)

**Comment by ReimarBauer** [comment]
Good night :)

**Comment by joernu76** [comment]
Hi, I think your issue is a misunderstanding about how the interface was designed, maybe in a non-ideal manner.

The test "(select to open control)" indicates that the drop-down-menu is used to open new controls, even though this is a mis-use of this UI element, which typically selects one of many options. Here, it kind of "compresses" several buttons into a list. We also do not remove already open elements from the selection - for simplicities sake.

One could and maybe shoudl redesign the UI to better follow common conventions.

Is this what you refer to in your original issue?

**Comment by sratslla** [comment]
Yes! I misunderstood how the user interface was supposed to operate.
I was able to comprehend how the drop-down menu is supposed to function thanks to @ReimarBauer.

We can modify the user interface; I will investigate how exactly that will function and create a new issue later after suggesting the modifications in the Slack channel.

I'll try to fix the Multiple Flightpath option that produces an error for the time being in the issue.

**Comment by Jatin2020-24** [comment]
> I get this one
> 
> @Jatin2020-24 please have a look
> 
> ```
> Fatal error in MSS 7.0.8 on Linux-5.4.0-144-generic-x86_64-with-glibc2.27
> Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
> 
> Please report bugs in MSS to https://github.com/Open-MSS/MSS
> 
> Information about the fatal error:
> 
> Traceback (most recent call last):
>   File "/home/reimar/PycharmProjects/MSS/mslib/msui/topview.py", line 359, in openTool
>     widget = mf.MultipleFlightpathControlWidget(parent=self, view=self.mpl.canvas,
>   File "/home/reimar/PycharmProjects/MSS/mslib/msui/multiple_flightpath_dockwidget.py", line 130, in __init__
>     self.color = self.ft_settings_dict["colour_ft_vertices"]
> KeyError: 'colour_ft_vertices'
> ```

I've checked it, but not able to reproduce this error. On my PC multiple_flightpath_dockwidget is opening without any error.

**Comment by joernu76** [comment]
@ReimarBauer Maybe the error is related to faulty stored options? I cannot reproduce either.

**Comment by ReimarBauer** [comment]
I can reproduce the problem also when I remove msui-core.conf or set `export MSUI_CONFIG_PATH=/tmp`
The second movie by @sratslla also shows it.

I do have an empty dict there:

![empty_dict](https://user-images.githubusercontent.com/278728/225916584-89835e36-6fd8-44c3-bd47-f4e58d0f4c54.png)


Eventually it happens only with a fresh setup, or no data in the MSUI_CONFIG_PATH


A workaround is for me this, the initialisation should may be done differently.

```
diff --git a/mslib/msui/multiple_flightpath_dockwidget.py b/mslib/msui/multiple_flightpath_dockwidget.py
index c925255b..6c76fa58 100644
--- a/mslib/msui/multiple_flightpath_dockwidget.py
+++ b/mslib/msui/multiple_flightpath_dockwidget.py
@@ -127,10 +127,12 @@ class MultipleFlightpathControlWidget(QtWidgets.QWidget, ui.Ui_MultipleViewWidge
         self.mscolab_server_url = mscolab_server_url
         self.token = token
         self.ft_settings_dict = self.ui.get_settings()
-        self.color = self.ft_settings_dict["colour_ft_vertices"]
+        try:
+            self.color = self.ft_settings_dict["colour_ft_vertices"]
+        except KeyError:
+            self.color = (0, 0, 1, 1)
         self.obb = []
 
-        self.operation_list = False
         self.flighttrack_list = True
 
         # Set flags
```

**Comment by ReimarBauer** [comment]
@joernu76 https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/topview.py#L496

when we have no qsettings file to load then  it crashes. I think we have just to initialize it with the default color.

**Comment by ReimarBauer** [comment]
@sratslla @Jatin2020-24 I also added a first unit test for that module.
