### ISSUE TITLE
rename the mscolab server configuration  USER_VERIFICATION = False

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1726]
We have now the option to verify a users email adress and also to reset a password.

The server configuration option USER_VERIFICATION = False is now misleading.

It should be renamed to MAIL_ENABLED, default should be False, because it needs some configurations for sending mails.

Only when it is True the server should send on a new user the confirmation mail and on password reset request the reset password mail

The "MAIL_ENABLED" flag has the function that without mail configured the server can start.

**Comment by ReimarBauer** [comment]
@nilupulmanodya this is the follow up

**Comment by nilupulmanodya** [comment]
@ReimarBauer I want to work on this. Please assign it to me
