### ISSUE TITLE
improve provided tutorials by converting to mp4 or other format

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1729]
When we use the gifcycles as base the resulting mp4 is smaller than the gif

download the gif for example
https://mss.readthedocs.io/en/latest/tutorials/tutorial_mscolab.html

`ffmpeg -i tutorial_mscolab.gif  -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" tutorial_mscolab.mp4`

from https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line
```
7.5M Mar 31 20:05  tutorial_mscolab.gif
6.4M Mar 31 20:08  tutorial_mscolab.mp4
```

needs further investigation and then an update to
 https://github.com/Open-MSS/MSS/blob/develop/tutorials/tutorials.batch

and the docs ;)

**Comment by rootxrishabh** [comment]
I'll like to work on this.

**Comment by ReimarBauer** [comment]
Thought you took  https://github.com/Open-MSS/MSS/issues/1283 ?
Which one do you want to do?

**Comment by rootxrishabh** [comment]
I'm doing this first, will take #1283 after this.

**Comment by ReimarBauer** [comment]
webm may be much better
https://www.videoproc.com/media-converter/gif-to-webm.htm

We need to know if for such a format some browser limitation exists

`ffmpeg -i inputfilename.gif -c vp9 -b:v 0 -crf 40 outputfilename.webm`

much smaller, we maybe can increase the size again

1.6M Apr  4 21:52 tutorial_mscolab.webm

**Comment by rootxrishabh** [comment]
Moin @ReimarBauer,  
`ffmpeg -y -i last_recording.mp4 -filter_complex "[0:v]crop=1920:1044:0:0, fps=5,scale=854:-1:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=32[p];[s1][p]paletteuse=dither=bayer[cropped]" -map "[cropped]"  -ss 00:00:14 -to 00:04:30  -c:v libvpx-vp9 -crf 40 -b:v 0 -c:a libopus -threads 6 tutorial_waypoints.webm` 
this command converts the .mp4 file generated from the .py file directly to .webm format with a size of 1.5mb in a single command.

As far as compatibility or any limitations with browsers are concerned, all modern browsers support webm as shown [here](https://caniuse.com/webm)

Also, [docs](https://github.com/Open-MSS/MSS/blob/develop/docs/gentutorials.rst) also need updation along with tutorials.batch

**Comment by ReimarBauer** [comment]
meanwhile solved
