### ISSUE TITLE
Fixing the "Connect to MsColab-MSUI" ui on windows

### ISSUE THREAD

**Issue by CipJusCodin** [Open-MSS/MSS#1732]
![image](https://user-images.githubusercontent.com/112339466/229736292-964002b3-bed8-4a88-9cbd-19ace5b6c18c.png)
The ui currently does not show the texts properly on windows.

**Comment by CipJusCodin** [comment]
I propose to fix the issue.

**Comment by ReimarBauer** [comment]
On linux this looks like
![font_issue](https://user-images.githubusercontent.com/278728/229740903-c10864d4-93e4-4e6f-bdfc-9df1a891492f.png)

on my remote windows it looks like
![windows_guacamole](https://user-images.githubusercontent.com/278728/229742024-692345f7-f4e6-494d-acb5-9265571f5cec.png)

@CipJusCodin please investigate if there is a font missing in your windows setup.

**Comment by CipJusCodin** [comment]
<img width="1920" alt="2023-04-04 (1)" src="https://user-images.githubusercontent.com/112339466/229780590-acc58eee-5b94-4799-baf7-0a3d9fc34f74.png">
<img width="1920" alt="2023-04-04 (3)" src="https://user-images.githubusercontent.com/112339466/229780621-7cd1c1c7-2b7b-4555-abba-1ab6bf23dfdf.png">
I connected my laptop to my monitor, left screen is laptop.
Seems it fixes itself when I drag the window to the right side(monitor screen). I can't think of a reason why this is happening besides screen size(14 vs 21 inch)

**Comment by ReimarBauer** [comment]
it may be related to the screen resolution.  What do you have on the laptop screen? or is there some scaling involved?

I assume when you move it back, it gets condensed again.

**Comment by CipJusCodin** [comment]
Yes it does get condensed again.
Display is at recommended default settings, scale 150%, and resolution is 1920*1080

**Comment by ReimarBauer** [comment]
may be do a research on the net what solutions are proposed. 

e.g.
https://forum.qt.io/topic/121234/font-size-on-a-125-display/8

But it should not get worse for those who don't have this scaling problem. 
Sometimes an updated windows/QT also resolves those problems. I remember a time where 4K displays on windows weren't usable.

**Comment by CipJusCodin** [comment]
I did my research, seems that the login page will look perfect on windows only when the scaling is 117% or less, should I redefine the ui? or maybe we can wait for an update and it fixes itself

**Comment by ReimarBauer** [comment]
We better leave this as it is.
