### ISSUE TITLE
rename MSCO properties menu entry in MSUI to "Maintenance"

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1753]

**Comment by ReimarBauer** [comment]
That could become completly different grouped, but I would like to see that **change in 9.0.0**
I dislike also the postfix of operation again in a menu which has this on top.

I think we can add more sections e.g. 

How would it be with

"View Description" should be moved into the main menu

"Edit"
for Rename,  Description, Category ...

"Maintenance"
Archive, Unarchive, Leave, Delete


 e.g. should look like

- [Chat]
- [Users]
- [History]
- [Description]
- [Edit] -> for Rename, Description, Category ....
- [Maintenance] -> Archive, Unarchive, Leave, Delete

**Comment by joernu76** [comment]
I make a simpler proposal. "normal" user stuff goes to the menu, everything requiring any kind of special mod rights goes to maintanance.
I also try to add the archive operation thingie.
