### ISSUE TITLE
Setup up continuous integration for unit tests or a cheap subset thereof (pycodestyle)

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#189]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/189) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

It would be marvellous, if we would have some traffic-light scheme for the current state of the software using the Pipelines and the growing set of tests. On which machine the tests would execute for "free" is obviously a problem...?

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Currently this is done by our institutes jenkins server.

The pipeline of bitbucket would be an option if we can get conda working. Or we may be could use it for pep8 check after we solved #206

**Comment by joernu76** [comment]
Solved by Marilyth.
