### ISSUE TITLE
TimeOut errors on bad internet connection/strange firewall

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1915]
We cannot connect to the MSColab Server on a guest WiFi with very long connection times (>2s), which may or may not be caused by a deep-inspecting firewall.

The timeout should be configurable to provide a work around.
Also, the current timeouts are defined as "magic number" in a wide range of places and the values should be collected to a single instance (as mentioned above, defined in the json configuration).

**Comment by ReimarBauer** [comment]
If your ISP is throttling certain types of traffic or has poor peering with other networks, VPN will mask the traffic and the result is faster.

https://www.cloudwards.net/vpn-internet-speed/#:~:text=Most%20of%20the%20time%2C%20you,your%20connection%20is%20capable%20of
