### ISSUE TITLE
disabling "work asynchronously" checkbox does not (always) ask for saving work.

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1934]

**Comment by joernu76** [comment]
I looked at the code and it, seemingly, simply discards all the work you have done, instead of, e.g., asking if one is sure to discard and/or offering to update/merge with the server.
This is the develop version. 
Am I missing something here?
I unchecked the box expecting a dialogue asking me on how to proceed (resync with server) instead of simply discarding half-an-hour of work; working locally is much faster than working online due to the long round-trip-times with the mscloab-server.

**Comment by ReimarBauer** [comment]
in mss-8.2.0 it behaves on toggling

![toggling](https://github.com/Open-MSS/MSS/assets/278728/84fce37b-1e11-4bb2-a200-5057d5ab1b21)

and on toggling with changes in both

![toggling_changes](https://github.com/Open-MSS/MSS/assets/278728/caf1b959-b92d-4681-9eb2-b48656ff3a58)

**Comment by ReimarBauer** [comment]
there is also a local backup of your work done, in my case on

`~/mss/local_mscolab_data/r.bauer/devel1`

```
more mscolab_operation.ftml 
<?xml version="1.0" encoding="utf-8"?>
  <FlightTrack version="8.2.0">
    <ListOfWaypoints>
      <Waypoint flightlevel="0.0" lat="32.57437275985663" location="" lon="173.51254480286738">
        <Comments></Comments>

```

**Comment by joernu76** [comment]
I will have a closer look. I think it behaved differently for me, but that maybe because I clicked too fast around with latency or whatever.

**Comment by joernu76** [comment]
I still think a pop-up box asking whether to save/sync/discard the features would be less confusing.
Also, we need some simple way to in particular import local flight tracks into operations (currently some people create it locally because it is faster and then have to go via save-to-file/import; this should be less tedious).

**Comment by ReimarBauer** [comment]
We should have a file click on the left site and a drop on the right site. So it gets automatically a new OP or a new named revision (when it is dropped to an existing one)

popup box with the option to discard the box is a good thing

**Comment by ReimarBauer** [comment]
we have already some other none API breaking enhancements, so we can add this popup and go for 8.3.0

**Comment by joernu76** [comment]
Now it works like a charm. I have no idea how I lost my modifications.

That the data jumps back to the server version is scary without a warning, so maybe a one-time popup might be useful?

It is really useful now that I know (again) how it works.

Until I find out how I lost my data, this can be closed.
