### ISSUE TITLE
Installing on Windows with README guidelines causes error/Necessary extra step misses in guideline

### ISSUE THREAD

**Issue by TheHeat3** [Open-MSS/MSS#1951]
Entering the command `mamba install mss python`  in the mssenv environment via the Anaconda CMD.exe Prompt causes the following error, which ultimately leads to the mss package to not be installed:

ERROR conda.core.link:_execute(945): An error occurred while installing package 'defaults::git-2.40.1-haa95532_1'.
Rolling back transaction: done
unknown encoding: utf-16-le
()

LookupError('unknown encoding: utf-16-le')
()

If a specific version is written into the install command, e.g. `install mss=1.8.2 python`, the package number in the error message changes to:

ERROR conda.core.link:_execute(945): An error occurred while installing package 'defaults::fftw-3.3.9-h2bbff1b_1'.
Rolling back transaction: done
unknown encoding: utf-16-le
()

LookupError('unknown encoding: utf-16-le')
()

###

Also, one extra step to enable mamba in the environment is necessary: ` conda install mamba#`
I found this to be non-trivial, as mamba was working fine in the environment implemented into Anaconda by default when installing mambaforge- but only there.

**Comment by joernu76** [comment]
The problem seems to have been a parallel installation of mambaforge and anaconda.
Several problems and pitfalls:
a) There are several cmd prompts; here the wrong one was used here. The "mambaforge prompt" should be used
b) The .condarc is shared between Anaconda and mamba. The "defaults" package repository should not be present, only conda-forge

**Comment by ReimarBauer** [comment]
When someone has a license of anaconda then the mamba command got builtin to the conda command.

 https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community
