### ISSUE TITLE
What to do with "UserWarning: An unhandled message box popped up during your test!"?

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#1957]
There are many of these warnings in the CI logs basically spamming the output and drowning out other more interesting warnings.

These warnings are originating from https://github.com/Open-MSS/MSS/blob/1327ede1dbe3f4eb26bf3889934fa76c74fb428b/conftest.py#L227.

I am not sure why this warning was introduced in the first place, but in my opinion there are two options to handle this better:
1. If it is an issue that there are unhandled message boxes, then this should fail the respective test.
2. If it is not an issue, then we shouldn't flood the output with this warning.

Since I am not too familiar with the internals of the test suite I'd like to discuss how to make this better.

**Comment by ReimarBauer** [comment]
see here, the warning comes from the fixture
https://github.com/Open-MSS/MSS/blob/develop/conftest.py#L214

tests better should fail instead of hiding one cause, some of the tests showing that have to do a second turn. 

Sometimes functionality gets added but not the test improved e.g.

```
call(<mslib.msui.mscolab.MSColab_ConnectDialog object at 0x7fc4c26e3e20>, 'Update Credentials', 'You are using new credentials. Should your settings file be updated with the new credentials?', <PyQt5.QtWidgets.QMessageBox.StandardButtons object at 0x7fc4bfefa880>, 65536), call().__eq__(16384)]
688
    warnings.warn(f"An unhandled message box popped up during your test!\n{summary}")
  
````

If that had failed then we would know better.

**Comment by ReimarBauer** [comment]
I do address some of these test mistakes in the refactor_tests_and_setup branch

**Comment by matrss** [comment]
I cannot find that branch in this repo or in your fork of it. Can you share a link?

I also started to address this issue, I'll open a draft PR shortly.

**Comment by ReimarBauer** [comment]
I started first with py311 this is a rebase to develop
https://github.com/Open-MSS/MSS/tree/refactor_tests_and_setup

I do mostly look on the msui/test_mscolab.py currently


I decided later to make another branch than py311, because the move to py311 should be done seperated.

**Comment by ReimarBauer** [comment]
There are a few more problems which got hidded by this fixture. e.g. the main window does not close. 
also that with the merge of both UIs we need an initial flight track.
