### ISSUE TITLE
MSUI: Window title is very very long and has redundant information

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#1961]
Seen under MSUI 8.1.1 under Windows 11 on a MSColab project. See screenshot below

![grafik](https://github.com/Open-MSS/MSS/assets/114411636/615ac8fa-d65a-4d38-9b9a-bef20fb84faa)

**Comment by ReimarBauer** [comment]
do you have an idea to reproduce that. had that also once last year?

https://github.com/Open-MSS/MSS/issues/1441

**Comment by joernu76** [comment]
Saw that as well, will have a look.

**Comment by joernu76** [comment]
Might be fixed on accident by #1962
Cannot reproduce currently, will observe.

**Comment by joernu76** [comment]
Happens reproducibly when I import a DLRKML file into an operation.
