### ISSUE TITLE
Checkbox for renaming operation-popup does not work

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#1973]
After renaming an operation a popup appears informing the user about the successful renaming. This popup has a checkbox about having this same popup in the future.
Unchecking this checkbox seems to have not effect.

**Comment by ReimarBauer** [comment]
having this unchecked works for me, but QErrorMessage can queue messages, for this info we don't want this, also "Error" is misleading too.

"newer description, as we run"
https://doc.qt.io/qtforpython-6/PySide6/QtWidgets/QErrorMessage.html

**Comment by ReimarBauer** [comment]
Because of the used QErrorMessage used I move this to the next major. The queueing may do the trouble.
