### ISSUE TITLE
Urls in documents, e.g. NOTICE

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#1992]
tango license url has moved?

https://web.archive.org/web/20221210230320/https://github.com/freedesktop/tango-icon-library/blob/master/COPYING.PublicDomain

**Comment by ReimarBauer** [comment]
We maybe should change the url to 
https://web.archive.org/web/20221210230320/https://github.com/freedesktop/tango-icon-library/blob/master/COPYING.PublicDomain

or link to an other repo  https://gitlab.freedesktop.org/tango/tango-icon-library

**Comment by ReimarBauer** [comment]
we can switch to the gitlab Url Looking at the freedesktop org on github it seems like they have moved everything to their gitlab instance: https://github.com/freedesktop

citing @matrss from RC

**Comment by Myrausman** [comment]
Hi @ReimarBauer, I am interested in working on this issue. Could you please assign it to me? Also, please let me know if there is any additional information I should consider while solving the issue.
