### ISSUE TITLE
table view  add ons

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#200]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/200) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

May be the performance dialog could be moved into a docking widget similar as the hexagon flight pattern?

**Comment by aravindm711** [comment]
Hey @ReimarBauer does this redesign look good? https://imgur.com/CkYjQ1a

**Comment by ReimarBauer** [comment]
@joernu76 and/or @Marilyth have a look please

**Comment by Marilyth** [comment]
It looks fine to me, though I am not the best to judge that. 
A few little things bother me design wise, like the field next to `take off time` is shifted a few pixels to the right compared to `take off weight`, `Aircraft:` is not in line with `Fuel`. Generally I am not sure I like the placement of `Aircraft` in pure aesthetics.

Another thing that bothers me on a very personal level is the use of imperial units instead of metric ones.
I will abide, however.

**Comment by aravindm711** [comment]
I have fixed the alignment issues from the previous redesign. https://imgur.com/a/cHqPveW Could you please take a look? @Marilyth.

**Comment by aravindm711** [comment]
I have rethought the placement of the widgets and fixed the alignment issues from the previous redesign. @Marilyth could you please take a look at this? https://imgur.com/z1KeDtP

**Comment by Marilyth** [comment]
I definitely like that one better.

I wonder if the Cancel and OK buttons can be cut, now that it is a dockwidget. 
Though I am not well aware of how MSS is being used in practice, so any further deviations from what is already there should be discussed with @joernu76 or @ReimarBauer

**Comment by aravindm711** [comment]
Thank you for the feedback @Marilyth.

It'd be great if I could get some feedback on what to improve on the proposed redesign @joernu76 @ReimarBauer. ( https://imgur.com/z1KeDtP )

**Comment by joernu76** [comment]
I like the new widget. The OK/Cancel buttons do not make sense anymore as the widget is not "blocking" anymore.
Instead, all other widgets need to be updated now after any change within this widget in contrast to previously, where this was only necessary upon pressing the "OK" button.

**Comment by aravindm711** [comment]
thank you for the feedback @joernu76. I'll look into how i can implement this by removing OK/Cancel buttons and updating other widgets automatically.
