### ISSUE TITLE
MSUI with Windows: TopView window is always on top of MSUI main window

### ISSUE THREAD

**Issue by soerenjoh** [Open-MSS/MSS#2007]
Under Windows 10, MSUI TopView window is always on top of MSUI main window. In addition, the TopView is not appearing in the Windows Task bar (other views are visible there). Alt +Tab also does not allow to change TopView windows.

![grafik](https://github.com/Open-MSS/MSS/assets/114411636/c7980228-ea15-4676-a528-00ec465ec7bd)

Further, "Server/Layer" window is also always on top of corresponding TopView/SideView

**Comment by ReimarBauer** [comment]
compared to KDE linux, 

Top view is in the windows task bar. 
"Server/Layer" window is also always on top of corresponding TopView/SideView.  We can have multiple times views open. Doen't this make sense?

When I use the top left  hotspot corner in KDE all started widgets are displayed side by side.

On any widget of MSS I can bring the main ui into foreground by ctrl+up

**Comment by ReimarBauer** [comment]
@soerenjoh please verify if it is always the first view started which is not shown in the window task bar?
e.g. if you start with table view, is then top view afterwards started in the window task bar.

**Comment by soerenjoh** [comment]
No, it's always the TopView, no matter which window I open first. 
If I start with TableView, and then the TopView afterwards, Table View is started in the task bar, but TopView is not.

**Comment by soerenjoh** [comment]
KDE behaviour seems to be different to windows. Ctrl + up does not have any effect on Windows.

I don't think it makes sense to have Server/Layers on top of the other window all the time. Sometimes I want to switch between layers without needing to close the Server/Layers window (by clicking on the "x"). But with only my laptop screen available (as it is on campaign), I actually need to close Server/Layer every time I want to see the content. I would be more happy if I could uncofus it.

**Comment by ReimarBauer** [comment]
these are two-three different issues. 
please create an issue for handling the server/layer widgets.
There are probably more ideas about that.
e.g. 
on my windows and my kde I have controls to lower down the widget, I also can move it around,
![minimize](https://github.com/Open-MSS/MSS/assets/278728/393efa2c-8dc7-4e9c-8dbc-e18bc691623d)


that the ctrl+up key is not working with windows is also a bug or question. It is easier for me to show on a different issue with images, gifcycles how it works for me in guacamole. 


I checked with 7.0.8, there topview was getting an own windows tab entry
![windows_mss708_topview_in_taskbar](https://github.com/Open-MSS/MSS/assets/278728/b63f0523-d568-483c-b533-733077d5e452)


With the refactoring of topview we introduces the problem. 
https://github.com/Open-MSS/MSS/compare/7.0.8...8.0.0#diff-8ef25679b45fd2a5333ae5758a94f8c8e152759307c381b6f5623512c69d546aR194

**Comment by soerenjoh** [comment]
I will open the new issue. 
I found the original issue with version 8.1.1

**Comment by ReimarBauer** [comment]
tracked it down, the fix needs an API change
