### ISSUE TITLE
refactor OGC WMS from 1.1.1 to 1.3.0

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#201]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/201) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Version 1.1.1 is deprecated

http://www.opengeospatial.org/standards/wms

We have to move on to 1.3.0

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

see #270 for further ideas

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

we should replace our dependcy of the paste server by a microframework e.g. flask or bottle.

**Comment by Marilyth** [comment]
I would like to avoid reading through two 80+ page documents and finding their differences, if in any way possible.
So I found this little summary of differences between 1.1.1 and 1.3.0, which seems oddly small.
https://docs.geoserver.org/latest/en/user/services/wms/basics.html#differences-between-wms-versions

Is this accurate, or did they leave something important out?

**Comment by ReimarBauer** [comment]
I think that's all. The main point is that ordering. 

https://gis.stackexchange.com/questions/23347/getmap-wms-1-1-1-vs-1-3-0

http://dmorissette.blogspot.com/2012/12/dont-upgrade-to-wms-130-unless-you.html
