### ISSUE TITLE
Server not WMS compliant for non-existing elevation levels

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#204]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/204) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

For elevation/level values, for which no data values are given, the server currently selects the data belonging to the next lower level.
According to specification, it should not do that, but give an Error.
Alternatively, the WMS specification allows the Server to specify that it will give the Nearest available level instead. In this case, it needs to indicate this behaviour in its capability document and also give an HTML warning.

The current behaviour of rounding down isn't very sensible.
As a quick fix, we could raise an Exception if the level is not present. In case of floating point values, we probably need to define a sensible error margin due to the float->ascii->float conversion involved.

The more useful behaviour would probably be returning the nearest value, but according to specification, which implies informing the client about it in HTML warnings.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

For elevation/level values, for which no data values are given, the server currently selects the data belonging to the next lower level.
According to specification, it should not do that, but give an Error.
Alternatively, the WMS specification allows the Server to specify that it will give the Nearest available level instead. In this case, it needs to indicate this behaviour in its capability document and also give an HTML warning.

The current behaviour of rounding down isn't very sensible.
As a quick fix, we could raise an Exception if the level is not present. In case of floating point values, we probably need to define a sensible error margin due to the float->ascii->float conversion involved.

The more useful behaviour would probably be returning the nearest value, but according to specification, which implies informing the client about it in HTML warnings.

**Comment by Marilyth** [comment]
When I request a level that does not exist, e.g. 478.0 when both 500.0 and 400.0 exist, the server throws the exception
`Error message: 'Requested elevation not available.' `
Am I missing something, or was this fixed already?

**Comment by ReimarBauer** [comment]
Please check if we have a test which asserts the exception. A test is welcome so that we don't get it wrong again.
