### ISSUE TITLE
typo in endpoint of gdpr

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2067]
unfortunately it is gpdr in develop

**Comment by Beeram12** [comment]
@ReimarBauer Should I change gdpr to gpdr in all files .

**Comment by ReimarBauer** [comment]
GDPR stands for: General Data Protection Regulation (GDPR)

There is one string were I did a typo. This one needs to become fixed.

**Comment by Beeram12** [comment]
@ReimarBauer may I know the location the file so that I could fix that issue

**Comment by ReimarBauer** [comment]
Hi, yes

But I think it is better when you use search in your Python IDE. Pycharm or vscode should have  a function for this.

Which development environment do you use?

**Comment by Beeram12** [comment]
Yes,
I use vscode.Yeah as you said I used search in vscode to find the typo but
I am getting  many files containing the typo so I asked like is there any
particular file to be changed or the total codebase should be changed.

**Comment by ReimarBauer** [comment]
When you search for GPDR?

Make a screenshot please. 

It looks to me that you want to repeat my typo.

**Comment by Beeram12** [comment]
@ReimarBauer Sorry it was my mistake I misunderstood your description
