### ISSUE TITLE
Unnecessary line in .gitignore?

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2070]
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/.gitignore#L28
> Where was that line coming from again? I cannot remember what this path was used for. Is it still required?

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384596047_

**Comment by nilupulmanodya** [comment]
@matrss  I hope to work on this, please assign me
