### ISSUE TITLE
Missing newline after last line

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2071]
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/docs/samples/config/mscolab/mss_saml2_backend.yaml.samlple#L116
> This file is missing a newline after the last line.

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384630111_

**Comment by nilupulmanodya** [comment]
@matrss  I hope to work on this, please assign me
