### ISSUE TITLE
Make VERIFY_SSL_CERT config name more descriptive

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2073]
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/mslib/mscolab/conf.py#L121
> This config option name should somehow make clear that it only applies to the certificates used between MSColab as a SAML SP and the IdP, nothing else.

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384799865_

**Comment by nilupulmanodya** [comment]
@matrss I want to work on this, please assign me
