### ISSUE TITLE
Do not use `sleep` as a synchronization primitive

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2074]
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/mslib/mscolab/mscolab.py#L278
> Not really optimal to use sleep as a synchronization primitive here (ideally it should wait until `process` signals that it is ready in some way, e.g. when process' stdout contains something that indicates that the server is up and running). This is not a very critical code path though, so not too much of a concern.

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384852664_

**Comment by nilupulmanodya** [comment]
@matrss I want to work on this, please assign me
