### ISSUE TITLE
Do not disable local account creation when an IdP is configured

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2076]
> https://github.com/Open-MSS/MSS/blob/f6b3ad110dbfaa12d439cadea6476dcd54d9328d/mslib/msui/mscolab.py#L242-L245
> Shouldn't it still be possible to register a new non-IdP user on the MSColab instance, even if an IdP is configured? I feel like disabling "local" account registration should be a different config option (that would need to be enforced server-side).

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384874147_
            

> also in the workflow of profile/usercreation by the IDP is not completed. The new profile is not activated, it would need a validation (recover password attempt currently) first. There some changes we have to think about after we merged this in.

_Originally posted by @ReimarBauer in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384930546_

> We have to verify too that a user with a "None" Password because of IDP can't fetch one and update that 'None' over password recovery.  Some of these parts need a coverage by tests.

_Originally posted by @ReimarBauer in https://github.com/Open-MSS/MSS/pull/2069#discussion_r1384946717_

**Comment by ReimarBauer** [comment]
When an IDP is configured this needs to have precidence. Using an IDP means creating a profile, this is a user object without a password. Login works only together with the IDP. No bypass possible. An unknown user of the system gets on first login by using a configured IDP a profile and has access.

We have to take care that the same "account/profile" can't become created twice or the precidence of the IDP can be changed without calling an admin.
