### ISSUE TITLE
define xmlsec_binary path dependent to used env

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2084]
We discussed in https://github.com/IdentityPython/pysaml2/issues/913 using libxmlsec1-feedstock  for the xmlsec1 binary

We can set its location by
https://pysaml2.readthedocs.io/en/latest/howto/config.html#xmlsec-binary

The solution needs to use the conda env var for locating the "env"/bin where it is

Currently we set the PATH var in the WSGI Script.

**Comment by nilupulmanodya** [comment]
@ReimarBauer I hope to work on this. please assign to me.

**Comment by ReimarBauer** [comment]
see  CONDA_PREFIX  in e.g.  https://stackoverflow.com/questions/36539623/how-do-i-find-the-name-of-the-conda-environment-in-which-my-code-is-running
