### ISSUE TITLE
use UTC based timestamps

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2122]
We use in mscolab `datetime.datetime.now() `
This can have a timezone issue, we should replace it by a timezone based on UTC
`datetime.datetime.now(tz=datetime.timezone.utc)`

**Comment by akshatgokul** [comment]
I would like to work on this issue, can you please assign this to me?

**Comment by ReimarBauer** [comment]
sorry for the delay, you have it .

**Comment by Preetam-Das26** [comment]
Is this issue open?
@ReimarBauer

**Comment by ReimarBauer** [comment]
@Preetam-Das26 yes, the PR was not finished.

**Comment by vikas-chaudhary-2802** [comment]
I would like to work on this issue, can you please assign it to me ??

**Comment by Preetam-Das26** [comment]
@ReimarBauer Ok can you please assign this issue to me?

**Comment by vikas-chaudhary-2802** [comment]
@ReimarBauer please assing this issue to me.

**Comment by Preetam-Das26** [comment]
@ReimarBauer   I am getting this error during tests:
during,
invoke dockertesting image creation:


🏃 Workflow Dispatch Action v1.2.1
Error: Parameter token or opts.auth is required



Can you please help me resolve it?

**Comment by ReimarBauer** [comment]
@Preetam-Das26 I assume you have not sent a  pull request to this repository? What exactly did you do to get this?

**Comment by matrss** [comment]
There are more instances of `datetime.now()` remaining:
```
$ git grep -n '\.now()'
docs/samples/automation/retriever.py:191:        path = [(wp[0], wp[1], datetime.datetime.now()) for wp in wps]
mslib/mswms/mss_plot_driver.py:519:        d1 = datetime.now()
mslib/mswms/mss_plot_driver.py:527:        d2 = datetime.now()
mslib/mswms/mss_plot_driver.py:558:        d3 = datetime.now()
mslib/mswms/mss_plot_driver.py:646:        d1 = datetime.now()
mslib/mswms/mss_plot_driver.py:654:        d2 = datetime.now()
mslib/mswms/mss_plot_driver.py:684:        d3 = datetime.now()
mslib/mswms/mss_plot_driver.py:851:        d1 = datetime.now()
mslib/mswms/mss_plot_driver.py:858:        d2 = datetime.now()
mslib/mswms/mss_plot_driver.py:870:        d3 = datetime.now()
mslib/utils/mssautoplot.py:69:    now = datetime.now()
mslib/utils/mssautoplot.py:107:        self.path = [(wp[0], wp[1], datetime.now()) for wp in self.wps]
tutorials/tutorial_waypoints.py:125:    current_time = datetime.datetime.now().strftime('%d-%m-%Y %H-%M-%S')
tutorials/utils/screenrecorder.py:66:        current_time = datetime.datetime.now().strftime('%d-%m-%Y_%H-%M-%S')
tutorials/utils/screenrecorder.py:107:        ini_time_for_now = datetime.datetime.now()
tutorials/utils/screenrecorder.py:159:                if datetime.datetime.now() >= future_date_after_120seconds:
```

**Comment by ReimarBauer** [comment]
We have to be carefully not to create a dependency to mscolab in the mswms, tutorials code parts.
