### ISSUE TITLE
Add GitHub actions to run tests on windows and macos

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2129]

**Comment by ReimarBauer** [comment]
we have to cover
osx osx_64 and osx_arm64

the last one gets more popular

**Comment by matrss** [comment]
It looks like M1 runners are now in beta: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

This must be a relatively recent addition, I am pretty sure I've checked at the beginning of january and they weren't available then.

The main issue is that the container setup is not usable on MacOS (nor Windows). This makes it currently impossible to just add additional `runs-on:` parameters to the test matrix, since dependency installation cannot be handled in the same way. But I also don't want to duplicate the entire workflow.

**Comment by matrss** [comment]
Closing in favor of #2284, #2285, and #2286, i.e. consider testing on each platform to be their own issues.
