### ISSUE TITLE
state of  osx-arm64 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2130]
We got a request by a participant of the CAESAR campaign, Feb 20-April 7, if MSS can be installed on an M2 apple.

Currently this is not possible. I suggested to use our docker image, https://mss.readthedocs.io/en/stable/installation.html#docker-instance

Recently basemap  with 1.3.9 was added for osx-arm64. 

We have to review what blocks us to use a ARM OSX Migrator for our package, similiar to https://github.com/conda-forge/basemap-feedstock/pull/123

**Comment by ReimarBauer** [comment]
The dockerimage has currently INFO: MSS Version: 8.3.2

and was updated to 8.3.3

**Comment by ReimarBauer** [comment]
tried manually https://conda-forge.org/blog/2020/10/29/macos-arm64/ which might work

https://github.com/conda-forge/mss-feedstock/pull/168


There are some not on the list, so trying the bot now.
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

**Comment by ReimarBauer** [comment]
looks like we can cross compile this https://github.com/conda-forge/mss-feedstock/pull/168
The question is how can we check it.

**Comment by ReimarBauer** [comment]
Another option could be 
https://conda-forge.org/docs/user/tipsandtricks.html#installing-apple-intel-packages-on-apple-silicon

**Comment by ReimarBauer** [comment]
Looking on https://anaconda.org/conda-forge/pyqt/files?page=4

the first osx-arm64 is a pyqt-5.15.4 version. 

Version 8.X.X can't be used with this type of processor because we need there a pinning of pyqt >=5, <5.13
This changes with version 9.

**Comment by yu71ng** [comment]
Hello, 
my working laptop is also with M2 apple and I've encountered the same issue. We will have a flight campaign this summer (ORCESTRA campaign), where we would like to use MSS. Do you have a rough estimate, when this issue could be solved?

**Comment by ReimarBauer** [comment]
Hi @yu71ng 
we plan to release 9.0.0 in the next weeks.  
There are a few issues remaining https://github.com/Open-MSS/MSS/milestone/93

Help is welcome :)

**Comment by yu71ng** [comment]
Maybe for an in-between solution, it came to my attention to do as follows: https://stackoverflow.com/questions/71515117/how-to-set-up-a-conda-osx-64-environment-on-arm-mac

Just change the setting in the mss-environment before installing the mss software:

`conda config --env --set subdir osx-64`
 
 With that, I can run mss 8.X.X. on a M2 Apple :)

**Comment by ReimarBauer** [comment]
Great @yu71ng , thx to letting us know :)

**Comment by ReimarBauer** [comment]
After the release of 8.3.5 and its cross compilation we can verify if missing packages are available.

**Comment by ccostanza10** [comment]
Hi there! I'm in the process of trying to install MSS on my Apple M2 chip. Based on the suggestions from @yu71ng, I tried the following

```
conda config --env --set subdir osx-64
conda config --add channels conda-forge
conda create -n mssenv
conda activate mssenv
conda install mss=9.3.0 python --solver=libmamba
```
Then I'm getting the following error

```
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: | menuinst Exception
Traceback (most recent call last):
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/conda/gateways/disk/create.py", line 259, in make_menu
    menuinst.install(
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/menuinst/api.py", line 170, in _install_adapter
    install(metadata, target_prefix=prefix, **kwargs)
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/menuinst/utils.py", line 426, in wrapper_elevate
    return func(
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/menuinst/api.py", line 62, in install
    paths += menu_item.create()
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/menuinst/platforms/osx.py", line 79, in create
    self._copy_icon()
  File "/Users/costanza/miniforge3/lib/python3.10/site-packages/menuinst/platforms/osx.py", line 113, in _copy_icon
    shutil.copy(icon, self.location / "Contents" / "Resources")
  File "/Users/costanza/miniforge3/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/costanza/miniforge3/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/costanza/miniforge3/envs/mssenv/Menu/msui.icndone
```

I'm tried to install a few different ways with mamba or conda now, so maybe I need to do full clean our of the mssenv dir on my system before I try to install again?

**Comment by ReimarBauer** [comment]
Hi @ccostanza10 
this issue is closed because we updated the package and the installation description. We will do for version 10 another update to the installation description because we got aware that the packages of conda-forge and anacondas default are mismatching.
https://conda-forge.org/docs/user/transitioning_from_defaults/#a-historical-note

I do have a M4 myself and for me the [manual](https://mss.readthedocs.io/en/stable/installation.html#manual) installation works, but I also have no anaconda license or anaconda pre installed. I am not sure if `conda config --env --set subdir osx-64` makes now problems.

Because of the anaconda defaults and conda-forge mismatch and because of the features of pixi for development we will change to a pixi installation for version 10.

This gets into the documentation in the next release after we merged 

https://github.com/Open-MSS/MSS/pull/2632/files#diff-d9b149498982c0663c3b7170398773361ed5678f1a627e9c2fd8d2c955c563db

please try the pixi installation described there.

**Comment by ccostanza10** [comment]
Hey @ReimarBauer!

Right, I tried the manual install with miniforge3 first, and I got the same error. That I listed in the previous mesage.

I did just try the `pixi global install mss`, and that worked without error! Excellent! Thanks for your help in figuring this out. Looking forward to testing out MSS.
