### ISSUE TITLE
provide an amount of good to destinguish colors

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2143]
e.g. 

https://sashamaps.net/docs/resources/20-colors/

we can use by the color picker, but we should have this in  the selection box

**Comment by AryanBakliwal** [comment]
Good Evening @ReimarBauer, do we need need to replace the basic colors with the one you provided in the link like this

Previous dialog
![image](https://github.com/Open-MSS/MSS/assets/106430579/0ab41329-110b-4f6f-b6a6-2104a52d720a)

New dialog
![image](https://github.com/Open-MSS/MSS/assets/106430579/79c26039-31d6-4a1d-968a-354f7dda970d)
