### ISSUE TITLE
The test suite leaves a lot of trash in /tmp and CWD

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2148]
The test suite is creating temporary directories that it does not cleanup afterwards. I am not yet sure where they are coming from or if this is only a side-effect of when the test suite crashes.

**Comment by matrss** [comment]
After cleaning up, a single successful test suite run on the latest develop branch left this in /tmp:
```
$ ls -la /tmp/tmp*
/tmp/tmp16_y1fyq:
total 144
drwxrwxr-x  3 icg149 icg149   4096 Feb 16 12:30 .
drwxrwxrwt 36 root   root   135168 Feb 16 12:31 ..
drwxrwxr-x  2 icg149 icg149   4096 Feb 16 12:30 msui_wms_cache

/tmp/tmpiy183g69:
total 144
drwxrwxr-x  3 icg149 icg149   4096 Feb 16 12:30 .
drwxrwxrwt 36 root   root   135168 Feb 16 12:31 ..
drwxrwxr-x  2 icg149 icg149   4096 Feb 16 12:30 msui_wms_cache

/tmp/tmplv6_vzxc:
total 144
drwxrwxr-x  3 icg149 icg149   4096 Feb 16 12:29 .
drwxrwxrwt 36 root   root   135168 Feb 16 12:31 ..
drwxrwxr-x  2 icg149 icg149   4096 Feb 16 12:30 msui_wms_cache

/tmp/tmpxi8oehy0:
total 144
drwxrwxr-x  3 icg149 icg149   4096 Feb 16 12:31 .
drwxrwxrwt 36 root   root   135168 Feb 16 12:31 ..
drwxrwxr-x  2 icg149 icg149   4096 Feb 16 12:31 msui_wms_cache
```

It also created an osfs: directory in the CWD, for some reason:
```
$ ls -R osfs\:/
'osfs:/':
tmp

'osfs:/tmp':
tmpkb38g7u6msui167af85de1  tmpzsgyrmi7msui167af85de1

'osfs:/tmp/tmpkb38g7u6msui167af85de1':
msui-core.conf

'osfs:/tmp/tmpzsgyrmi7msui167af85de1':
msui-core.conf
```

**Comment by ReimarBauer** [comment]
This happens when os.path is used but not getsyspath from the fs object https://docs.pyfilesystem.org/en/latest/concepts.html#system-paths

**Comment by ReimarBauer** [comment]
> It also created an osfs: directory in the CWD, for some reason:

This should not be done by the test_suite  see

https://github.com/Open-MSS/MSS/blob/develop/mslib/utils/config.py#L470
https://github.com/Open-MSS/MSS/blob/531cb75769e51ae7c1403dc202892873265ad66d/mslib/utils/config.py#L499

**Comment by matrss** [comment]
The tests for it set `ignore_test=True`, here: https://github.com/Open-MSS/MSS/blob/531cb75769e51ae7c1403dc202892873265ad66d/tests/_test_utils/test_config.py#L52 and here: https://github.com/Open-MSS/MSS/blob/531cb75769e51ae7c1403dc202892873265ad66d/tests/_test_utils/test_config.py#L56-L57

This means the early return you reference is not used and the osfs:/ directory is created.

Sidenote: we really should not have application code behave differently depending on if it runs in a test or not, it makes the application code running outside of tests untested by definition.
