### ISSUE TITLE
Replace occurrences of `tests.utils.wait_until_signal` with `qtbot.wait_signal`

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2156]
The `wait_until_signal` function has the limitation that it starts listening for a signal only *after* the code that should emit that signal was called. This means there is a time window in between these calls in which the signal could be emitted but is not seen by the wait. I.e. a race condition.

The `wait_signal` context manager from pytest-qt does not have this issue because it wraps the code that is expected to emit the given signal in a `with` block and therefore starts listening *before* the signal has a chance to be emitted.

**Comment by rohit2p** [comment]
@matrss correct me if i am wrong, according Recommended approach i need to replace `wait_until_signal ` function with `qtbot.wait_signal ` within `with ` blocks.
so for that i need make changes in this this files:-
<img src="https://github.com/Open-MSS/MSS/assets/108990670/f48989a9-7629-4d6b-b8ad-8f5ed748875b" width="500" height="400">
by replacing with this for example:
```
with qtbot.wait_signal(self.wms_control.cpdig.canceled):
    # I'll adjust the signal names (cpdig.canceled, image_displayed, etc.) to match the actual signals

```
while doing this ill be importing qtbot like this:
`from pytestqt.qtbot import qtbot`

But, what do i do with the function `wait_until_signal` in `utils.py`should i remove it since we'll be using `qtbot.wait_signal` insted.
or is their anything more that should be done to solve this issue ? just wanted to confirm before making the changes.

**Comment by matrss** [comment]
> @matrss correct me if i am wrong, according Recommended approach i need to replace `wait_until_signal ` function with `qtbot.wait_signal ` within `with ` blocks. so for that i need make changes in this this files:- <img alt="" width="500" height="400" src="https://private-user-images.githubusercontent.com/108990670/307609486-f48989a9-7629-4d6b-b8ad-8f5ed748875b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NDI3MjAsIm5iZiI6MTcwODk0MjQyMCwicGF0aCI6Ii8xMDg5OTA2NzAvMzA3NjA5NDg2LWY0ODk4OWE5LTc2MjktNGQ2Yi1iOGFkLThmNWVkNzQ4ODc1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMDEzNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTMxYTY5ZTZlN2ZiYmI0ZTY3MDNmN2RiNjYyZGE4MTgxYzhmNjhiNjA4ZjMzMWFhYzRmYTQ5Y2QwYmQ5NGVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6qc-17XnBpuv5qHPI_Jn9vl-n4AGFU1Il7hGU4qSSiQ"> by replacing with this for example:
> 
> ```
> with qtbot.wait_signal(self.wms_control.cpdig.canceled):
>     # I'll adjust the signal names (cpdig.canceled, image_displayed, etc.) to match the actual signals
> ```

Yes, exactly.

> while doing this ill be importing qtbot like this:
> `from pytestqt.qtbot import qtbot`

No, qtbot is a pytest fixture (<https://docs.pytest.org/en/stable/how-to/fixtures.html#how-to-fixtures>). That means it just needs to be added as a function argument to the test function, if it isn't there already. You can grep for `qtbot` in tests/ to see how it is used in other places.

> But, what do i do with the function `wait_until_signal` in `utils.py`should i remove it since we'll be using `qtbot.wait_signal` insted.

When it is no longer used anywhere it can be removed.

> or is their anything more that should be done to solve this issue ? just wanted to confirm before making the changes.

This should be all.
