### ISSUE TITLE
Simplify route definition for mss_theme

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2178]
In the following route definition the `<name>` parameter must always be "img", so we might as well hardcode it:

https://github.com/Open-MSS/MSS/blob/6bf94d35b4d49f1c24a161ff61a96542f9e6ac8b/mslib/index.py#L98-L104

Also, I think the route with a default is unnecessary.

**Comment by vikas-chaudhary-2802** [comment]
I love to work on this issue, Can you assign me ??

**Comment by matrss** [comment]
Sure

**Comment by workaryangupta** [comment]
@matrss @ReimarBauer Kindly checkout this PR #2218
