### ISSUE TITLE
Simplify route definition for xstatic route

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2179]
In the following route definition the filename must always be truthy, so the route with a default seems to make no sense:

https://github.com/Open-MSS/MSS/blob/6bf94d35b4d49f1c24a161ff61a96542f9e6ac8b/mslib/index.py#L87-L96

**Comment by workaryangupta** [comment]
I would like to work on this, can you assign this to me?

**Comment by matrss** [comment]
Sure
