### ISSUE TITLE
Database queries should return aware datetime objects

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2182]
Right now queries for e.g. the `User.confirmed_on` field in mscolab, but also other datetime database fields, return naive datetime objects in UTC. This is bad for the same reason as documented with the `datetime.utcnow()` function here: https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow

This came up in https://github.com/Open-MSS/MSS/pull/2177#discussion_r1482685642.

Related to #2122 and #2183.

**Comment by Preetam-Das26** [comment]
@matrss ,I would like to work on this issue.

**Comment by matrss** [comment]
There are two more columns that should be changed to use the AwareDateTime type:
```
$ git grep -n "db.DateTime"
mslib/mscolab/models.py:184:    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
mslib/mscolab/models.py:208:    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
```

**Comment by matrss** [comment]
It might be necessary to fix this issue as well as the remaining parts of #2183 and #2122 in one PR, because the test suite would not pass otherwise. At least that is what I saw when I checked what happened if I just replace the column type.

**Comment by ReimarBauer** [comment]
on mswms, or msui, or tutorials it has a differnt scope as in the mscolab database. We should not  create by an import a dependency that they are not independent after the change.

**Comment by Preetam-Das26** [comment]
Sorry for skipping these parts. I will make the necessary changes.
