### ISSUE TITLE
Do not use `datetime.datetime.utcnow()`

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2183]
There are multiple locations where this function is used. It is documented as being potentially dangerous and should be replaced with `datetime.datetime.now(tz=datetime.timezone.utc)`: https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow

This came up in https://github.com/Open-MSS/MSS/pull/2177#issuecomment-1933712007.

Related to #2122.

**Comment by vikas-chaudhary-2802** [comment]
i love to work on this issue, can you please assign me ?

**Comment by matrss** [comment]
Sure.

**Comment by Preetam-Das26** [comment]
Can I work on this issue?  @matrss

**Comment by matrss** [comment]
There are more instances of `utcnow()` remaining:
```
$ git grep -n 'utcnow'
mslib/mscolab/models.py:184:    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
mslib/mscolab/models.py:208:    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
mslib/msui/wms_control.py:478:            datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)))
mslib/msui/wms_control.py:480:            datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)))
mslib/msui/wms_control.py:843:                        end_time = datetime.utcnow()
```

**Comment by ReimarBauer** [comment]
We have to be carefully not to create a dependency to mscolab in the msui code parts.

**Comment by Myrausman** [comment]
Hey @ReimarBauer , Can I work on the remaining issue and could you please assign it to me?
