### ISSUE TITLE
update the "Manual" installation instruction on stable

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2200]
This is the current released docu https://mss.readthedocs.io/en/stable/installation.html

We need a backport from develop https://github.com/Open-MSS/MSS/blob/develop/docs/installation.rst on stable
because some of the links on our released installation page are broken.

**Comment by Preetam-Das26** [comment]
I would like to work on this issue @ReimarBauer

**Comment by ReimarBauer** [comment]
@Preetam-Das26 you have it, this needs a Pull Request to the stable branch.

**Comment by Preetam-Das26** [comment]
I have to incorporate the changes in the develop branch of the installation.rst to the stable branch of installation.rst  right?
@ReimarBauer

**Comment by ReimarBauer** [comment]
@Preetam-Das26 yes, when you verify the used links in stable you see that they are now broken. I had not expected that at the time I changed them in develop.
