### ISSUE TITLE
Backport tests overhaul to stable

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2204]
The recent changes to the test suite and some CI parts that targeted develop should have gone to stable instead. I need to backport them.

**Comment by matrss** [comment]
> The recent changes to the test suite and some CI parts that targeted develop should have gone to stable instead.

I've tried to backport some of it and looking at the conflicts I now disagree with my above statement. There were some changes to the test suite on develop already that would have made a merge from stable to develop a major headache, in my opinion. So I think it was right to target develop first.

I could still backport all of this, but I am not sure if it is worth the effort when the next major release would bring it to stable anyway, without any additional effort. It also doesn't fix any immediate bugs that are on stable right now (I think), it just makes the test suite sane(r).

So I consider not doing this.

**Comment by ReimarBauer** [comment]
agreed

**Comment by matrss** [comment]
OK, I'll close this then.
