### ISSUE TITLE
Remove too broad mocking of QMessageBox

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2210]
There are some tests in `test_wms_control.py` which still have a too broad mock on QMessageBox. One of them is this one: https://github.com/Open-MSS/MSS/blob/167af85de1ae22293bacb423886991af0e70c7d3/tests/_test_msui/test_wms_control.py#L115-L121

Ideally I'd want this:
- since the assert only checks `.critical`, only that part should be mocked
- the mock should be moved into the function as a context manager in a `with:` statement around the `query_server` call
  - this isn't really that important in this instance, but in general for larger tests this makes it easier to understand which part a mock is needed for and to avoid accidentally affecting other parts of a test
- replace `.call_count == 1` with `.assert_called_once()`, since the mock already provides that as a method
  - or even `.assert_called_once_with(...)` and making sure that the critical message box has an error message that we expect

**Comment by rohit2p** [comment]
Can i work on this? @matrss

**Comment by rohit2p** [comment]
@matrss I have closed PR #2219 Unfortunately, I mistakenly included some older commits along with the intended changes. I apologize for any confusion.

**Comment by matrss** [comment]
No problem. Just FYI: it is possible to fix this kind of situation with a combination of `git reset`/`git rebase -i develop` and `git push --force-with-lease`. There is a lot git can do with the right incantation :)

**Comment by rohit2p** [comment]
Thankyou for your understanding and helpful advice. I'll definitely keep this in mind for future situations.
