### ISSUE TITLE
sideview out of valid data range causes strange extrapolated values

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#2226]
When having a flight path that extends out of the geographical range of the data, the sideview plots include a strange extrapolation. There should be no data displayed for way points outside the valid range.

This shoes the (correctly) displayed data  range and the flight path:
![topview_chile](https://github.com/Open-MSS/MSS/assets/32653190/f1fdab79-9ce2-4f08-b09b-3b77a597a1b3)
and this the corresponding side view
![sideview_chile](https://github.com/Open-MSS/MSS/assets/32653190/2bffa0f5-0961-45ee-a07a-018c6a803250)
From about half way between the first and second waypoint on the left to the right end of the plot, there are no available data.

**Comment by joernu76** [comment]
This is caused by the 2-D interpolation of the vertical cross-sections, which assumes a 360° coverage.
The code has to be changed to handle *both* global data and local data.
Looking at the code, the global data interpolation probably also works only most of the time, but not for all edge cases.

**Comment by jgrooss** [comment]
seems not fixed, see https://github.com/Open-MSS/MSS/pull/2257

**Comment by jgrooss** [comment]
sorry, my fault. It is fixed. The branch can be closed
