### ISSUE TITLE
Develop - seed module needs always to use mscolab_settings.ARCHIVE_THRESHOLD 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2227]
In the seed module, there are still some hardcooded,  dateutil.relativedelta.relativedelta(months=2) 
the 2 must be exchanged by  mscolab_settings.ARCHIVE_THRESHOLD

**Comment by workaryangupta** [comment]
I would like to work on this issue.

**Comment by ReimarBauer** [comment]
@workaryangupta this needs to go into stable

**Comment by ReimarBauer** [comment]
@workaryangupta 
my mistake, the code part were refactored in develop, we can't do API Changes in stable.
