### ISSUE TITLE
wms map server change should delete last view

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#224]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/224) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

If one changes the wms map server url the old image stays intact and only a get map updates to the new one.

I think we should empty the existing view so that it is clear that it get map needs to be clicked

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

I disagree (weakly). The title of the image gives a clear indication of what is depicted.

There is no tight connection between the buttons below and the depicted map. also changing levels does not immediately update the plot.
If we decide to proceed here, one might clear it only in case that "update when changed" is selected. But switching the server necessarily resets many buttons such that immediately retrieving an image with the default settings is usually not what is desired.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

the image is completly wrong on a new loaded wms server url. if update on changes is on, then this is confusing.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

this needs further analysis and a concept useable for a lot more views

**Comment by joernu76** [comment]
This issue has been solved en passant by the redesign of WMS UI for multi-layering support.
