### ISSUE TITLE
mscolab does not update created_at for Changes and Messages

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2241]
We define in the models for Message and Change a "created_at" and keep the initial creation time. 

This needs to become updated on each new entry.

We see this problem in the chat by the service messages.

![service_message](https://github.com/Open-MSS/MSS/assets/278728/4a1de178-30ac-4620-804e-98ab4642df14)

but we can't see it in the current tests (or we see it randomly), because for some reason it seems to order correctly. 

get_all_changes did a query

```
changes = Change.query.\
                filter_by(op_id=op_id)\
                .order_by(Change.created_at.desc())\
                .all()
```

A database entry for changes looks like. 

![indicating_the_problem](https://github.com/Open-MSS/MSS/assets/278728/7fe4c859-36de-4c21-9349-59def1c9453f)

**Comment by mahmoudnabil133** [comment]
I am trying to solve this bug.

**Comment by ReimarBauer** [comment]
@mahmoudnabil133 compare with my Pull Request. You can do afterwards the follow up. We have to compare with milliseconds. Then we have also test coverage for the needed change.

**Comment by ReimarBauer** [comment]
I add a new bug report, your change can then focus on this one.

@mahmoudnabil133 that is what you want to work on https://github.com/Open-MSS/MSS/issues/2245

Likly you have to comment there, seems I can't assign it.
