### ISSUE TITLE
changes query needs compare .created_at with the stored milliseconds

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2245]
After https://github.com/Open-MSS/MSS/issues/2241 is merged the query needs to become improved. This PR has the needed tests to check for a solution of the problem.

This compares currently only seconds. We need also the milliseconds which are in the database
```
changes = Change.query.\
                filter_by(op_id=op_id)\
                .order_by(Change.created_at.desc())\
                .all()
```
In the changed tests of the mentioned PR we need to remove the time.sleep(1) so that the change can be tested.

I am currently not sure if this can be done without an API change. When it needs an API change we can do this only in develop.
Because it is a bug we try for stable first.

**Comment by mahmoudnabil133** [comment]
ok, i will work on this bug.

**Comment by mahmoudnabil133** [comment]
> [ReimarBauer](/ReimarBauer)

ok i will work on this bug. so i could update my prevuis pr to cover tests.  enything else should i Take it into consideration.

**Comment by ReimarBauer** [comment]
@mahmoudnabil133 please wait for the merge.

**Comment by ReimarBauer** [comment]
Hi, I justed recognized that my change is not that correct, but the tests are good. So we wait for this PR 
https://github.com/Open-MSS/MSS/pull/2239 merged in develop, then the tests are available. 

I also enabled the testrunner on your privious PR so you can see if there are other changes needed.

**Comment by mahmoudnabil133** [comment]
OK , i am waiting

**Comment by mahmoudnabil133** [comment]
from the testrunner on my privious PR : it seems like my last pr failed becouse i forgot 2 parentheses of `utcnow()` so i can fix it after merging this pr https://github.com/Open-MSS/MSS/pull/2239

**Comment by kedar1251090306** [comment]
Interested for GSoC 2026 prep—working on a PR!
