### ISSUE TITLE
Out of Scope Variable in Exception Block in constants.py

### ISSUE THREAD

**Issue by workaryangupta** [Open-MSS/MSS#2274]
The variable `_fs` is out of scope in the except block as it was defined in the try block.
https://github.com/Open-MSS/MSS/blob/1d0a5ad604170f3a618c54b69b1ad949bba2ea91/mslib/msui/constants.py#L37-L43

**Comment by ReimarBauer** [comment]
it is likly
```
_fs = fs.open_fs(fs.path.dirname(MSUI_CONFIG_PATH))
_fs.makedirs(fs.path.basename(MSUI_CONFIG_PATH))
```
but that should also in an exception, when it can't succeed we should raise and tell the user

**Comment by Preetam-Das26** [comment]
I would like to work on this issue. @ReimarBauer

**Comment by ReimarBauer** [comment]
this needs to go to stable :)
