### ISSUE TITLE
define a range of a "green" coverage

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2302]
Hey, I want to reach at least 70 % by coverage again,

we maybe should adjust a bit that not only a few lines below this goal the coverage test shows the CI has a failure.

What would be a good value for https://coverage.readthedocs.io/en/7.4.4/config.html#report-fail-under

**Comment by matrss** [comment]
I don't think the setting you have referenced applies for coveralls, right? I.e. it is for coverage.py and would make the pytest run fail if coverage is below this value, but it would not affect what the status check from coveralls shows (which is green if coverage stayed the same or increased, and is red if coverage decreased, compared to a previous run), right?

I would prefer to stay with what coveralls already does, but fix our test suite to actually have a deterministic coverage (unlike what we have right now, where there is a handful of lines that may or may not be covered at random, for some reason).

**Comment by ReimarBauer** [comment]
oh, right, we moved from there. It only illustrates what a solution can be.

I dislike that it currently looks like the tests have failed but it is only less line covered. 

But at all for much new lines I think it's a good idea to remember that with a merge we end up there again.

**Comment by matrss** [comment]
The proper fix is to get the test suites coverage to be deterministic. Do you have any idea why it is not? I can only guess that it depends on what Qt has done already at the end of a test, so maybe a qWait at the end of every test would pave this over, _for now_. I would have to test that out.

**Comment by ReimarBauer** [comment]
@matrss I think we can close this, a follow up may also get a different description, as my initial one.
