### ISSUE TITLE
multipe flightpath docking widget on logout traceback

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2309]
when you have worked with the docking widget then closed topview and did logout.

click some operations, click a local flightpath, click again on a operation then logout

```
Fatal error in MSS 8.3.4 on Linux-6.5.0-10027-tuxedo-x86_64-with-glibc2.35
Python 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/MSS/mslib/msui/topview.py", line 365, in <lambda>
    self.mainwindow_signal_logout_mscolab.connect(lambda: self.signal_logout_mscolab.emit())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type MSUITopViewWindow has been deleted
```

![close_topview_then_logout](https://github.com/Open-MSS/MSS/assets/278728/ff3e81a6-73fd-4d6a-ba86-a7f8324154c7)

**Comment by ReimarBauer** [comment]
This happens not always or a component is missing now

**Comment by matrss** [comment]
The offending line emits the signal_logout_mscolab of the MSUITopViewWindow class whenever the signal_logout_mscolab of the main window is emitted, but there is no slot connected to that signal as far as I can tell. It also seems logically wrong that this signal on MSUITopViewWindow class exists at all. Can it just be removed?

**Comment by ReimarBauer** [comment]
That is currently needed there. 
It should logout the many operation connections in the dockingwidget when the main logout is triggered. 

Some time ago I added some ideas about the docking widgets in https://github.com/Open-MSS/MSS/issues/1108
