### ISSUE TITLE
Add lint rules to prevent CRLF and whitespace errors

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2330]
Do we want to introduce a linter for these kinds of things? We could setup a https://editorconfig.org/ configuration for the repository and use https://github.com/editorconfig-checker/editorconfig-checker to enforce it.

_Originally posted by @matrss in https://github.com/Open-MSS/MSS/issues/2328#issuecomment-2063820151_
            
With such a setup we could enforce unix-style linebreaks, linebreaks at EOF, and other stuff.

**Comment by matrss** [comment]
There are some inconsistencies regarding linebreak styles in the repository as shown in https://github.com/Open-MSS/MSS/pull/2328#issuecomment-2063986824.

**Comment by matrss** [comment]
The end_of_line setting of editorconfig might be problematic because it would enforce lf on windows as well. But git can deal with this by itself: with `* text=auto` in .gitattributes it will auto-detect text files and convert crlf to lf in the repository. For checkouts on windows systems one could then set core.autocrlf to get crlf endings in the working tree, while git would store everything with lf.

But I have no idea if this is the best approach or if there are some files that should always have crlf (.bat?) while some should always have lf? I wish this was standardised decades ago...

**Comment by ReimarBauer** [comment]
Also on windows we need to use linefeed for our repo. There should not get any `\r\n` into the codebase. 

The bat file is an interesting question.  I think Call and goto because of labels have a limitation.  But I am not sure if the labelparser has still that problem.

In the past I had also problems with numbers having crlf  without a blank by reading on linux.

**Comment by matrss** [comment]
It turned out that editorconfig is sub-optimal for this kind of thing because 1. its `end_of_line` setting would force lf even on windows, where actually we just want to force lf in the repository (git can create a worktree with crlf on windows, which is fine as long as the commited files have lf) and 2. its `insert_final_newline` option is interpreted by editorconfig-checker to mean "at least one newline", not exactly one newline.

Instead, a bit of scripting around git can do all the checking, which I have done in #2334.
