### ISSUE TITLE
allow non uniformly spaced grid data

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#235]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/235) by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

For aircraft campaigns, one wants on the one side highest possible
resolution of displayed model data on the other side a large area of
display to get the overall overview. One needs to find a compromise
such that the data set are not to big and the resolution is high
enough.  If would be of great help, if the data grid in the data files
 could be spaced in a non regular way, 
e.g. longitude 5, 10,15,...40, 42, 44, 46 ..50, 51, ...70,70.5,71... etc 
and similar for latitude.

These files could be produced at low numerical cost by the rdf
technique (or maybe later by a nested ICON model).  Of course one
could blow up these files by interpolating on a high resolution grid
everywhere, but this likely would make things slow.  If it could be
managed, that this interpolation is carried out just before plotting,
it may make thigs fast and benefiting.

This would be a great improvement of for flight planning isues.

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Seems like a good idea. I am not sure that this is not already supported, as long as the grid is rectilinear. Could you provide an example file for testing?

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@grooss please add an example

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@{557058:3f381f76-9ea4-4904-940c-ec968a1a0765} an example is requested since long. Is this still an issue?

**Comment by ReimarBauer** [comment]
**Original comment by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

yes it is an issue. It would save computing time for the RDF CLaMS forecast. I didn’t see this example request. It may work already but currently my focus is on the campaign. Try to have an example asap.

**Comment by joernu76** [comment]
I recently had a look again at the used interpolation.
Doing general regridding is a pretty complex and, potentially, computationally expensive task.
This should be better done as a preprocessing step.
