### ISSUE TITLE
migration script for mscolab timestamps

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2366]
we need a script to migrate the database < 9.0.0 to the isotimeformat

**Comment by ReimarBauer** [comment]
hmm, mscolab db --seed does not create examples where we have created_at used.

From the dir differences: We need to add a "datasso" dir.

**Comment by matrss** [comment]
There was no change to the database schema, so I don't understand what you think needs to be done.

What we did change was that all timestamps read from the database are interpreted as UTC, while previously we didn't ensure that we only wrote UTC to it. But AFAIK there is nothing we can do about it, since there is no way to know the timezone of what was previously written to the database.

**Comment by matrss** [comment]
> since there is no way to know the timezone of what was previously written to the database.

OK, well, we could assume the local timezone of the server for that.

**Comment by ReimarBauer** [comment]
ok, great then it is only that dir. Which is currently also created when  we don't have SAML enabled.

**Comment by matrss** [comment]
> What we did change was that all timestamps read from the database are interpreted as UTC, while previously we didn't ensure that we only wrote UTC to it.

Messages and Changes had a default created_at value of `datetime.datetime.utcnow()`, so they were written as UTC and need no migration. An Operations last_used field was also set to utcnow in all the places I can find, so should not need a migration either.

A Users registered_on and confirmed_on fields used `datetime.datetime.now()` though, so they were created in the servers local timezone. AFAICT this means that they were also written to the database as timestamps in their local timezone (but without timezone information). This means that without a migration those two fields, for existing users, will be off by the servers local timezones offset to UTC.

But honestly, I am not sure if it is worth the effort to make this mostly irrelevant information be accurate or if it is fine if it is off by up to 14h for existing users.

**Comment by ReimarBauer** [comment]
you are right.
