### ISSUE TITLE
Tutorial videos on readthedocs are too wide

### ISSUE THREAD

**Issue by matrss** [Open-MSS/MSS#2462]
See for example:

![Screenshot from 2024-08-15 13-55-43](https://github.com/user-attachments/assets/aaf8346e-0f66-4a17-b8d9-c0f71fece381)

and:

![IMG_20240815_135658](https://github.com/user-attachments/assets/a8faf4a1-e623-4ac9-bafb-49d63a1c6d06)

I think the videos should not exceed the width of the browser window itself, at all times. If they are too small one can always make them full-screen as needed.

**Comment by ReimarBauer** [comment]
The videos should behave identical to the image in about.

**Comment by matrss** [comment]
That image has `max-width: 100%` set, but it is already not that wide, so it is below 100%. Do you want the videos to be similar in width to that image, or limited to 100% at most like that image?

**Comment by ReimarBauer** [comment]
The image has a size 1200x900 and it is scaled by the theme. 
You see its original size by opening it in its own tab.


![Screenshot_20240815_154026_Chrome.jpg](https://github.com/user-attachments/assets/7193d4ab-7398-4b73-8dfc-7408915a5daa)

We need to find the class Attribute and look if this works with the videos too or define some own css.

**Comment by matrss** [comment]
Yes, my question was if you want videos exactly as wide as that image, i.e. `max(1200px, 100% width)`, or just have videos be limited by the enclosing blocks width as well, like that image.

For reference, this is how that image looks on my desktop:

![Screenshot from 2024-08-15 16-09-35](https://github.com/user-attachments/assets/4d67b9db-5742-4736-9ae5-fc0f59eda64c)

It is less than 100% width, because the images own width is smaller.

The CSS to do this for videos as well is trivial.

**Comment by ReimarBauer** [comment]
> Yes, my question was if you want videos exactly as wide as that image, i.e. `max(1200px, 100% width)`, or just have videos be limited by the enclosing blocks width as well, like that image.
> 
> For reference, this is how that image looks on my desktop:
> 
> ![Screenshot from 2024-08-15 16-09-35](https://github.com/user-attachments/assets/4d67b9db-5742-4736-9ae5-fc0f59eda64c)
> 
> It is less than 100% width, because the images own width is smaller.
> 
> The CSS to do this for videos as well is trivial.


The only thing I want is that it behaves responsive. It must work on any resolution of the browser.
