### ISSUE TITLE
import failure in mslib.msui.qt5.ui_webbrowser

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2503]
```
from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/home/reimarb/Miniforge/envs/mssdev/lib/python3.11/site-packages/PyQt5/__init__.py)
```

```
mamba list pyqt
# packages in environment at /home/reimarb/Miniforge/envs/mssdev:
#
# Name                    Version                   Build  Channel
pyqt                      5.15.9          py311hf0fb5b6_5    conda-forge
pyqt5-sip                 12.12.2         py311hb755f60_5    conda-forge
pyqtgraph                 0.13.4             pyhd8ed1ab_0    conda-forge
```

rebuilding from ui_webbrowser.ui still has the line
`self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.centralwidget)`

and it is not imported

`from PyQt5 import QtCore, QtGui, QtWidgets`

QtWebKit was deprecated in Qt 5.5

**Comment by matrss** [comment]
Cross-linking #2293: the web browser code path is dead code (it is an example of such in that issue); as it is unused and there is no plan to start using it in the future I think it can just be removed.
