### ISSUE TITLE
AttributeError: module 'alembic.context' has no attribute 'config'. Did you mean: 'configure'?

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2504]
I get as warning

```
  warn(str(ex), Module.ImportWarning)
/home/reimarb/Miniforge/envs/mssdev/lib/python3.11/site-packages/pdoc/__init__.py:774: ImportWarning: Error importing 'mslib.mscolab.migrations.env': AttributeError: module 'alembic.context' has no attribute 'config'
```

and I can reproduce that by

```
from alembic import context
config = context.config
```
AttributeError: module 'alembic.context' has no attribute 'config'. Did you mean: 'configure'?

@matrss Do you have time to look on this?

**Comment by matrss** [comment]
`flask db init` still generates an env.py file that accesses `alembic.context.config`. Migrations work fine, so I can only assume that Flask-Migrate, or rather alembic, do some setup work before invoking env.py. This file is not meant to be imported standalone, it is used by the `alembic` CLI tool or the `flask db` commands from Flask-Migrate.
