### ISSUE TITLE
MSS should remember the last style chosen for a layer

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#251]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/251) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@{joernu76} have we this in qsettings meanwhile saved?

**Comment by Marilyth** [comment]
This needs clarification @ReimarBauer @joernu76 

Do you mean MSS should remember the last style chosen persistently?
E.g. When I choose Style B for a Layer, and restart MSS, Style B should still be chosen?

Do you mean the style chosen should also be applied to other layers?
E.g. When I choose Style B for Layer A, and switch to Layer B, it also has Style B chosen?

Do you mean the style chosen for a Layer should not change when switching?
E.g. When I choose Style B for Layer A, switch to Layer B, switch to Layer A, Style B is still chosen?

**Comment by joernu76** [comment]
I think we have (3) already with the new interface (and maybe before...). I think I mostly refer to (1).

Imagine: We have two styles, one for northern hemisphere (default) and one for southern hemisphere (where the campaign is located). It would be nice, if MSS would remember my choice of the southern hemisphere style across application restarts.

But only if this does not complicate the code too much.

I think (2) is out-of-scope.
