### ISSUE TITLE
Flightlevels in Sideview potentially inconsistent

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#252]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/252) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

If multiple Sideviews are open, the flightlevels become inconsistent if they are changed in one plot.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

If multiple Sideviews are open, the flightlevels become inconsitent if they are changed in one plot.

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

If multiple Sideviews are open, the flightlevels become inconsitent if they are changed in one plot.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

If multiple Sideviews are open, the flightlevels become inconsistent if they are changed in one plot.

**Comment by Marilyth** [comment]
Is there an easy way to reproduce this issue? Everything seems fine on my end.

**Comment by ReimarBauer** [comment]
Can't reproduce too. Just seen that we have different states of functions activated in multiple windows. E.g. one has + waypoints the other - waypoints.
@joernu76 have you more details?

**Comment by joernu76** [comment]
Issue seems fixed.
