### ISSUE TITLE
develop: UI problem with resizing the main UI logged in 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2526]
There is a problem with the UI scaling at the moment an operation gets activated

![image](https://github.com/user-attachments/assets/deeac3b3-3390-4421-b475-12d55ee1634a)

**Comment by divyaajainn** [comment]
Hi. I would like to work on this issue. Could you please assign this to me?

**Comment by ReimarBauer** [comment]
Welcome @idkdivyaig you have it.
