### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#2581]
dependency change
```
./../../micromamba/envs/ci/lib/python3.11/site-packages/OpenSSL/__init__.py:8: in <module>
    from OpenSSL import crypto, SSL
../../../micromamba/envs/ci/lib/python3.11/site-packages/OpenSSL/crypto.py:1579: in <module>
    class X509StoreFlags(object):
../../../micromamba/envs/ci/lib/python3.11/site-packages/OpenSSL/crypto.py:1598: in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY
E   AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by matrss** [comment]
Looks like this issue: <https://github.com/conda/conda/issues/13619#issuecomment-2075825121>. And again a case of "install-time dependency resolution makes testing released packages impossible"...

**Comment by ReimarBauer** [comment]
and again a dev on #gsoc found it first.

**Comment by ReimarBauer** [comment]
> Looks like this issue: [conda/conda#13619 (comment)](https://github.com/conda/conda/issues/13619#issuecomment-2075825121). And again a case of "install-time dependency resolution makes testing released packages impossible"...

I'd seen that closed issue too, but that is rather old. 4 days ago (feels like yesterday) the PR didn't found it.

**Comment by ReimarBauer** [comment]
That change could match, trying.  
https://anaconda.org/conda-forge/cryptography

**Comment by ReimarBauer** [comment]
cryptograhy 43.0.3  worked

https://github.com/Open-MSS/MSS/actions/runs/12049683203/job/33596942683?pr=2577#step:5:675

**Comment by ReimarBauer** [comment]
https://github.com/conda-forge/openssl-feedstock/issues/181

**Comment by ReimarBauer** [comment]
This will solve the problem. Again such things can only resolved by a community approach.

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/913

**Comment by ReimarBauer** [comment]
https://conda-forge.zulipchat.com/#narrow/channel/457337-general/topic/problem.20with.20openssl.20after.20cryptography.2044.2E0.2E0.20was.20released

**Comment by ReimarBauer** [comment]
Was upstream fixed
