### ISSUE TITLE
evolving/changing demodata for testing

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#263]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/263) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We need demo data evolving over some time period.

That means while the server is running demodata should add more files. This simulates the real situation, where other processes increases the amout of data the server has to handle

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

a different approach is to reduce demodata during tests

**Comment by joernu76** [comment]
Resolved.
