### ISSUE TITLE
faster timeout for configured but not reachable servers

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#279]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/279) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

If a server is behind a firewall and we don't have access, we should get that pretty fast.

Currently a getcapabilities request needs to run into a timeout to stop this request.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

needs to become verified after 1.7.0 release

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

all wms urls from configurations can be checked if they exists. The user interface should only show which can be used. Missing urls should become logged.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I think it is better to have a mss\_pyui command line option to check defined urls. We should cleanup from the beginning urls which can’t be accessed.

**Comment by ReimarBauer** [comment]
We could verify availability of the host. 
```
_s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        _s.bind(("IP", port))
    except (socket.error, IOError):
       -> mark not available

```

**Comment by Marilyth** [comment]
@ReimarBauer 
I am very confused here. What are we trying to find out? Why would binding a port solve anything?

So we have preconfigured servers, they may or may not be "available", and we want to know that before [get capabilities] is pressed?
Do we just want to automatically "press the button" before the user gets to, to make sure every server is replying correctly?

**Comment by ReimarBauer** [comment]
You are right, that is not so simple as it looks like. 

a) user has an old server which does not provide data but seems alive this won't be recognized before a request.
b) also we can have the situation the valid server is just in an maintainance state.

We can not autmoate this. Therefore I close it.
