### ISSUE TITLE
`add_data` should be optional

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#289]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/289) by Andreas Hilboll (Bitbucket: [andreas-h](https://bitbucket.org/andreas-h), GitHub: [andreas-h](https://github.com/andreas-h)).**

----------------------------------------

Currently, it is not possible to have optional `add_data`.

Use case:  In the `VS_MSSChemStyle_AL_*` plotting classes, there is currently no `add_data` set.  In case of no `air_pressure` being pressent, I calculate static air pressure.

However, there are some AL models which provide air_pressure as 4D fields. In these cases it would be good to have *optional*  `add_data`. 

As discussed on Slack with @joernu76

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Currently, it is not possible to have optional `add_data`.

Use case:  In the `VS_MSSChemStyle_AL_*` plotting classes, there is currently no `add_data` set.  In case of no `air_pressure` being pressent, I calculate static air pressure.

However, there are some AL models which provide air_pressure as 4D fields. In these cases it would be good to have *optional*  `add_data`. 

As discussed on Slack with @joernu76

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@{joernu76}  how is the state of this, move it to 1.10.0 ?

**Comment by joernu76** [comment]
Can be solved by providing proper user-defined plotting classes. See WMS generic plotting routine.
