### ISSUE TITLE
use server information on client site

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#295]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/295) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

The capabilities data document should be printable. There is currently a lot information which belongs to each printout.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

This can be done by pyperclip, see Configuration Loader

**Comment by joernu76** [comment]
Showing the information is sufficient.
