### ISSUE TITLE
WMS capability document of our extended getVSec

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#349]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/349) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

The XML document offered by the WMS Server does not contain the capability of our extended getVSec. This could be easily be added in the <Capability> <Request> section.
This might contradoct the spec, though.

In addition (or in spite of above) we should add a couple of features to determine whether we can offer them to a WMS server as "VendorSpecificCapabilities", such as our stereographic projections and stuff.

**Comment by joernu76** [comment]
The extensions have been published by M. Rautenhaus.
