### ISSUE TITLE
time dimension/time extent field with ranges and or periods not fully supported

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#353]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/353) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Some servers declare their supported times with a complicated, but documented format, where they define starting/ending times with periods in the middle.
E.g.
1999-01-01/2000-08-22/P1D
Currently, these things are not fully supported, especially if a period is specified in addition.

Ideally, the field is parsed and entered into the valid times field.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@joernu76 can we move this to 1.9.0 ?

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

Fine for me.

**Comment by joernu76** [comment]
Has been solved already. See
test_xml_time_init_period in mslib/msui/_tests/test_wms_control.py
