### ISSUE TITLE
Check on WMS compliance against official test suite

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#357]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/357) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

See 
https://github.com/opengeospatial/ets-wms11

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

See 
https://github.com/opengeospatial/ets-wms11

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

hmm, the project has an open pull request for some month

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

I doubt that this issue can be completed before the 1.8.0 release, even under ideal circumstances.

I propose to shift this to the next release cycle.

**Comment by ReimarBauer** [comment]
**Original comment by Shivashis Padhi (Bitbucket: [plant99](https://bitbucket.org/plant99), GitHub: [plant99](https://github.com/plant99)).**

----------------------------------------

I am actually very close to do the testing. I believe I can complete it by tonight. But it will just be generating new compliance issues. What do you say @joernu76 ?

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

See 
https://github.com/opengeospatial/ets-wms11

**Comment by Marilyth** [comment]
For reference, an easy way to test a WMS server is as follows:
1. `docker run --network host --rm ogccite/ets-wms13`
2. Visit http://localhost:8080/teamengine/viewSessions.jsp in your browser
3. Log in with user and password `ogctest`
4. Set up and run the tests

**Comment by Marilyth** [comment]
I tried to make things as WMS compliant as possible back when I was working on the 1.3.0 standard, in a short period of time.

As things are now, MSS is not and probably will not be 100% WMS compliant. The main reasons why:
1. The way vertical layer requests are handled is straight up not possible to be compliant so there is no way to fix this.
2. When testing multiple layers, the test suite sends requests for mixed vertical and horizontal layers, again failing.
