### ISSUE TITLE
output to vectorized formats, e.g. pdf sometimes don't show the flightpath line

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#361]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/361) by Isabell Krisch (Bitbucket: [isabell_krisch](https://bitbucket.org/isabell_krisch), ).**

----------------------------------------

When saving a topview to a pdf file, the flightpath vanishes. Saving the same topview to png keeps the flightpath.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@isabell_krisch can you provide the flightpath?

with the builtin server / data I can't reproduce this

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Got the flightpath bei PM, but can't reproduce this. Can you still reproduce this?

**Comment by ReimarBauer** [comment]
**Original comment by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

I cannot reproduce the problem either. @isabell_krisch , can you provide a more accurate description for reproducing the error? If I immediately save the Topview after starting the program, the PNG and PDF both are identical and show the flight pathg.

**Comment by ReimarBauer** [comment]
**Original comment by Isabell Krisch (Bitbucket: [isabell_krisch](https://bitbucket.org/isabell_krisch), ).**

----------------------------------------

@ReimarBauer @joernu76: Flight path only vanishes when saving with atmospheric data (for example cloud cover). The error is reproducible both with Python 3.6.6 and Python 2.7.14 and both times mss 1.7.3. I further tried different Webmap Services (including internal ones and EUMETSAT) and the problem is persistent.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@isabell_krisch I used https://eumetview.eumetsat.int/geoserver/wms and tried with msg_fog | meteosat:msg_fog

in a completly fresh miniconda3 and only netcdf4 is downgraded to 1.4.0

I guess I understand now what you have found! [issue_pdf_output.png](https://bitbucket.org/repo/MBp6Xa/images/434849891-issue_pdf_output.png)

The connecting line between the points is not printed.

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

All vectorized formats have the same issue

* svg
* eps, ps
* pdf

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

The issue is related to  the matplotlib.backends.backend_pdf.FigureCanvasPdf 

From the ToDo there


```
#!text

# TODOs:
#
# * encoding of fonts, including mathtext fonts and unicode support
# * TTF support has lots of small TODOs, e.g., how do you know if a font
#   is serif/sans-serif, or symbolic/non-symbolic?
# * draw_markers, draw_line_collection, etc.

```

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

looks like one solution may be we have to refactor self.line = self.ax.plot to become self.line = self.ax.scatter

scatter elements are visible in pdf too



https://bitbucket.org/wxmetvis/mss/src/3e8aaf3f55ea00e01c03210c07f032cbebd87066/mslib/msui/mpl_pathinteractor.py?at=stable&fileviewer=file-view-default#mpl_pathinteractor.py-395

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

Because of API change we have to solve this in 1.8

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

this needs upstream an improvement

**Comment by joernu76** [comment]
Currently, it looks like the flightpath has vanished in PNG, whereas the PDF shows it, but is missing the WMS layer...?

**Comment by joernu76** [comment]
Seems resolved.
