### ISSUE TITLE
quality check for input data

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#424]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/424) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We need a check routine which verifies data provided to a server setup that setup matches to data.

**Comment by joernu76** [comment]
There are a lot of checks in the current DataAccess class, which gives pretty good info on what has been identified and what isn't standard-conformant.
