### ISSUE TITLE
Support plots combining multiple horizontal layers in one plot

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#429]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/429) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

E.g. combine geopotential at 500hPa with Potential temperature at 850hPa.

One could realise this by creating surface fields of the different quantities, but this requires additional storage and effort in preparing te data.

**Comment by Marilyth** [comment]
While easily possible with my multilayering PR, it was discussed that this feature does not have many use cases and makes the application too difficult to handle.
If however this is still wanted later on, it will be an easy implement.
