### ISSUE TITLE
mscolab circles / more user managment

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#452]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/452) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

In mscolab we introduce user and shared project work. We need a way to enter a lot users to a project and also to manage the kind of colaboration.

I like the circle nextcloud model, may be we can use that similiar.

To be observed:

‌

* individual added user which is also in a circle is priviledged for the role.
* global on server side an admin can enable the Circle ALLV\(iewer\)/ALLC\(olaborator\), which adds all existing users with that role to the circle. 
* other global definitions on server side optional.
* A user can use global circles or define some on his namespace
* Any user should be able to add users to a circle in his namespace
* A circle can be set to a default role, e.g. a circle for viewer only user
* Adding a circle to a project will be add all members internally like individual added users.
* Adding more circles with same users, maximal role of a user is used
* The UI should give a overview of users and roles of all having access to the project.  A change role may create a individual added user with defined role  

Is there more to think about ?

**Comment by ReimarBauer** [comment]
**Original comment by Shivashis Padhi (Bitbucket: [plant99](https://bitbucket.org/plant99), GitHub: [plant99](https://github.com/plant99)).**

----------------------------------------

From one read, I’d say its doable. I'll comment more on 6th September.

**Comment by ReimarBauer** [comment]
**Original comment by Shivashis Padhi (Bitbucket: [plant99](https://bitbucket.org/plant99), GitHub: [plant99](https://github.com/plant99)).**

----------------------------------------

The script can be made a module in the next release.

**Comment by Tanish0019** [comment]
@ReimarBauer This is defining the admin window. This issue can be closed now I think
