### ISSUE TITLE
Failed import of files with missing columns

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#459]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/459) by Markus Geldenhuys (Bitbucket: [Markus Geldenhuys](https://bitbucket.org/Markus Geldenhuys), ).**

----------------------------------------

If one try to import a text \(FlightStar file\) with a missing column or coordinate MSS does not allow this. A quickfix by yourself is to identify the location and put some ‘junk’ data in there. However it would be nice to have MSS not sensitive to this…

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I am rather unsure if we are able to handle this automaticly whithout human interaction.   
  
Is there a linting or analyzer for those files available, or can that be easily written?

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

This needs a detailed review

**Comment by joernu76** [comment]
I think linting arbitrary formats is out-of-scope and should be the task of the tool we use for that.
The "FliteStar" Format is not an actual format, but we try to parse the "human readable output" of a  commercial tool, which was never thought to be used for this context.
