### ISSUE TITLE
mark and remove URLs from history

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#480]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/480) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

The URL fields have a drop down list of possible URLs to be filled from both the configuration file and possibly history of used URLs comparable to the WMS control. This is an important feature as it simplifies the preconfiguration of MSS for campaign users using the JSON file.

‌

Possibly multiple URLS should be retained in recent history, if a mechanism could be implemented to mark and remove those URLs again.

‌

‌

‌

**Comment by Tanish0019** [comment]
@ReimarBauer Currently your recent URLs are saved in the input box. But there is no option to remove. Maybe we can keep top 5 recently used urls or something similar?

**Comment by ReimarBauer** [comment]
@Tanish0019 yes that's fine

**Comment by ReimarBauer** [comment]
This needs a review if it is with the mentioned PR solved
