### ISSUE TITLE
Simplify MSCO server and user setup for simple use cases

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#488]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/488) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

For using the msco server on a single campaign, it is desirable to, by default, give all registered users access to all projects. This might be restricted to view access.

**Comment by ReimarBauer** [comment]
**Original comment by Tanish Grover (Bitbucket: [tanish19](https://bitbucket.org/tanish19), GitHub: [tanish19](https://github.com/tanish19)).**

----------------------------------------

@{557058:fabca9ad-f8cf-4f48-b9aa-8ab5c2f5d433} How about adding a checkbox in the new project dialog which gives project access to everyone?

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

@{joernu76} this is by the admin dashboard with two clicks done. 

* select all user, give rights
* use one project as template for rights for the next project

I think basics are available and we can close this one?

‌

‌

‌

**Comment by ReimarBauer** [comment]
**Original comment by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

This is likly already implemented in a different way. We could setup  users. We could create a template project and inherite by this users and also rights.

We should do have the option on creating a new project to inherite from a template \(other project, defaults, …\)

**Comment by ReimarBauer** [comment]
We are able to use any of our projects as template. In current campaign we have a TEMPLATE project with configured users and do inherite from this.

We may be should think about the additional option on creating a project to select another project to inherite users.

on server site are cli scripts which can be used to add any created user to the TEMPLATE or to any other project with a defined role. It is also possible to initialize a database with users.

on the server code we may think about hooks, or policies to become configured as extension

**Comment by joernu76** [comment]
Two options IMHO:
1) We probably need to add support for "groups" to allow this in a simple fashion. 
2) Or allow the total removal of the permission model. I.e. every new user may do everything.

Wither way we need to support a usage model that does not require a semi-fulltime admin for rights management in a campaign with 1-3 new users per day and a large number of projects (i.e. ~ 100).
