### ISSUE TITLE
save/export/checkout terminology unclean in mscolab

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#496]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/496) by Joern Ungermann (Bitbucket: [joernu76](https://bitbucket.org/joernu76), GitHub: [joernu76](https://github.com/joernu76)).**

----------------------------------------

The notion of save/export/fetch is not consistently used. I propose the following terms:

* push - “save” to server
* auto check in - automatically check in every change.
* pull - “load” from server
* revert - “checkout” to elder, selected revision
* undo - “checkout” of last revision
* save - “save” ftml to disk
* export - “save” to disk on other formats
* load - “load” ftml from disk
* import - “load” from disk in other formats

‌

save/export could be merged, if someone can implement that cleanly for our plugins.

‌

**Comment by Tanish0019** [comment]
@ReimarBauer These terminologies have been changed. I think we can close this issue?

**Comment by ReimarBauer** [comment]
great :)
