### ISSUE TITLE
Simplification of performance setup

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#511]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/511) by Jens-Uwe Grooß (Bitbucket: [grooss](https://bitbucket.org/grooss), GitHub: [grooss](https://github.com/grooss)).**

----------------------------------------

Currently the performance is calculated from two given numbers provided in the "performance menu" on the table view tab.  
\(1\) The total start mass including fuel  
\(2\) the mass of fuel at start.

One can check, if a flight may be too long, if "remaining fuel" runs into negative numbers". As long as flights have always the same length one does not need to change these numbers, however, for a shorter flight one needs to alter both numbers consistenly.

I propose to change this into the parameters 

mass of empty aircraft \(including fuel safety reserve\)  
and  
maximum possible fuel

Then the "remaining fuel" could be displayed such that it always ends with zero and with variable initial fuel to be calculated. If initial fuel mass would exceed maximum possible fuel mass, this could be indicated e.g. by changing the color in the  "remaining fuel" column to zero.

With this, it is not necessary to alter these numbers given a fixed aircraft with the same setup \(payload\).

\(Version 1.9.0\)

**Comment by joernu76** [comment]
Seems reasonable and probably simple...?

**Comment by joernu76** [comment]
Partially adressed so far.

**Comment by ReimarBauer** [comment]
needs currently no further improvements
