### ISSUE TITLE
Allow Ascent rate to be modifiable in the Table View

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#544]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/544) by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

A helpful feature would be to allow the ‘Ascent Rate’ column to be modifiable when it is not '0', the way that the Lat/Lon/Flightlevel/Pressure fields can be modified.  For example, I would like my ascent and descent rates to always be 1500 ft/min, but adjusting the individual points to match the desired Ascent Rate takes a lot of time.  For example, if I have a flight plan consisting of ten input locations on my Table, adjusting the Ascent rate at location 2 for example, would pull the following location 3 point towards or away from point 2, depending on if the Ascent Rate is positive or negative.  This would make the flight plans more realistic.

**Comment by joernu76** [comment]
Moving a waypoint is only easily feasible in case the two points and the succeeding one are on a line.
In case the distance is longer than required one could add a new point instead. 
Also, people might think that adjusting the ascent rate would modify the flight altitude of the succeeding point...

I think that adding/moving way points is not an obvious behaviour here, even though it would be a useful one. We typically solved this issue with comments indicating the desired ascent rate and less waypoints. The flight plan is not fully realistic in any case and needs to be discussed with pilots (e.g. U turns require rather large circles typically and can be flown in a variety of fashions.)

Maybe one could implement the desired feature with a docking toolkit and more elaborate waypoint setting features? It certainly requires an undo feature as will be provided by better MSCOLAB integration.

**Comment by joernu76** [comment]
too complicated.
