### ISSUE TITLE
Allow Vertical Plots to have Secondary Y-Axis

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#571]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/571) by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

It would be useful to have in the Side View Options menu, an option to add a secondary y-axis on the right side of the plot.  For example, if the menu is set to have ‘flight level’ as the primary y-axis value,  the secondary y-axis could be pressure or pressure altitude.

**Comment by Jatin2020-24** [comment]
Please assign me this issue.
