### ISSUE TITLE
Plot x-axis, y-axis, title, and color bar label sizes should be configurable.

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#573]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/573) by Shawn Honomichl (Bitbucket: [Shawn](https://bitbucket.org/Shawn), GitHub: [Shawn](https://github.com/Shawn)).**

----------------------------------------

Plot x-axis, y-axis, title, and color bar label sizes should be configurable in the options.  During briefings when flight plan images are displayed, people often complain of having trouble seeing labels.

**Comment by risehr** [comment]
Hello @ReimarBauer I am a bit unclear about this issue although I pondered over it for quite sometime.

Is that the whole map with latitudes and longitudes that are already there need to be framed inside x and y axes or the waypoints colour and connecting flight path color needs to be configured? Please, make it a bit more clear.
![image](https://user-images.githubusercontent.com/54763705/118949650-146f0900-b977-11eb-9abe-0fb3979a2033.png)

**Comment by risehr** [comment]
![image](https://user-images.githubusercontent.com/54763705/118950001-6adc4780-b977-11eb-9dea-a463bcfe0c5d.png)
or just the labels shown inside the circle that need to be configured?

**Comment by ReimarBauer** [comment]
start with Plot x-axis, y-axis 

these are added by the client, see mpl_qtwidget. 

this PR can be taken as example how to add to the options menu and how axis are drawn

https://github.com/Open-MSS/MSS/pull/980/files

Also in that PR you can see the problem. Different users have different readable results. So an  individual adjustment does help.

**Comment by risehr** [comment]
I have read the PR#980 carefully. What I understood from this issue is that in the Sideview options menu, you want me to have the option of showing and hiding the x axis and y axis(both primary and secondary) as desirable. Am I right? This is necessary to have a clear display of the flightpath. Moreover, the sizes of the color label should be configurable(We can increase or decrease their sizes so as to have a clear visibility). Right?

Please confirm if I understood the issue clearly or not. @ReimarBauer

**Comment by ReimarBauer** [comment]
not ;)


the PR is an example to show where and how options can be added. Also where the code lives for this issue.

This issue is about to be able to change the font size for the labels of the x-axis, y-axis and the title. 
The values to alter the font size have to be entered in the options menu.

**Comment by risehr** [comment]
Thanks a lot for the clarification. Now that I have understood, I am looking onto it.
