### ISSUE TITLE
refactor  mss_qt move module imports to modules

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#575]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/575) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

We introdruced mss\_qt because of a short time we had pyqt4 and pyqt5 together.

The module import should become moved back where they are used, so that we as developer get our IDEs to use all help of autocompletion or documentation.

[https://bitbucket.org/wxmetvis/mss/src/develop/mslib/msui/mss\_qt.py#lines-138](https://bitbucket.org/wxmetvis/mss/src/develop/mslib/msui/mss_qt.py#lines-138)

**Comment by joernu76** [comment]
The current module has this line `from PyQt5 import QtGui, QtCore, QtWidgets, QtTest, Qt  # noqa`, which bundles the import of core QT modules. All other modules should not use the modules imported here, but directly import from PyQt5.
