### ISSUE TITLE
rename get_project get_project_by_id

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#586]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/586) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

we may be can have get\_projects return only one project, so we can remove the second get\_project

**Comment by Tanish0019** [comment]
@ReimarBauer `get_project` is a find by id endpoint and `get_projects` is a get all endpoint. I don't think we need to merge the two?

**Comment by ReimarBauer** [comment]
not neccesarily

I thought about, when we give no p_id to get_project if it then can return the whole list.

But looking on it now, we can't tell "False" in that case.

I think we should rename one e.g. get_project_by_id

**Comment by aravindm711** [comment]
should the api endpoint and all its references be changed to 'get_project_by_id' or just the method involved? @ReimarBauer

**Comment by ReimarBauer** [comment]
Yes, that's is better readable.
