### ISSUE TITLE
server.update should be able to send a new revision

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#587]
**[Original report](https://bitbucket.org/wxmetvis/mss/issue/587) by Reimar Bauer (Bitbucket: [ReimarBauer](https://bitbucket.org/ReimarBauer), GitHub: [ReimarBauer](https://github.com/ReimarBauer)).**

----------------------------------------

I’ve seen how I can rename a flight path. Can this be used to send a different ftml content file?

If not I would like to have this also for using in tests.

**Comment by joernu76** [comment]
I do not understand this issue.

**Comment by ReimarBauer** [comment]
this is a simplifaction for testing
