### ISSUE TITLE
setup a containerd package 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#600]
in addition to the docker approach we have to add a setup for containerd

https://containerd.io/

https://containerd.io/docs/getting-started/

**Comment by plant99** [comment]
I wish to take this up, please assign this to me if you're not working on this.

**Comment by plant99** [comment]
@ReimarBauer I was looking at this a week back, and I believe containerd is a spec/library used to work on pre-built images, it doesn't let us build an [OCI](https://opencontainers.org/) image per-se. Please correct me if I'm wrong.

**Comment by plant99** [comment]
Regarding #619 , I feel we should stick to docker containers.

There would be more abundant documentation on CI/CD of Docker images from GitHub actions.
