### ISSUE TITLE
improve landing page

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#607]
e.g.

- fix typos
- add images

**Comment by ReimarBauer** [comment]
We should add some of the images like this one
https://remus.jpl.nasa.gov/kiruna/a020.htm

**Comment by ReimarBauer** [comment]
the mobile version needs a fix has no navigation and no logo currently

**Comment by ReimarBauer** [comment]
we need a way to use the github pages and additional use an imprint on the site

**Comment by SagarBapodara** [comment]
Hey @ReimarBauer, I would like to work on this issue, but could you please describe it more in detail about the issue? It would be great if you could add the link also.

**Comment by ReimarBauer** [comment]
At the moment you have started mscolab or the wms service it does provide a simple web site. The development server mswms.py does on  http://127.0.0.1:8081/ mscolab development server on http://127.0.0.1:8083
see [Setup Instructions](https://open-mss.github.io/develop/Setup-Instructions)

The content of the pages is located in the repository https://github.com/Open-MSS/MSS/tree/develop/mslib/static

On mobile the web sites look different.

**Comment by SagarBapodara** [comment]
Yes, well these are static pages with content, & I do not think there is any dynamic functionality attached, can't we combine everything into 2 files only, one for content & the other for styling? We can use HTML, CSS, Bootstrap & JS for that. Doing this, in my opinion, would allow us to have better functionality as well as better formatting of the content as well :). Would like to know your thoughts on this @ReimarBauer

**Comment by SagarBapodara** [comment]
Yes, on mobile navigation & logo is does not show up. But what I get is that these are standalone pages, or are these pages serving any dynamic content from the backend? as I could not find any.

**Comment by ReimarBauer** [comment]
We have all dynamic content access by the QT gui. The web page itselfs is very static. Currently it gives a brief information about the service MSS. If someone wants an other styling or different templates that can currently only done by mocking.

Our usecase to access this data for planning scientific flight pathes is to be able to do this in an environment where we have a very low internet bandwidth. I can't judge if something similar is feasible with current js frameworks.

**Comment by ReimarBauer** [comment]
partly addressed in https://github.com/Open-MSS/MSS/pull/752
