### ISSUE TITLE
snap to coordinates

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#611]
I'm thinking about an option to have inactive waypoints from other plannings on a map and that you are limited to only use these coordinates for a new plan.

They are shown as markers on the map too. if you get close to a marker this gives a signal and you can drop your waypoint on that.

**Comment by joernu76** [comment]
We are magnetic to "locations" already. Making those "inactive waypoints" into locations would fulfill that.
We typically add important (named) points to the settings. could be automated, obviously.
Accepting only those would be not so good, I guess.

**Comment by joernu76** [comment]
Collecting past waypoints might be a smart idea. Certainly accessing all known radio beacon and similar waypoints in a data base might be useful (especially for adding proper waypoint names.
However, retaining a history from past plannings adds a "state" to the software which is different between users, requires a management interface for the removal of, e.g., waypoints with typos and adds a  lot of complexity for testing.

Any database would need to be local and from past experience those things are pretty expensive and often protected.

**Comment by joernu76** [comment]
Differrently implemented.
