### ISSUE TITLE
in development documentation replace pep8 by flake8

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#615]
We still describe the pep8 module in https://mss.readthedocs.io/en/stable/development.html
This should be changed to flake8  e.g. `pytest --flake8`

or pycodestyle

`pycodestyle --show-source --show-pep8  mslib`

**Comment by iamansoni** [comment]
I would like to work on this task. You can assign it to me.

**Comment by ReimarBauer** [comment]
sorry for my late answer, I do now more often lookup all requests of me.
