### ISSUE TITLE
test_mscolab.py fails seemingly on random

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#624]
During creation of the testing actions, I ran into the issue that test_mscolab.py failed twice, out of many attempts.
The tests were done by just rerunning the job, so nothing changed in the source code or anything, and the result should in theory not change.

The line that fails is this one: https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/_tests/test_mscolab.py#L172
Currently I am not able to reproduce this at will.

**Comment by ReimarBauer** [comment]
We can reopen it, when we have more details

**Comment by ReimarBauer** [comment]
Sometimes also in our test framework this fails and vanishes on a rerun.

**Comment by Marilyth** [comment]
As this seems to be happening for some other tests as well, I will keep a list of all I find.
Another, more rare occurrence is test_get_message. Which last happened on the docker images on March 3rd.
https://github.com/Open-MSS/dockerhub/runs/2023839225?check_suite_focus=true
https://github.com/Open-MSS/MSS/blob/09b1fd1e665037048afaa991d0f83d1a38d5be88/mslib/mscolab/_tests/test_chat.py#L143

**Comment by Marilyth** [comment]
I have reason to believe test_import_file might be failing due to using time.sleep instead of QTests wait to wait for the import.

Sleeping, I think, is blocking everything, even the import, from happening until after the sleep. Depending on how the Eventloop is feeling that day, sleep will happen before import is done and cause issues.
One should replace all sleeps with waits if possible to see if there is any improvement.

**Comment by Marilyth** [comment]
Sleep has been replaced with qWait. Probably all remaining failing tests fail due to not enough waiting.
Tests failing due to not enough waiting are covered here #870
