### ISSUE TITLE
verify user creation for mscolab

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#632]
Currently we can create users in the UI of mscolab without verification by a valid email

we need to send an email to the user and verify by a token that his email address is correct.
only verified users should be added to the database by the gui.

**Comment by aravindm711** [comment]
what email-id are we sending the mail from? @ReimarBauer

**Comment by ReimarBauer** [comment]
this needs be configurable. It is not a general email-id. We could do it similar to http://moinmo.in/HelpOnConfiguration/EmailSupport
and add this to the mscolab_settings
