### ISSUE TITLE
edit user data in mscolab

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#633]
Currently we can add users by username, email address and a password 

We need
 - password change
 - change username
 - change email, only after we can verify the changed email adress, https://github.com/Open-MSS/MSS/issues/632

**Comment by ReimarBauer** [comment]
A further step can be to add a password recovery method.

**Comment by nakul-shahdadpuri** [comment]
Hey @ReimarBauer can I take this up?

**Comment by Jatin2020-24** [comment]
Please assign this issue to me.

**Comment by Jatin2020-24** [comment]
@ReimarBauer  I will complete this by next week.

**Comment by CipJusCodin** [comment]
Hi, is this issue still open? I'm new to open source contributions. Can I take this up?

**Comment by ReimarBauer** [comment]
start with change username

the first part is to add an UI feature to msui.mscolab and to handle the change on the mscolab.server. 
the second to push an event on all users and to change it on any active users display.

do the first part.

**Comment by CipJusCodin** [comment]
On it!

**Comment by ReimarBauer** [comment]
with password recovery implemented the important part is done. Currently changing Names or e-mail needs an admin involved. 

I close this, when someone can describe a safe approach for both we can reopen it
