### ISSUE TITLE
view and edit comfortable json configs

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#634]
currently we have a plain text editor for working with json files

This is a different approach
https://github.com/PaulSchweizer/qt-json-view

this will need a small refactoring for python-3 and QT5. 

We have also to verify if our data is compatible.

That's the documented example. That's promising. We have to look on the boolean syntax. I changed for the example False to None.

![qt-json-view](https://user-images.githubusercontent.com/278728/105769209-c5334180-5f5d-11eb-8a05-db357c94b28c.png)

**Comment by ReimarBauer** [comment]
in moinmoin the help information is generated automatically from the decriptions in the source
result:
http://moinmo.in/HelpOnConfiguration#Access%20control%20lists
source: https://github.com/moinwiki/moin-1.9/blob/master/MoinMoin/config/multiconfig.py#L753

The new editor has to show the meaning of the keys

Also the saved file has only to store changed from default.

On loading a minimum set of changes the editor should also show what can be changed

**Comment by joernu76** [comment]
Realized as part of GSOC2021.
