### ISSUE TITLE
mscolab export/import did not use configured "filepicker_default": "fs" 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#636]
if we configure in mss_settings.json the "fs" filepicker this is currently for mscolab export/import ignored

To verify this you need a config file mss_settings.json to be stored in $HOME/.config/mss

```
{
 "filepicker_default": "fs"
}
```

The used QtWidgets.QFileDialog.getSaveFileName needs to be replaced by mss_qt.get_save_filename 
also QtWidgets.QFileDialog.getOpenFileName by the one of mss_qt.

To compare how that file picker looks like, you can look at it by e.g. save of topview.

fix is needed for:
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py
and look also on the test.

**Comment by aravindm711** [comment]
Hey @ReimarBauer, can I work on this issue?
