### ISSUE TITLE
Editing mscolab Url must be blocked on connect

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#637]
We need to disable editing of the mcolab url once connected. And enable it on disconnect.

![block_editing_of_url](https://user-images.githubusercontent.com/278728/105840583-84760f80-5fd3-11eb-9bda-edfe4e10d7e3.gif)

https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py

**Comment by ahelii16** [comment]
Hey @ReimarBauer I'll take this up!
