### ISSUE TITLE
mscolab disconnect button

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#639]
The disconnect button should use the position of the connect button after  connected. And with disconnect the button should show connect.

![disconnect](https://user-images.githubusercontent.com/278728/105861059-9913d100-5fee-11eb-9022-0174512f16a1.png)

There are changes in mscolab.py needed
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mscolab.py

**Comment by ahelii16** [comment]
Hi, can I take up this issue?

**Comment by Tanish0019** [comment]
@Ahelii16 Sure
