### ISSUE TITLE
fix typo of word "collaboration" in documents

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#640]
We should use the word "collaboration" instead of "colaboration" in all descriptions.

We keep the word mscolab for the module etc.

**Comment by ahelii16** [comment]
Can I do this one?

**Comment by ReimarBauer** [comment]
what a "word" can make a difference. In text we should care for typos.

**Comment by ahelii16** [comment]
We keep the word mscolab for the module etc. - can you explain what this means?

**Comment by ahelii16** [comment]
I have fixed the typo for collaboration in the latest commit for #642 . However I forgot to write #640 . Can you please confirm if it's alright?

**Comment by ReimarBauer** [comment]
> We keep the word mscolab for the module etc. - can you explain what this means?

we don't want to rename the module mscolab.py

**Comment by ReimarBauer** [comment]
> I have fixed the typo for collaboration in the latest commit for #642 . However I forgot to write #640 . Can you please confirm if it's alright?

I look on this later. 
Next time do a new PR for a new issue.

**Comment by ReimarBauer** [comment]
nothing remaining :) Everything alright!

**Comment by ahelii16** [comment]
Thanks 👍
