### ISSUE TITLE
kml overlay should show the selected color close to the filename

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#644]
It is difficult with multiple kml files in a list to find the right one. A double click opens the navigation to updates,

![kml_colorpicker](https://user-images.githubusercontent.com/278728/105883196-dedc9380-6006-11eb-9b76-3f520eb8fa3c.gif)

We want right off the filename a box with the color used and optional that it can be changed by a click
Same for the line style.

Something like: 

![kml](https://user-images.githubusercontent.com/278728/105884261-14ce4780-6008-11eb-89e1-10570e81941d.png)

Sources:
- https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/ui/ui_kmloverlay_dockwidget.ui
- https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/kmloverlay_dockwidget.py

**Comment by risehr** [comment]
Hey @ReimarBauer Can I try this issue?

**Comment by ReimarBauer** [comment]
@risehr you have it 

the function is also decribed on
https://open-mss.github.io/help/

**Comment by SagarBapodara** [comment]
Hey, @ReimarBauer is the issue still open? I would like to give try it.

**Comment by ReimarBauer** [comment]
@SagarBapodara @risehr is working on this.
