### ISSUE TITLE
Remove email field from admin window in mscolab

### ISSUE THREAD

**Issue by Tanish0019** [Open-MSS/MSS#650]
We don't want to show the emails of all the users in the admin window for privacy reason so we need to remove that field from the admin window in mscolab.

**Opening Admin Window**
 - Start mscolab server and the main mss ui
 - Go to mscolab window from the toolbar at the top
 - Connect to mscolab server, login as user, select a project then click on manage users

![image](https://user-images.githubusercontent.com/30210495/106021609-fa20cf00-60ea-11eb-9c5f-b2ba878bd0e7.png)

**Comment by nakul-shahdadpuri** [comment]
@Tanish0019 Hi, can I take up this issue?

**Comment by ReimarBauer** [comment]
You have it

**Comment by ReimarBauer** [comment]
Please send a PR to develop

**Comment by ReimarBauer** [comment]
In the PR is the changed UI file missing

**Comment by nakul-shahdadpuri** [comment]
@ReimarBauer I think I forgot to commit the ui file. I did that now. Sorry.
