### ISSUE TITLE
Replace old ".format" syntax with f"" strings

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#651]
We should replace old .format strings with the new f"" formatting syntax (Please note: the logging must use the old % syntax; aside logging also f"" syntax should be used).

**Comment by iamansoni** [comment]
I would like to work on this task. You can assign it to me. Is this to be done for all the files of [mslib](https://github.com/Open-MSS/MSS/tree/develop/mslib) or only to some files of it?

**Comment by ReimarBauer** [comment]
Hi @iamansoni 
this is already in the queue, taken by SergeLeon.

**Comment by iamansoni** [comment]
Ok, cool!✌
