### ISSUE TITLE
remove the dockerfiles directory from the repository

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#658]
We have on the organisation Open-MSS a dedicated repository for builds on dockerhub

https://github.com/Open-MSS/dockerhub

We should remove the old outdated dockerfiles directory from the development branch.

**Comment by ReimarBauer** [comment]
We moved to https://hub.docker.com/orgs/openmss/repositories

so we should only have one place where we manage/develop Dockerfiles 
This is https://github.com/Open-MSS/dockerhub/

**Comment by Aut0R3V** [comment]
\assign

**Comment by Aut0R3V** [comment]
Hi I'd like to work on this. What I've understood is that the files on https://github.com/Open-MSS/dockerhub need to be removed since they are no longer required. @ReimarBauer Please tell if this is right.

**Comment by ReimarBauer** [comment]
> Hi I'd like to work on this. What I've understood is that the files on https://github.com/Open-MSS/dockerhub need to be removed since they are no longer required. @ReimarBauer Please tell if this is right.

This is a misunderstanding. We have an old version in the repository, see https://github.com/Open-MSS/MSS/tree/develop/dockerfiles

This was moved to the new project but not removed from the repository.
