### ISSUE TITLE
migration dockerhub yourmss to organization openmss

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#662]
We got access by support of hub.docker to
https://hub.docker.com/orgs/openmss/

the workflows for dockerfiles have to be changed and also the site for official releases needs to be updated

**Comment by Marilyth** [comment]
All GitHub Actions now reference openmss instead of yourmss.
What exactly do you mean with `and also the site for official releases needs to be updated`?
@ReimarBauer

**Comment by ReimarBauer** [comment]
some of our docs needs changes too, e.g.

- https://mss.readthedocs.io/en/stable/docker_based_installation.html
- https://open-mss.github.io/develop/docker_images

that likly can become good first issues

**Comment by ReimarBauer** [comment]
added a seperate issue for the follow ups
https://github.com/Open-MSS/MSS/issues/685
