### ISSUE TITLE
MSS 2.0.0 Topview crashes with geos 3.9.x

### ISSUE THREAD

**Issue by gisi90** [Open-MSS/MSS#665]
Topview is not working for a new installation of mss (2.0.0) in new anaconda environment using mamba.

Occurence: everytime when one tries to open topview
System: Linux and Windows

![grafik](https://user-images.githubusercontent.com/54586339/106905391-89863d80-66fc-11eb-85bc-e9c1b68ef9de.png)

![grafik](https://user-images.githubusercontent.com/54586339/106905976-01546800-66fd-11eb-8bb1-6bfce44d1f32.png)

Packages in Anaconda (Windows):

# packages in environment at .conda\envs\mssenv2:
#
# Name                    Version                   Build  Channel
apipkg                    1.5                      py37_0
appdirs                   1.4.4                      py_0
argcomplete               1.12.2             pyhd3eb1b0_0
argon2_cffi               19.1.0           py37he774522_0
basemap                   1.2.2            py37hb8505f4_4    conda-forge
bcrypt                    3.2.0            py37he774522_0
brotlipy                  0.7.0           py37h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2021.1.19            haa95532_0
certifi                   2020.12.5        py37haa95532_0
cffi                      1.14.4           py37hcd4344a_0
cftime                    1.4.1            py37hda49f71_0    conda-forge
chameleon                 3.6.2                      py_0
chardet                   4.0.0           py37haa95532_1003
click                     7.1.2              pyhd3eb1b0_0
conda                     4.9.2            py37haa95532_0
conda-package-handling    1.7.2            py37h76e460a_0
cryptography              3.3.1            py37hcd4344a_0
curl                      7.71.1               h4b64cdc_8    conda-forge
cycler                    0.10.0                   py37_0
defusedxml                0.6.0                      py_0
execnet                   1.8.0              pyhd3eb1b0_0
fastkml                   0.11                       py_1    conda-forge
flask                     1.1.2              pyhd3eb1b0_0
flask-httpauth            4.2.0              pyhd8ed1ab_0    conda-forge
flask-socketio            4.3.2              pyhd3eb1b0_0
flask-sqlalchemy          2.4.4                      py_0
freetype                  2.10.4               hd328e21_0
fs                        2.4.11           py37hc8dfbb8_2    conda-forge
fs.sshfs                  1.0.0              pyhd8ed1ab_1    conda-forge
fs.webdavfs               0.3.7            py37hc8dfbb8_1    conda-forge
fs_filepicker             0.3.7            py37hc8dfbb8_4    conda-forge
furl                      2.1.0                      py_0
future                    0.18.2                   py37_1
geos                      3.9.0                h39d44d4_0    conda-forge
git                       2.30.0               h57928b3_0    conda-forge
gitdb                     4.0.5                      py_0
gitpython                 3.1.12             pyhd3eb1b0_1
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6               h7ebc959_0
humanfriendly             9.1              py37haa95532_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       67.1                 h33f27b4_0    conda-forge
idna                      2.10               pyhd3eb1b0_0
importlib-metadata        3.4.0            py37h03978a9_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
importlib_resources       5.1.0            py37haa95532_1
intel-openmp              2020.3             h57928b3_311    conda-forge
isodate                   0.6.0                    py37_0
itsdangerous              1.1.0                    py37_0
jinja2                    2.11.3             pyhd3eb1b0_0
jpeg                      9d                   he774522_0    conda-forge
jplephem                  2.15               pyh2f6353c_0    conda-forge
kiwisolver                1.3.1            py37hd77b12b_0
krb5                      1.17.2               hbae68bd_0    conda-forge
libarchive                3.5.1                h8686738_1    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libcblas                  3.9.0                     7_mkl    conda-forge
libclang                  10.0.1          default_hf44288c_1    conda-forge
libcurl                   7.71.1               h4b64cdc_8    conda-forge
libiconv                  1.15                 h1df5818_7
liblapack                 3.9.0                     7_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h2a8f88b_0
libpq                     12.3                 h4f54205_3    conda-forge
libsolv                   0.7.17               h7755175_0    conda-forge
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                hc10be44_0    conda-forge
libxml2                   2.9.10               hb89e7f3_3
libxslt                   1.1.34               he774522_0
lxml                      4.6.2            py37h9b66d53_0
lz4-c                     1.9.3                h2bbff1b_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mamba                     0.7.10           py37hed535a2_0    conda-forge
markdown                  3.3.3            py37haa95532_0
markupsafe                1.1.1            py37hfa6e2cd_1
matplotlib                3.3.4            py37h03978a9_0    conda-forge
matplotlib-base           3.3.4            py37h3379fd5_0    conda-forge
menuinst                  1.4.16           py37he774522_1
mkl                       2020.4             hb70f87d_311    conda-forge
mss                       2.0.0            py37h03978a9_1    conda-forge
msys2-conda-epoch         20160418                      1
multidict                 5.1.0            py37h2bbff1b_2
netcdf4                   1.5.5.1         nompi_py37h4965ef1_101    conda-forge
numpy                     1.20.0           py37hd20adf4_0    conda-forge
olefile                   0.46                     py37_0
openssl                   1.1.1i               h2bbff1b_0
orderedmultidict          1.0.1                    py37_0
owslib                    0.22.0             pyhd3eb1b0_0
packaging                 20.9               pyhd3eb1b0_0
paramiko                  2.7.2                      py_0
passlib                   1.7.4                      py_0
pillow                    8.1.0            py37h4fa10fc_0
pint                      0.16.1                     py_0    conda-forge
pip                       20.3.3           py37haa95532_0
proj                      7.2.0                h3e70539_0    conda-forge
property-cached           1.6.4                      py_0    conda-forge
psycopg2                  2.8.6            py37hcd4344a_1
pycosat                   0.6.3            py37h2bbff1b_0
pycparser                 2.20                       py_2
pygeoif                   0.7                        py_1    conda-forge
pymysql                   1.0.2            py37haa95532_1
pynacl                    1.4.0            py37h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyperclip                 1.8.1              pyhd3deb0d_0    conda-forge
pyproj                    3.0.0.post1      py37hce81e75_0    conda-forge
pyqt                      5.12.3           py37h03978a9_7    conda-forge
pyqt-impl                 5.12.3           py37hf2a7229_7    conda-forge
pyqt5-sip                 4.19.18          py37hf2a7229_7    conda-forge
pyqtchart                 5.12             py37hf2a7229_7    conda-forge
pyqtwebengine             5.12.1           py37hf2a7229_7    conda-forge
pyreadline                2.1                      py37_1
pyshp                     2.1.3              pyhd3eb1b0_0
pysocks                   1.7.1                    py37_1
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1              pyhd3eb1b0_0
python-engineio           3.14.2             pyhd3eb1b0_0
python-socketio           4.6.1              pyhd3eb1b0_0
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   227              py37he774522_1
pyyaml                    5.4.1            py37h2bbff1b_1
qt                        5.12.9               hb2cf2c5_0    conda-forge
reproc                    14.2.1               h8ffe710_0    conda-forge
reproc-cpp                14.2.1               h0e60522_0    conda-forge
requests                  2.25.1             pyhd3eb1b0_0
ruamel_yaml               0.15.87          py37he774522_1
scipy                     1.6.0            py37h6db1a17_0    conda-forge
setuptools                52.0.0           py37haa95532_0
sgp4                      2.15             py37h3b38789_0    conda-forge
six                       1.15.0           py37haa95532_0
skyfield                  1.36               pyh44b312d_0    conda-forge
smmap                     4.0.0              pyhd3eb1b0_0
sqlalchemy                1.3.23           py37hcc03f2d_0    conda-forge
sqlite                    3.33.0               h2a8f88b_0
tk                        8.6.10               he774522_0
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.56.0             pyhd3eb1b0_0
typing_extensions         3.7.4.3            pyh06a4308_0
unicodecsv                0.14.1                   py37_0
urllib3                   1.26.3             pyhd3eb1b0_0
validate_email            1.3                        py_3    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
webdavclient2             0.1.1                      py_0    conda-forge
werkzeug                  1.0.1              pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
win_inet_pton             1.1.0            py37haa95532_0
wincertstore              0.2                      py37_0
xstatic                   1.0.2              pyh9f0ad1d_0    conda-forge
xstatic-bootstrap         4.5.3.1            pyhd3deb0d_0    conda-forge
xstatic-jquery            3.5.1.1          py37h03978a9_0    conda-forge
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.8                h4e2f164_1    conda-forge

**Comment by joernu76** [comment]
Mmmh. With a fresh install, I have the same problem. Shouldn't the dockerhub image fail then as well @Marilyth ?
I have yet to find what package causes the problem.
matplotlib is the same version, basemap has a different subversion though (py38h85717e3_3 against py38h2516ec2_4).

**Comment by joernu76** [comment]
Okay, I found the culprit.
geos                      3.9.0
crashes 
geos                      3.8.1
works.

**Comment by joernu76** [comment]
@gisi90 can you verify that
`
mamba install geos=3.8.1
`
solves the issue for you?

**Comment by joernu76** [comment]
@ReimarBauer I am a bit unsure where to change that with out current build structure. Also, geos was so far not in our dependency list...
I propose as hotfix to limit geos to version 3.8.x or below and try to solve the underlying issue, probably upstream...? But we need to develop a minimal testcase for that to demonstrate the problem.

**Comment by joernu76** [comment]
I assigned Reimar to this issue for the hotfix. We should reassign it to me or @Marilyth for solving the underlying issue.

**Comment by gisi90** [comment]
@joernu76 geos 3.8.1 solves the issue

**Comment by gisi90** [comment]
@joernu76 thanks for finding the cause

**Comment by ReimarBauer** [comment]
Oh, what a coincidence hours ago I explained the build number _1 of mss-2.0 ;)

I will prepare a build _2 in a moment

**Comment by joernu76** [comment]
Perfect. Do you know how to install specific build numbers with conda?

**Comment by ReimarBauer** [comment]
just add the next parameter, e.g. 
```
conda install mss=2.0.0=py37h89c1867_1
```

**Comment by ReimarBauer** [comment]
we had geos not yet as a direct dependency in our meta.yaml 
That means it is called by another package we also use. 
We should forward that problem to that package feedstock

https://github.com/conda-forge/basemap-feedstock/tree/master/recipe

**Comment by ReimarBauer** [comment]
@joernu76 I would love to see a pytest which can trigger that behaviour. Then we can care for that also in the normal test situation.

**Comment by joernu76** [comment]
@ReimarBauer We have that. Opening a TopView with a default config crashes and we do that in Tests.
This should have been discovered in the daily(?) dockerhub builds...?

**Comment by ReimarBauer** [comment]
we provide build 2 on conda-forge

**Comment by joernu76** [comment]
I'd like to keep this open for a while as the fundamental issue (MSS not compatible with current geos) remains and needs to be fixed eventually. I'll reduce the priority.

**Comment by ReimarBauer** [comment]
We don't import geos, it comes with basemap. I guess we need another fix in basemap - upstream fix needed 

I created an issue already in the basemap feedstock, but that's also only a follow up of the origin problem

**Comment by ReimarBauer** [comment]
> @ReimarBauer We have that. Opening a TopView with a default config crashes and we do that in Tests.
> This should have been discovered in the daily(?) dockerhub builds...?

I guess this is an issue of geos or basemap not aware of an API change. We do need a test to address it or discuss it with geos / basemap.

**Comment by joernu76** [comment]
I agree that this is not "our" issue, but I am unsure whom to blame yet. To properly file an issue with someone else, we'd need a minimal testcase IMHO. I'll try to generate one this week. Did you file any issue already? Can you cross-link those?

**Comment by ReimarBauer** [comment]
@joernu76 I did this twice time already. But it is difficult to see in comparison to the old place. Look for some picture like

![explain](https://user-images.githubusercontent.com/278728/107273010-cf216e00-6a4e-11eb-86f9-35f3fbb487f9.png)

**Comment by ReimarBauer** [comment]
sorry that was by mistake, wrong button clicked.
