### ISSUE TITLE
Test_mscolab.py failing in develop branch 

### ISSUE THREAD

**Issue by ahelii16** [Open-MSS/MSS#680]
Failing in:  test_view_open, test_get_recent_pid

**Comment by ReimarBauer** [comment]
please show the traceback, and also details about used OS

our testframework here currently looks up only linux

**Comment by ahelii16** [comment]
I'm using Ubuntu 18.04.2 LTS

**Comment by ahelii16** [comment]
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/aheli/Desktop/MSS, configfile: pytest.ini
plugins: cov-2.11.1
collected 40 items                                                                                                                                                                                         

mslib/msui/_tests/test_mscolab.py ....F............s...F..................                                                                                                                           [100%]

================================================================================================= FAILURES =================================================================================================
_______________________________________________________________________________________ Test_Mscolab.test_view_open ________________________________________________________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f9a4cfc76a0>

    def test_view_open(self):
        self._login()
        # test without activating project
        QtTest.QTest.mouseClick(self.window.topview, QtCore.Qt.LeftButton)
        QtTest.QTest.mouseClick(self.window.sideview, QtCore.Qt.LeftButton)
        QtTest.QTest.mouseClick(self.window.tableview, QtCore.Qt.LeftButton)
        QtWidgets.QApplication.processEvents()
        assert len(self.window.active_windows) == 0
        # test after activating project
        self._activate_project_at_index(0)
        QtTest.QTest.mouseClick(self.window.tableview, QtCore.Qt.LeftButton)
        QtWidgets.QApplication.processEvents()
        assert len(self.window.active_windows) == 1
        QtTest.QTest.mouseClick(self.window.topview, QtCore.Qt.LeftButton)
        QtWidgets.QApplication.processEvents()
>       assert len(self.window.active_windows) == 2
E       assert 1 == 2
E        +  where 1 = len([<mslib.msui.tableview.MSSTableViewWindow object at 0x7f9a4c4c2ca0>])
E        +    where [<mslib.msui.tableview.MSSTableViewWindow object at 0x7f9a4c4c2ca0>] = <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a4cfe08b0>.active_windows
E        +      where <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a4cfe08b0> = <test_mscolab.Test_Mscolab object at 0x7f9a4cfc76a0>.window

mslib/msui/_tests/test_mscolab.py:131: AssertionError
------------------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aheli/Desktop/MSS/mslib/msui/mscolab.py", line 709, in open_topview
    self.create_view_window("topview")
  File "/home/aheli/Desktop/MSS/mslib/msui/mscolab.py", line 731, in create_view_window
    view_window = topview.MSSTopViewWindow(model=self.waypoints_model,
  File "/home/aheli/Desktop/MSS/mslib/msui/topview.py", line 179, in __init__
    self.setup_top_view()
  File "/home/aheli/Desktop/MSS/mslib/msui/topview.py", line 217, in setup_top_view
    self.mpl.canvas.init_map(**kwargs)
  File "/home/aheli/Desktop/MSS/mslib/msui/mpl_qtwidget.py", line 878, in init_map
    self.map = mpl_map.MapCanvas(appearance=self.get_map_appearance(),
  File "/home/aheli/Desktop/MSS/mslib/msui/mpl_map.py", line 108, in __init__
    self.map_countries = self.drawcountries(zorder=3)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py", line 1899, in drawcountries
    countries = LineCollection(self.cntrysegs,antialiaseds=(antialiased,))
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1393, in __init__
    self.set_segments(segments)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in set_segments
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in <listcomp>
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/path.py", line 132, in __init__
    cbook._check_shape((None, 2), vertices=vertices)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 2303, in _check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
-------------------------------------------------------------------------------------------- Captured log call ---------------------------------------------------------------------------------------------
2021-02-20 19:51:09 CRITICAL MSS Version: 2.0.0.
2021-02-20 19:51:09 CRITICAL Python Version: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]
2021-02-20 19:51:09 CRITICAL Platform: Linux-4.15.0-135-generic-x86_64-with-glibc2.10 (('64bit', 'ELF'))
2021-02-20 19:51:09 CRITICAL Fatal error: Traceback (most recent call last):
  File "/home/aheli/Desktop/MSS/mslib/msui/mscolab.py", line 709, in open_topview
    self.create_view_window("topview")
  File "/home/aheli/Desktop/MSS/mslib/msui/mscolab.py", line 731, in create_view_window
    view_window = topview.MSSTopViewWindow(model=self.waypoints_model,
  File "/home/aheli/Desktop/MSS/mslib/msui/topview.py", line 179, in __init__
    self.setup_top_view()
  File "/home/aheli/Desktop/MSS/mslib/msui/topview.py", line 217, in setup_top_view
    self.mpl.canvas.init_map(**kwargs)
  File "/home/aheli/Desktop/MSS/mslib/msui/mpl_qtwidget.py", line 878, in init_map
    self.map = mpl_map.MapCanvas(appearance=self.get_map_appearance(),
  File "/home/aheli/Desktop/MSS/mslib/msui/mpl_map.py", line 108, in __init__
    self.map_countries = self.drawcountries(zorder=3)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/mpl_toolkits/basemap/__init__.py", line 1899, in drawcountries
    countries = LineCollection(self.cntrysegs,antialiaseds=(antialiased,))
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1393, in __init__
    self.set_segments(segments)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in set_segments
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/collections.py", line 1408, in <listcomp>
    self._paths = [mpath.Path(_seg) for _seg in _segments]
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/path.py", line 132, in __init__
    cbook._check_shape((None, 2), vertices=vertices)
  File "/home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 2303, in _check_shape
    raise ValueError(
ValueError: 'vertices' must be 2D with shape (M, 2). Your input has shape (0,).
_____________________________________________________________________________________ Test_Mscolab.test_get_recent_pid _____________________________________________________________________________________

self = <test_mscolab.Test_Mscolab object at 0x7f9a4c0d10d0>

    def test_get_recent_pid(self):
        self._connect_to_mscolab()
        self._create_user("anton", "anton@something.org", "something")
        self._login("anton@something.org", "something")
        assert self.window.loggedInWidget.isVisible() is True
        assert self.window.listProjects.model().rowCount() == 0
        self._create_project("flight2", "Description flight2")
        # ToDo fix number after cleanup initial data
>       assert self.window.get_recent_pid() == 8
E       assert 7 == 8
E        +  where 7 = <bound method MSSMscolabWindow.get_recent_pid of <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a43913040>>()
E        +    where <bound method MSSMscolabWindow.get_recent_pid of <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a43913040>> = <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a43913040>.get_recent_pid
E        +      where <mslib.msui.mscolab.MSSMscolabWindow object at 0x7f9a43913040> = <test_mscolab.Test_Mscolab object at 0x7f9a4c0d10d0>.window

mslib/msui/_tests/test_mscolab.py:294: AssertionError
============================================================================================= warnings summary =============================================================================================
conftest.py:30
  /home/aheli/Desktop/MSS/conftest.py:30: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

mslib/msui/_tests/test_mscolab.py: 19 warnings
  /home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/requests/auth.py:39: DeprecationWarning: Non-string usernames will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (None) to a string or bytes object in the near future to avoid problems.
    warnings.warn(

mslib/msui/_tests/test_mscolab.py: 19 warnings
  /home/aheli/anaconda3/envs/mssenv/lib/python3.8/site-packages/requests/auth.py:49: DeprecationWarning: Non-string passwords will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (<class 'NoneType'>) to a string or bytes object in the near future to avoid problems.
    warnings.warn(

mslib/msui/_tests/test_mscolab.py: 16 warnings
  /home/aheli/Desktop/MSS/mslib/msui/flighttrack.py:197: DeprecationWarning: an integer is required (got type ItemFlags).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    return QtCore.Qt.ItemFlags(

mslib/msui/_tests/test_mscolab.py: 18 warnings
  /home/aheli/Desktop/MSS/mslib/msui/flighttrack.py:202: DeprecationWarning: an integer is required (got type ItemFlags).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    return QtCore.Qt.ItemFlags(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================================= short test summary info ==========================================================================================
FAILED mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_view_open - assert 1 == 2
FAILED mslib/msui/_tests/test_mscolab.py::Test_Mscolab::test_get_recent_pid - assert 7 == 8
===================================================================== 2 failed, 37 passed, 1 skipped, 73 warnings in 340.27s (0:05:40) =====================================================================

**Comment by ReimarBauer** [comment]
some of the tests keep some states. I do refactor this currently. 
After that merge is done hopefully this is also fixed.

https://github.com/Open-MSS/MSS/pull/679/files

**Comment by ahelii16** [comment]
I will rewite the remaining tests for #639 also after that

**Comment by ReimarBauer** [comment]
I'd seen that pycharm testing has some differences to the call on the terminal. I try alternatives for the same result.
