### ISSUE TITLE
Check that each dimension has a coordinate dimension (netCDF4tools.py): allow to skip for vars in skip_dim_check

### ISSUE THREAD

**Issue by gisi90** [Open-MSS/MSS#695]
When grib-files of parameters on model-levels (ml) of ECMWF are converted to necdf using cdo, there are 2 additional dimensions (nhyi, nhym) without having a coordinate variable.  The "check that each dimension has a coordinate dimension" in netCDF4tools.py fails for such files because this "check" does not ignore dimNames in skip_dim_check. Adding skip_dim_check worked for me.

`# Check that each dimension has a coordinate dimension`
`for dimName in masterDims:`
  ` if dimName not in cdfm-variables and dimName not in skip-dim_check:`
  `  raise IOError("dimension '{}' has no coordinate variable in master '{}'".format(dimName,master))`

**Comment by ReimarBauer** [comment]
@gisi90 a PR of this change to stable branch, is welcome :) 

flake8 will find the missing blank
```dimName, master```
