### ISSUE TITLE
Adding commands/Making changes in documentation of README file / development docs

### ISSUE THREAD

**Issue by ArchishmanSengupta** [Open-MSS/MSS#719]
# Currently the README of installation of the ``branch: develop`` is this:
![issue7](https://user-images.githubusercontent.com/71402528/111079171-c2e17280-851e-11eb-983e-610086fc1d97.png)

i propose to add documentation of forking the repo and adding it before ``Installation MSS`` guide.

The documentation will then look like 👍🏼

### 💻 1. System requirement :

1. Any system with basic configuration.
2. Operating System : Any (Windows / Linux / Mac).

### 💿 2. Software requirement :

1. Updated browser
2. python (If not download it [here](https://www.python.org/downloads/)).

### ⚡ 3. Skill set :

1. Knowledge of git & github.
2. python

# 📌Setting up the local environment
Forking the repository:
1.Fistly you have to make your own copy of project. For that you have to fork the repository. You can find the fork button on the top-right side of the browser window. (Refer image below )[Adding a picture of the forking button]

2.Kindly wait till it gets forked.

3.After that copy will look like <your-user-name>/MSS forked from Open-MSS/MSS.

# After this i will add the following: 
## 📌 Creating a pull request:  [Adding a picture]

You can guide me through if i miss anything.

Please Assign me this task. @ReimarBauer @andreas-h @Marilyth @PrayasJ @plant99 
Thanks & Regards,
Archie

**Comment by joernu76** [comment]
Hi, good idea!

Some comments.
1) The Readme.md should stay brief and is currently addressing "users" in stead of developers. The documentation you outlined would enhance  https://github.com/Open-MSS/MSS/blob/develop/docs/development.rst greatly! As such I propose to add your github/fork/etc. documentation to that rst-file.
2) I am unsure if we should add figures as these create a larger maintenance overhead. Keep it textual with, perhaps, links to documentation of github or similar.

**Comment by ArchishmanSengupta** [comment]
alright. will keep these things in mind. Actually i am unable to use the IRC Channel. Is there any other way i can keep in touch with you/other maintainers?

**Comment by joernu76** [comment]
The Slack-System *should* be usable wherever you have access to a browser? If that doesn't work, the second best option (and a good option anyway) is to keep the discussion contained in this issue.

**Comment by ArchishmanSengupta** [comment]
can you share me the link of the slack channel which will be used during the gsoc 21 period for this project? @joernu76

**Comment by joernu76** [comment]
@ReimarBauer knows this better, but I believe that we are currently use
https://mss-devel.slack.com/archives/CSL13ATK7
for gsco preparation. There will be a project dedicated channel once we have funding.

**Comment by ReimarBauer** [comment]
Hi @aravindm711 please send a mail to mss-info@fz-juelich.de, see also, first section ;)
https://open-mss.github.io/contributing/

You get an invite link by me.

**Comment by ArchishmanSengupta** [comment]
hey @ReimarBauer I have sent the email to mss-info@fz-juelich.de. kindly have a look. Thank you

**Comment by ArchishmanSengupta** [comment]
hey @joernu76 after i add the necessary changes mentioned in the issue, will i add the (https://github.com/Open-MSS/MSS/blob/develop/docs/development.rst ) link in the readme?

**Comment by joernu76** [comment]
Sounds reasonable that we provide links to the built version of our documentation for further reading.
Here
https://mss.readthedocs.io/en/stable/
is the web-server with the built documentation and this
https://open-mss.github.io/
is a new set of pages added by Reimar. @ReimarBauer , what would be the appropriate system at the current point in time...? And is the new set pf pages based on the RST files?

**Comment by ReimarBauer** [comment]
we create a new issue for other changes
