### ISSUE TITLE
verify newer sqlalchemy >=1.4.0 and sqlite >= 3.35.1 to work with MSS

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#722]
We have currently a fixation in our build scripts because of changes in sqlalchemy and sqlite

This needs to become resolved

**Comment by Marilyth** [comment]
Likely needs to be solved for #1026 to be fixed.
We should check if issues still exist for the higher versions.

**Comment by ReimarBauer** [comment]
We should verify which newer version did not crash our tests and replace the fixation.
