### ISSUE TITLE
Set semi-transparent background to colorbars

### ISSUE THREAD

**Issue by bkirbus** [Open-MSS/MSS#726]
For **horizontal views**, a fully white or semi-transparent white **background behind the colorbar** would be nice.
* Thus, it is easier to read all labels, title, etc. on the colorbar
  * Especially in cases where the maps in the background become very "noisy"

**Comment by joernu76** [comment]
The HS_GenericStyle in mslib/mswms/mpl_hsec_styles.py provides a white background behind the colorbar labeling, which solves this issue in an elegant way (by adding a path effect to the labels).

This solution should be applied to all plotting classes in mslib/mswms/mpl_hsec_styles.py
