### ISSUE TITLE
display canonical version string on installed version

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#731]
Sometimes it is useful not only to talk about MSS versions, seeing which build it is can be better

We should find an easy way to show a string similar to this in the help info of the gui

```
mamba list -c | grep mss

conda-forge/linux-64::mss-2.0.1-py39hf3d152e_0
```

Some problems may occure because the package was installed in the little time frame some library was updated and we have not created a new build.

If I would see this string and together a bug report with sqalchemy problems I could immediatly tell, take the _1 we fixed it :)

**Comment by ReimarBauer** [comment]
the version string can  be retrieved by 
glob.glob(sys.prefix + '/conda-meta/mss-*')

And if the json file is not defined, we likly have a developer installation. 

We could show something about the repo
```
repo = git.Repo(os.path.dirname(os.path.realpath(__file__)), search_parent_directories=True)
repo.head.object
```

**Comment by ReimarBauer** [comment]
current implementation is for the command line.

**Comment by ReimarBauer** [comment]
We look for a smarter solution than the one in the PR.

**Comment by joernu76** [comment]
too complicated for some reason.
