### ISSUE TITLE
Dock-widgets in TableView prevent TableView from closing upon application exit

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#736]
Steps to reproduce the problem:
1) Open a TableView
2) Open a dock widget
3) "Quit" the MainWindow
Expected Outcome:
4) All windows close
Outcome;
4) TableView window remains visible.

The TopView has dockwidgets that work in this regard. One should be able to transfer the proper handling from TopView to TableView.

**Comment by risehr** [comment]
Hi @joernu76  @ReimarBauer ! I have solved this issue. Tests also passed. I have send a PR to develop.
