### ISSUE TITLE
Fix Docs in Setup Instructions

### ISSUE THREAD

**Issue by nakul-shahdadpuri** [Open-MSS/MSS#745]
In the [setup instructions](https://open-mss.github.io/develop/Setup-Instructions) for creating demo data for MSWMS, the documentation says to run 
```sh
python mslib/mswms/demodata.py --create
```
However, --create is not a recognized argument,
```sh
python mslib/mswms/demodata.py --seed
```
should be used to create demo data, and the documentation may be updated.

**Comment by ReimarBauer** [comment]
Thx for finding this, that was not included in the PR

https://github.com/Open-MSS/MSS/pull/654
