### ISSUE TITLE
Syntax error in meta.yaml

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#747]
Our develop docker image is currently failing because there is a space in the version specification of the meta.yaml for sqlite and sqlalchemy.

https://github.com/Open-MSS/MSS/blob/228a7ff34aca56671db0404c2f167a63dda2966f/localbuild/meta.yaml#L75
https://github.com/Open-MSS/MSS/blob/228a7ff34aca56671db0404c2f167a63dda2966f/localbuild/meta.yaml#L76

**Comment by ReimarBauer** [comment]
oh, I assume that got in through a merge from stable. So in stable that is likly also wrong.

the syntax for this is one blank after the module name and no blank after the operator. 
currently looking for a good linter test
