### ISSUE TITLE
update copyright year 2020 to 2021

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#755]
update of all our copyright strings

if noone grabs this I do this before the next release

**Comment by Jatin2020-24** [comment]
@ReimarBauer Please review PR, I have updated copyright year.
Thank you

**Comment by ReimarBauer** [comment]
@Jatin2020-24 there are a few 2020 replaced by 2021  which should be 2020-2021 

I changed the milestone, so develop PR is fine.
