### ISSUE TITLE
Exception "_auth_delegate" attribute error when accessing password protected servers

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#760]
See 
https://github.com/geopython/OWSLib/issues/762

Workaround: install owslib version 0.21 (0.22 does not have this error, but was *very* quickly replaced by 0.23)

**Comment by ReimarBauer** [comment]
intermediate solution by a build fixation for owslib.
https://github.com/conda-forge/mss-feedstock/pull/90

**Comment by joernu76** [comment]
Seems fixed in 0.24.1
