### ISSUE TITLE
The new layer selection dialog should be closeable with Ctrl+W just as the other windows.

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#765]

**Comment by joernu76** [comment]
I admire the problem with the non-triggering actions. One might hack this for the upcoming release:
```
    def keyPressEvent(self, event):                                                                                                                                          
        super().keyPressEvent(event)
        if event.key() == QtCore.Qt.Key_W and event.modifiers() == QtCore.Qt.ControlModifier:
            self.reject()
```
The dialogue can be closed with "ESC", btw, which also rejects the dialogue. It is IMO not obvious that this is a dialogue, because it is not modal and has no OK/CANCEL/etc buttons. Maybe it should be derived from MainWindow instead...?

**Comment by joernu76** [comment]
This here is probably better:
```
--- a/mslib/msui/multilayers.py
+++ b/mslib/msui/multilayers.py
@@ -75,6 +75,9 @@ class Multilayers(QtWidgets.QDialog, ui.Ui_MultilayersDialog):
         self.listLayers.setColumnHidden(2, True)
         self.listLayers.header().setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
 
+        self.close_shortcut = QtWidgets.QShortcut(QtGui.QKeySequence("Ctrl+W"), self)
+        self.close_shortcut.activated.connect(self.reject)
+
     def remove_filter_triggered(self):
         self.leMultiFilter.setText("")
         if self.filter_favourite:
```

**Comment by joernu76** [comment]
Would still be interesting to know why the "standard way" does not work.

**Comment by Marilyth** [comment]
Thanks for looking into this yourself.
The reason shortcuts aren't working seems to me that actionCloseWindow is never actually added to the dialog, and I am not sure why. Maybe I am using Designer wrong?
So basically this line is missing in ui_wms_multilayers.ui:
`<addaction name="actionCloseWindow"/>`
Adding it manually is making it work again.

**Comment by joernu76** [comment]
Mmh. I had no luck doing that myself in Creator. I remember now having had the same problem and - apparently? - coming to the same solution. Adter addding the element to the XML, it appears in creator, but I couldn't quickly figure out a way to do that in the GUI. I think, I could drag the action to the list of objects on the upper right, but am unsure about that. Or using some other dialog? mmh. Strange.
Thanks!

**Comment by Marilyth** [comment]
You can drag and drop Actions into menus through the Designer, e.g. in ui_mainwindow.ui. I think they are not meant to be used standalone without a menu.
