### ISSUE TITLE
Show >=2 flight tracks at the same time

### ISSUE THREAD

**Issue by bkirbus** [Open-MSS/MSS#802]
Is it possible to show 2 flight tracks at once on the Horizontal View? Of course, it's possible to activate them one after another in quick succession. But an important aim of our upcoming campaign HALO-(AC)3 is coordinating 2 airplanes at once. So it would be cool to
* **show 2 flight tracks at the same time** (e.g. with different colors) on Horizontal View.

**Comment by ReimarBauer** [comment]
This can be at current state reached by using the KML overlay and displaying a different flightpath there.
Therefore a parser flight track to kml is needed.

**Comment by bkirbus** [comment]
@ReimarBauer I tested it, and it works like a charm. It's perfect to directly adjust waypoints according to another (previous or parallel) flight pattern. The only question would be if it's also possible to edit (and not only show) the second flight track as well.

Thanks again, cheers

**Comment by ReimarBauer** [comment]
Currently you can do it with twice time opened MSS and loading in each one of the flightpathes and the other as kml overlay. 

I thought some time ago on something like this. This is not only interesting for your case.
 
![dockwidget_flightpath](https://user-images.githubusercontent.com/278728/115292309-14040800-a156-11eb-8f55-f7a65254934d.png)

This would also have a control to activate the flight path which gets changes.  
To use this we need some other steps done first. 


You probably have seen the ideas page https://open-mss.github.io/develop/GSOC2021/ideas
On May 17th the accepted projects become announced.

**Comment by joernu76** [comment]
Option A) Improving workaround with existing tools
One could rather simply add a new dockwidget/feature to the KML thingie that could check a target file for changes and update accordingly. I.e. it would 
1) make sense to support FTML files in the KML feature dialogue (such that the export-to-KML-feature need not be used. That is straightforward
2) Check for changes to the underlying file and update the visualisation upon such a change. No idea if that is easy or hard.

Option B)
We are working on a collaboration feature, where one could also do this without a file, but this feature needs to be completed first (there are a couple of big construction sites ongoing).
That would allow to open to MSS instances and edit both tracks at the same time, one in each MSS instance. That would be very, very close to what you desire. Might be achievable within this year.

Editing two flight tracks, at the same time, within one instance, with two TableViews etc, will never work, I guess.
