### ISSUE TITLE
missing values in netCDF data are ignored

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#811]
values such as -1e30 used to flag missing data using the missing_value attribute are ignored by horizontal plots.

**Comment by jgrooss** [comment]
![sideview_number](https://user-images.githubusercontent.com/32653190/119109571-9287ea00-ba21-11eb-9223-9abf2b4c39ea.png)
This seems not solved for side view images. Flightpath EDMO-Kiruna, Datafile for this case is in
/usr/nfs/software/icg1/exchange/j.-u.grooss/mss

**Comment by joernu76** [comment]
Mmmh. The routine used for interpolating onto cross-sections does not support masks.
But maybe it properly works with NaN. I'll try something.

**Comment by joernu76** [comment]
Is it better now and not misbehaving in different forms?

**Comment by jgrooss** [comment]
yes, looks good now

**Comment by joernu76** [comment]
Then I'll prepare a patch to develop.
