### ISSUE TITLE
Simplify use of Server/Layer window

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#816]
In the Server/Layer window the available parameters to display can be chosen.
If one parameter is clicked (and a color scale has been chosen) the information is transferred to the main window.
(1) depending on the avaiable work screen, the  Server/Layer window is likely overlapping the main (top view) window and such blocks the sight to the main window. There should be an easy possibility to close this Server/Layer window after the parameter choice, either by double-klick on the parameter or by introducing a "dismiss" button. Or both.
(2) If the parameter has been chosen and the "Auto-Update" is chosen in the main window, the parameter should be displayed immedeately to avoid another klick of "retrieve"

**Comment by joernu76** [comment]
I like the double click ad (1) but cannot say if QT UI guidelines require another button. ctrl+w/the close window WM button are fine fore me. Might not be obvious to every user, though.

**Comment by jgrooss** [comment]
potentially double click on either parameter or Style (colorscale) choice to close the window

**Comment by Marilyth** [comment]
So to sum it up, there are currently 3 ways to close the Server/Layer window.
1. Pressing Escape
2. Pressing Ctrl+W
3. Closing the window on the top right like any other regular window

You are suggesting to add 3 other options:
1. Double click a layer
2. Add an additional "dismiss" button
3. Auto close whenever the map is updated

Do I understand you correctly?
I dislike 2. as I find it very redundant at this point.
The rest I can implement and see how it goes.

**Comment by joernu76** [comment]
Option 3) was not suggested (this is a separate problem).
I would implement option (1), Jens-Uwe suggests option (2).

(3) is a bug? That the map is not updated (immediately) when a different layer is selected and "auto-update" is active.

I would not implement a double-click on the style thingie.

**Comment by jgrooss** [comment]
I was not aware of option "pressing escape" or "CNTL-W" 
I would be happy with having the double click implemented. 
Or is it possible to print the information "exit by ESC" somewhere in the window?

**Comment by joernu76** [comment]
I feel that both my mother, wife and children feel that the only way to ever exit any kind of dialogue is to press the small x in the top right corner...

FYI: You can close *any* MSS windows with Ctrl+W, except the Main Window, which quits the application with Ctrl+Q.

**Comment by ReimarBauer** [comment]
that's the reason because we have also on many other windows only this x :) 

And last time I already disliked this superflious dismiss button. 

But I see a further need to describe the keys we have defined 
https://github.com/Open-MSS/MSS/issues/784

and also document them

**Comment by Marilyth** [comment]
For reference, auto-update combined with double clicking, is proving more difficult than I thought.
I will implement 3) and need to ponder on the possibility of 1) a bit longer.

**Comment by joernu76** [comment]
what about
```diff --git a/mslib/msui/multilayers.py b/mslib/msui/multilayers.py
index ae9a9162..7636e66e 100644
--- a/mslib/msui/multilayers.py
+++ b/mslib/msui/multilayers.py
@@ -345,7 +345,7 @@ class Multilayers(QtWidgets.QDialog, ui.Ui_MultilayersDialog):
             self.cbWMS_URL.setCurrentIndex(index)
         self.needs_repopulate.emit()
         if not self.cbMultilayering.isChecked():
-            self.dock_widget.auto_update()
+            QtCore.QTimer.singleShot(50, self.dock_widget.auto_update)
         self.threads -= 1
 
     def multilayer_doubleclicked(self, item, column):
```
?

**Comment by Marilyth** [comment]
I am playing around with Timers as well. 
I thought race conditions might break things but it seems safer than I thought.
So far I have managed to break a few things with it however.

**Comment by joernu76** [comment]
I did a lot of bad stuff with events and event queues in the past that cannot be recommended... (SDL and SystemC).
And I am not familiar with the QT system at all to properly judge this.

But I hope not much can happen in 50ms... This will break for certain double-click settings etc. so I would certainly qualify it as a "hack" and it should be documented as such in the code if adopted.
Alternatively, one could also delay the "click" event to occur after the "doubleclick" event, but that is more tedious and IMO even more dangerous...

**Comment by joernu76** [comment]
This timer has also the added benefit that the map is only fetched (typically) after the window has been closed, which, for my tiling window-manager, means that the proper map size is fetched.
:-)
