### ISSUE TITLE
Displayed newest initialisation time as default

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#824]
When on a MSS server multiple forecast data sets with different initialisation times are present, the default setting should be to disply the newest initialisation time. This is the most likely to be looked upon.
This is currently not the case. Please fix it.

**Comment by Marilyth** [comment]
@joernu76 @jgrooss This might be interfering with a previous design decision we made when creating the Multilayer window. I might need some more input to find a proper solution. Or maybe I am thinking too much about it.

Per default and if possible, the initialisation times are carried over from the previous selection, which are not necessarily the newest or oldest.

E.g.
- Layer A has initialisation times X and Y
- Layer B has initialisation times Y and Z
Where Z is newer than Y is newer than X

1. The user picks Layer A, and it defaults to Y
2. Then the user picks Layer B, it defaults to Y from the previous selection, even though Z is newer

Would this be considered unwanted behaviour? 
Should initialisation times always default to the newest and not be carried over?

**Comment by joernu76** [comment]
It is complicated.
I think we now store a couple of options persistently.
Once a new init time has been selected, it will probably be transfered to new chosen layers?
I think a call to get_capabilities should "invalidate" currently stored init_time(s) (are they stored somewhere...?) and update them with the most recently available one for that layer.
Would that make more sense?
