### ISSUE TITLE
kml overlay does not display open lines

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#829]
(The problem described first here was caused by a corrupted kml file. Therefore the following text is deleted. However, another bug was found, described below) 
kml overlay can be used to overplot the flight information regions.
When shifting the map range in  a (stereographic) map projection, the kml overlay does not update itself automatically.This only occurs if the kml overlay is unticked and ticken again.
![fir_orig](https://user-images.githubusercontent.com/32653190/115899323-e7563600-a45e-11eb-8edd-9a804bd40b2b.png)
![fir_shifted](https://user-images.githubusercontent.com/32653190/115899340-eae9bd00-a45e-11eb-852a-f25c3cae0488.png)

[fir_test.kml.txt](https://github.com/Open-MSS/MSS/files/6366015/fir_test.kml.txt)

**Comment by jgrooss** [comment]
I could not add a kml file here therefore I named it kml.txt

**Comment by ReimarBauer** [comment]
That is the result of the fir_test.kml on google maps engine

![kml_output_on_gmaps](https://user-images.githubusercontent.com/278728/115892166-313b1e00-a457-11eb-8bd3-6a0924e2cf95.png)

**Comment by ReimarBauer** [comment]
I guess for an open line this will be the syntax
[j.kml.txt](https://github.com/Open-MSS/MSS/files/6366349/j.kml.txt)


but I think I found another issue by this. I don't get it to the right location in northern stereo 

it should be here
![there](https://user-images.githubusercontent.com/278728/115893963-0b167d80-a459-11eb-8222-153a92626c73.png)

I get it at 

![moved](https://user-images.githubusercontent.com/278728/115894091-2bded300-a459-11eb-8337-f3c15061b34e.png)

I could move it around

![moved_map](https://user-images.githubusercontent.com/278728/115894547-af002900-a459-11eb-81c3-ebb57698afcc.png)

**Comment by ReimarBauer** [comment]
LINESTRING instead of POLYGON is needed

**Comment by jgrooss** [comment]
This point is now discussed in issue #830
