### ISSUE TITLE
patch from kml overlay did not keep position when stereo map is moved

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#830]
Example
[j.kml.txt](https://github.com/Open-MSS/MSS/files/6366349/j.kml.txt)

I found an issue by this. I don't get it to the right location in northern stereo 

it should be here
![there](https://user-images.githubusercontent.com/278728/115893963-0b167d80-a459-11eb-8222-153a92626c73.png)

I get it at 

![moved](https://user-images.githubusercontent.com/278728/115894091-2bded300-a459-11eb-8337-f3c15061b34e.png)

I could move it around but it should have a fixed position

![moved_map](https://user-images.githubusercontent.com/278728/115894547-af002900-a459-11eb-81c3-ebb57698afcc.png)

**Comment by jgrooss** [comment]
some additional minor point:
if a kml overlay is chosen and  box is ticked the overlay is displayed correctly
If then the map projection is changed, it is not displayed. One must untick and tick the box again to display the overlay.
(similarly untik & tick the kml overlay box fixes the shown mis-display of the kml coordinates shown above)

**Comment by jgrooss** [comment]
one more:
As the kml overlay is used mainly for displaying FIR borders. I would ask to set the default thickness to 2 instead of 5.

**Comment by ReimarBauer** [comment]
In other projections no user interaction is needed than just panning. So this problem is related to stereo projections

**Comment by ReimarBauer** [comment]
@jgrooss make for the minor things please new issues.  some minors look like features instead of bugs.

 e.g. the features can also be useability bugs, but if we need to do  API changes I prefer to shift that to 3.1.0

**Comment by ReimarBauer** [comment]
when we tick the box in the kml docking widget the draw function of the widget is called. This does draw  correct. When we use panning then this draw function is not used. pannig is builtin of matplotlib.

**Comment by ReimarBauer** [comment]
> some additional minor point:
> if a kml overlay is chosen and box is ticked the overlay is displayed correctly
> If then the map projection is changed, it is not displayed. One must untick and tick the box again to display the overlay.
> (similarly untik & tick the kml overlay box fixes the shown mis-display of the kml coordinates shown above)

I have this only with stereo map projections. I think it is just drawn on a wrong position.

If I choose between Europe and Global which are both cyl. projection type it works as expected

**Comment by ReimarBauer** [comment]
Stere is missing:
https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/mpl_map.py#L420

**Comment by joernu76** [comment]
The refactoring of last summer killed the redrawing of KML objects after map projection/panning changes.
Fix incoming.
