### ISSUE TITLE
New view mode, providing 1-D samples along the flight path

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#833]
@joernu76 @jgrooss As this work package might be interesting to you.

Many atmospheric measurement instruments measure atmospheric quantities in situ that is only at the location of the aircraft. Both for flight planning, but especially for flight analysis, it is beneficial to have available a kind of plot similar to those used by the scientists in data exploration, which is a simple 1-D plot of quantity over time with multiple quantities (e.g., water vapour and
ozone volume mixing ratios).

Example:
![Screenshot at 2021-04-26 08-56-50](https://user-images.githubusercontent.com/19623152/116045929-d716a480-a672-11eb-8f7b-a3eed9b78057.png)

**Comment by ReimarBauer** [comment]
Likly waypoints can be disabled, but zoom and panning may be interesting

**Comment by jgrooss** [comment]
This is nice. I thought of this long ago, see #152 :-)

**Comment by joernu76** [comment]
Ah, there was an issue already. Probably the input to the WP of the DFG proposal we wrote.

**Comment by joernu76** [comment]
Zooming/panning is not *that* useful, currently, as these are figures generated by the server and one would simply see more blocky pixels...
If we decide to generate the figure locally, enabling full pan/zoom control would be obviously quite easy to implement...

**Comment by ReimarBauer** [comment]
changed milestone because of https://semver.org/lang/de/
