### ISSUE TITLE
mscolab issues

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#837]
A few issues we ran into at our last meeting discussing mscolab
- [bug] When logging in with wrong credentials, you receive a fatal JSON error (bug)
- [enhancement] It might be troublesome to log in twice, once to get access to the server and once to log into your mscolab account
- [Unsure] The config set up in the json, containing the mscolab server address and credentials, seems to have been ignored
- [bug] HTTP Authentication is not cancelable
- [bug] Login should be disabled without email and password provided
- [bug] Some odd Socket Error popped up and caused all sorts of synchronisation issues (Add Project greyed out, not updated on changes, etc)
- [bug] When the permissions for a project changes from e.g. collaborator to admin, the project gets added twice for the user

**Comment by joernu76** [comment]
I would suggest to create separate issues and see, which bugs are trivial to fix (some should be) and do those right away to stable. More complex changes might go to develop. Issue for todays meeting.

**Comment by Marilyth** [comment]
Put into seperate issues
