### ISSUE TITLE
mscolab connection error

### ISSUE THREAD

**Issue by jgrooss** [Open-MSS/MSS#838]
There is some problem when logging into the mscolab server,
after personal login there comes the following error message:

------------------------------------------------------------------------------------------------
Fatal error in MSS 3.0.1. on Linux-5.4.0-72-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 551, in authorize
    self.after_authorize(emailid, r)
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 570, in after_authorize
    self.conn = sc.ConnectionManager(self.token, user=self.user, mscolab_server_url=self.mscolab_server_url)
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/mslib/msui/socket_control.py", line 54, in __init__
    self.sio.connect(self.mscolab_server_url)
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/socketio/client.py", line 286, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Connection refused by the server
------------------------------------------------------------------------------------------------

after clicking the "Manage Users" button comes the follwing message
------------------------------------------------------------------------------------------------

Fatal error in MSS 3.0.1. on Linux-5.4.0-72-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/mslib/msui/mscolab.py", line 462, in open_admin_window
    self.admin_window = maw.MSColabAdminWindow(self.token, self.active_pid, self.user,
  File "/home/icg122/anaconda3/envs/mss301/lib/python3.9/site-packages/mslib/msui/mscolab_admin_window.py", line 77, in __init__
    self.conn.signal_project_permissions_updated.connect(self.handle_permissions_updated)
AttributeError: 'NoneType' object has no attribute 'signal_project_permissions_updated'
------------------------------------------------------------------------------------------------

[mamba_list.txt](https://github.com/Open-MSS/MSS/files/6392727/mamba_list.txt)

**Comment by jgrooss** [comment]
Fot problem inspection, the anaconda directory of my computer has been copied to
icg1805:/private.scratch/icg122/priv/anaconda3

**Comment by Marilyth** [comment]
I will take a look at that directory of yours

**Comment by Marilyth** [comment]
Unfortunately it doesn't seem to be your anaconda. Things work fine on my end with your installation.
Maybe it is a firewall issue of some kind..

**Comment by Marilyth** [comment]
This seems to have been an issue with the way the settings saved the server/email, causing a connection error or a wrong credentials error.
Apparently this is fixed now.
