### ISSUE TITLE
Wrong credentials in mscolab result in fatal error

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#849]
When logging in with wrong credentials, you receive a fatal JSON error as seen in the picture
![login](https://user-images.githubusercontent.com/19623152/116525200-9029e880-a8d8-11eb-8fa9-507a340154ec.png)

**Comment by ReimarBauer** [comment]
@Marilyth in 3.0.1 I don't have this. The picture shows a 3.0.0 version. This could be too old?

Anyway that should have worked also with 3.0.0

looking how that could happen

**Comment by Marilyth** [comment]
It happens still on the latest stable.
I will look into this tomorrow.
