### ISSUE TITLE
mscolab server authentication and login could be reduced to one

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#850]
When logging into a mscolab server which requires authentication, one needs to login twice, once into the mscolab server and once into the account.
This might be confusing and troublesome.

**Comment by ReimarBauer** [comment]
before someone starts working on this, post some idea / proposals here

**Comment by aravindm711** [comment]
Hello @Marilyth @ReimarBauer , would a straight forward solution work for this? Like removing the connect button and calling the connect handler when login/adduser button is pressed after entering the credentials. Also the status label wouldn't make sense if this is implemented, would it? If this sounds good, i'll try to make modifications to the UI and get feedback before implementing.

**Comment by ReimarBauer** [comment]
Hi @aravindm711 we have this [login protection](https://mss.readthedocs.io/en/stable/mscolab.html#protecting-login) which I need on the server site. This and the user login credentials can be set in the users mss_settings.json.  But if this is not set the user gets first the server authentication and afterwards the login. 

Currently only the server auth protects for user creation spam. Anyone connected can create users. I also want that users can create accounts after they are connected.

**Comment by aravindm711** [comment]
Would we not be able to use server auth if we connect to the mscolab server when the user hits login/adduser? Because the only thing the user can do after connecting to a server, is login or add user.

**Comment by ReimarBauer** [comment]
When nothing is configured on my server the current behaviour is like this for add user. And if we don't have server auth then add user is open to everybody.

At current time I can seperate users by server instances. At a time we can create kind of "namespaces" aka servers as e.g. discord does, we may be can handle this differently.

![auth](https://user-images.githubusercontent.com/278728/117862122-96ce3d80-b292-11eb-8ba4-052227a06443.gif)

**Comment by ReimarBauer** [comment]
Due to the config options and also updating the config on first access this is now much simplified.

https://github.com/Open-MSS/MSS/pull/1339
