### ISSUE TITLE
Multilayering test failing sometimes

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#854]
I observed a few instances of one of my multilayering tests failing, probably due to the Auto-Update now triggering on layer changes in develop.
This bug doesn't need a fix in stable yet.

**Comment by joernu76** [comment]
Does this also relate to this
https://github.com/Open-MSS/MSS/runs/2465552979?check_suite_focus=true
?

**Comment by Marilyth** [comment]
It doesn't. This seems like another problem perhaps related to the parallel setup
