### ISSUE TITLE
mscolab connect/disconnect signal leak

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#873]
On each connection or disconnection to a server, the signal for the buttons is switched between connect_handler and disconnect_handler.
However the old signal is never cleaned up. So after a while a single button click will connect and disconnect an arbitrary amount of times, causing the whole application to slow down.

**Comment by ReimarBauer** [comment]
good catch :)

**Comment by Marilyth** [comment]
This also happens here https://github.com/Open-MSS/MSS/blob/3605e3d6d368cbee7cd9cda8c466e07363f57be6/mslib/msui/mscolab.py#L201
