### ISSUE TITLE
login button is blocked for stored credential

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#881]
When login credentials are not typed the button Login is blocked

![login_blockes](https://user-images.githubusercontent.com/278728/116723105-6c04ff00-a9df-11eb-8bde-3fa4753e8ba0.gif)

**Comment by Marilyth** [comment]
There is also another signal leak with the email and password connects
I assume the fix for this issue will be around these lines so perhaps you could kill two birds with one stone?
https://github.com/Open-MSS/MSS/blob/f77981a2e49b193a163893224e97937fbf3387e1/mslib/msui/mscolab.py#L203
