### ISSUE TITLE
Fatal error on Load Configuration File

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#892]
When selecting "Load Configuration File" in the main window, this fatal error pops up
![Screenshot at 2021-05-04 16-27-45](https://user-images.githubusercontent.com/19623152/117019601-d7a7de80-acf5-11eb-8085-b2714c5ddc2a.png)

**Comment by ReimarBauer** [comment]
Inform user and ignore. 

A further step could be a migration script.

**Comment by joernu76** [comment]
This is a rather unimportant setting, which should not cause a fatal error when not given.
Adding this
`
    "filepicker_config": "qt",
`
to the JSON file solves the issue.

**Comment by joernu76** [comment]
mmmh.
when I remove the setting from my JSON file, it does not crash.
What is necessary to provoke the crash?

**Comment by joernu76** [comment]
@ReimarBauer 
OK, who introduced filepicker_config parameter without supplying a default value? Is this needed?
we either need to remove the parameter *or* supply a default value. I can provide a fix, but this is a bug.

**Comment by ReimarBauer** [comment]
in our code we need it renamed to "filepicker_default" 

All other filepicker_* lines were replaced that was missed.

**Comment by ReimarBauer** [comment]
That was just missed here

https://github.com/Open-MSS/MSS/commit/348e4372806e7368e10bedb94f7ee4fc35297a6c

**Comment by ReimarBauer** [comment]
> Inform user and ignore.
> 
> A further step could be a migration script.

We have to check what happens if there are other names used.

**Comment by joernu76** [comment]
other names? anything but fs/qt/default will generate a Fatal Error AFAIK
