### ISSUE TITLE
star / unstar feature on windows 10 (OS) does not always work

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#896]
Some of the windows user can set some star but removing seems not to work also further staring seems not be possible

**Comment by joernu76** [comment]
You refer to the "star"/liking of multilayers in the WMS dialogue on windows?

**Comment by ReimarBauer** [comment]
> You refer to the "star"/liking of multilayers in the WMS dialogue on windows?

yes, seen the problem in the flightplanning meeting.

**Comment by Marilyth** [comment]
Can't reproduce under normal conditions.
Did the person perhaps use a scaling option other than 100%?
![image](https://user-images.githubusercontent.com/19623152/117113017-33bc4280-ad8a-11eb-9f41-2b2ae5f7fc76.png)

**Comment by joernu76** [comment]
Does this question imply that you can reproduce it with different scalings?

**Comment by Marilyth** [comment]
The hitbox of the icons changes on different scaling options, yes.
Generally the scaling options in Windows are prone to destroying usability of many apps, and games.
So knowing this is the cause would help in fixing it.

**Comment by joernu76** [comment]
see also here https://doc.qt.io/qt-5/highdpi.html
Are we doing something wrong there?

**Comment by ReimarBauer** [comment]
on my 4K displays without scaling this works, but I'm on linux.
