### ISSUE TITLE
request update of mss

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#899]
We need MSS UI itselfs to recognize that the used version is outdated. 

When this is recognized the user should see a hint how to get to the newest version.

**Comment by Marilyth** [comment]
I think it would make sense to combine this issue with an auto-updater, to make it as easy as possible for the user.
![updater](https://user-images.githubusercontent.com/19623152/117332256-e5956500-ae97-11eb-9499-cc810eb5ff45.gif)
