### ISSUE TITLE
Fatal error when working locally without ~/mss folder

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#900]
When ticking the "Work Locally" checkbox in mscolab without an existing ~/mss folder, this fatal error pops up.
![Screenshot at 2021-05-05 10-18-10](https://user-images.githubusercontent.com/19623152/117113987-89451f00-ad8b-11eb-85a2-15c77b0a1638.png)

**Comment by joernu76** [comment]
`home/mss` does not seem appropriate either.
This
`$XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.` would be a better place (with /mss at the end, obviously).

**Comment by joernu76** [comment]
I do not understand fs well enough to fix this. With os.path, it would be easy. But I do not find a way to manipulate the data_dir  variable in a way that would allow me to create the missing directory.

We might run into a similar issue with configuration or other open_fs calls.

**Comment by joernu76** [comment]
This is what we use for the config file:
```
HOME = os.path.expanduser("~/")
MSS_CONFIG_PATH = os.getenv("MSS_CONFIG_PATH", os.path.join(HOME, ".config", "mss"))                                                                                         
if not os.path.exists(MSS_CONFIG_PATH):
    os.makedirs(MSS_CONFIG_PATH)

```

**Comment by ReimarBauer** [comment]
The issue here is this path is not created, while it is for the tests in a different /tmp folder. ;)
The tests have to use a different folder. Unfortunately the dir creation is on the wrong place for the tests.
