### ISSUE TITLE
Fatal error in config loader because of invalid character

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#901]
On OS Windows 10 a user sees a problem loading his settings file

![Clipboard - 5  Mai 2021 10 17](https://user-images.githubusercontent.com/278728/117115897-01144900-ad8e-11eb-95b5-03d1099b241e.png)

**Comment by joernu76** [comment]
People are using the config-thingie a lot...
The path does not look like it contains invalid characters...?

**Comment by Marilyth** [comment]
Might be an issue with fs no supporting `\` in paths
fs.path.split() also doesn't work on Windows, as it only splits on `/`, not on `\`

from fs.path.split
```
if "/" not in path:
    return ("", path)
split = path.rsplit("/", 1)
return (split[0] or "/", split[1])
```

**Comment by joernu76** [comment]
fs is causing us a lot of issues.

Do you have a access to a Windows system for testing?

**Comment by joernu76** [comment]
@ReimarBauer I have the feeling that we can use either os or fs but not both. (e.g. due to "/" "\").
Can you replace all os.path stuff with fs replacements? grep should discover a lot.

**Comment by Marilyth** [comment]
I have a Windows and Linux system for troubleshooting. We had multiple instances of issues with fs on Windows already.

**Comment by ReimarBauer** [comment]
On a old 2.0.1 without own configuration this does not happen on the guacamole windows 10 system.
on a recent 3.0.2 config editor opens without an error too.

**Comment by ReimarBauer** [comment]
The problem happens with saving 

just
```
{
}
```
can't be saved.

**Comment by Marilyth** [comment]
The issue arises when mss_settings.py was automatically loaded.
It does not happen when no settings were loaded, and it does not happen when the setting were manually loaded.

**Comment by ReimarBauer** [comment]
I found some more problems and working on a test while I already have an idea how to solve it.
https://github.com/Open-MSS/MSS/pull/936

We have also a problem when there is not any mss_settings.json defined. I struggeled with windows over a None path and seen afterwards that I had this also on linux.

I added @Marilyth hotfix, but we can later merge both in a row.

**Comment by ReimarBauer** [comment]
With current stable I have this without a mss_settings.json
```
Fatal error in MSS 3.0.2. on Linux-4.15.0-142-generic-x86_64-with-glibc2.27
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 
[GCC 9.3.0]

Please report bugs in MSS to https://github.com/Open-MSS/MSS

Information about the fatal error:

Traceback (most recent call last):
  File "/home/user/PycharmProjects/mss/mslib/msui/editor.py", line 203, in file_save_and_quit
    self._save_to_path(self.path)
  File "/home/user/PycharmProjects/mss/mslib/msui/editor.py", line 228, in _save_to_path
    dir_name, file_name = fs.path.split(filename)
  File "/home/user/miniconda3/envs/mssdev/lib/python3.9/site-packages/fs/path.py", line 313, in split
    if "/" not in path:
TypeError: argument of type 'NoneType' is not iterable
```
