### ISSUE TITLE
better management of MSCOLAB servers in drop down list

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#906]
I have a long list of local/remote servers and the server I need is way down the list.
I'd like to remove some servers and I'd like MSS to have the last used server selected.

**Comment by ReimarBauer** [comment]
one option is to use the config var into the json file
```
default_MSCOLAB 
```
But I would like this trashcan icon as May added it to the multilayer selection window on this place too.

**Comment by ReimarBauer** [comment]
a similar question: 
https://github.com/Open-MSS/MSS/issues/865

**Comment by joernu76** [comment]
OK, the config variable solves 80% of my issues. Not being able to loose a server from the history *ever* is the remaining one.
I would be fine with not storing used servers persistently outside of the JSON file. I would implement that.

**Comment by ReimarBauer** [comment]
I agree to this, there can be eaily a long list by tests collected which is superfluos. 

On browsers it is implemented with an autocomplete feature. Once you type it takes the one from the cache. This would be another option to have an empty list, besided the default_MSCOLAB.

**Comment by joernu76** [comment]
autocomplete feature would be an option, but a way more complicated one. Doesn't work to my full satisfaction in browsers either, btw.

**Comment by ReimarBauer** [comment]
For me on a linux shell it works perfect. It is difficult to find anything on the worlds scope which satisfies on all circumstances all users.

But for now lets go with the simplest solution, we need a hint in the empty field where to add a default.

**Comment by ReimarBauer** [comment]
The long list, btw. is a different problem, the xdist tests create those. A common user, has only 1 there.

**Comment by ReimarBauer** [comment]
Just recognized that it does autocomplete already. when I type http://m it shows me the staging server.
