### ISSUE TITLE
show name of the flightpath/project on the views

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#916]
If one presents a flightpath we currently have no information which it is.

We should display the flightpath name / msco project name on the other views (tableview, sideview, topview)

Perhaps  we could add it as label into the space between Level and Autoupdate

![space](https://user-images.githubusercontent.com/278728/117257441-2a93aa00-ae4c-11eb-866d-f029ff0720f8.png)

**Comment by jroettenbacher** [comment]
Hi Reimar, I will have a go at this.

**Comment by jroettenbacher** [comment]
However, I think the space between Level and Autoupdate is not really intuitive for the flight track/project name. Maybe in the top of the window would be better. After MSS:
![grafik](https://user-images.githubusercontent.com/44004932/118127365-e3805880-b3f9-11eb-9578-b469b352128c.png)

**Comment by jroettenbacher** [comment]
What do you think about this?
![grafik](https://user-images.githubusercontent.com/44004932/118139246-75db2900-b407-11eb-90b9-ad3619250b04.png)
