### ISSUE TITLE
Topview Home Button return to initial coordinates

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#919]
The topview Home Button does not load the initial coordinates. 
So there is no option to get back to the origin without restarting topview.

**Comment by joernu76** [comment]
Interesting. This button is served by matplotlib. 
One can certainly restore the view by re-selecting the projection again from the drop down list.
I'll see if we have control over that.

**Comment by joernu76** [comment]
"History" arrows do not work as well.

**Comment by joernu76** [comment]
Seems to work for cylindrical projections, breaks for stereographic ones...

**Comment by joernu76** [comment]
Found this comment:

```
        Redraws the entire map. This is necessary after zoom/pan operations.

        Determines corner coordinates of the current axes, removes all items
        belonging the the current map and draws a new one by calling
        self.__init__().

        DRAWBACK of this approach is that the map coordinate system changes, as
        basemap always takes the lower left axis corner as (0,0). This means
        that all other objects on the matplotlib canvas (flight track, markers,
        ..) will be incorrectly placed after a redraw. Their coordinates need
        to be adjusted by 1) transforming their coordinates to lat/lon BEFORE
        the map is redrawn, 2) redrawing the map, 3) transforming the stored
        lat/lon coordinates to the new map coordinates.
```

I.e. the way how basemap works apparently breaks matplotlib's system as it
cannot deal with the coordinate change.

Potential solution a)

fix basemap

Potential solution b)

reimplement the buttons in our code using (seemingly working) lon/lat coordinates as basis.

**Comment by joernu76** [comment]
I go for b). The change is rather large and complicated and due to the fact that this hasn't worked, ever, I think we can push this to the next point release.
