### ISSUE TITLE
recently the server/layer window gets into background

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#921]
With some of the views open the multilayer selection window can get loaded into the background. I clicked on my taskbar icon of mss and then they got reorganized.

![example](https://user-images.githubusercontent.com/278728/117296837-ce458000-ae75-11eb-84ea-06dfdd18943d.gif)

**Comment by ReimarBauer** [comment]
@Marilyth I've no idea if this happens always, I recognized it by creating this demo video.

**Comment by Marilyth** [comment]
@ReimarBauer Can you reproduce this consistently? This never happens on my end.

**Comment by ReimarBauer** [comment]
@Marilyth it was three times today but don't happen again. If it happens better reproducable we can open this again.
