### ISSUE TITLE
improve startup speed of topview and other views

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#922]
With the current configuration of MSS for the campaign, a start of TopView takes a noteable moment.

We have to optimizing initializing of parameters.

Probably it is faster to read all sections instead one by one, or to read more than one section by the config_loader.

**Comment by ReimarBauer** [comment]
The config_loader is not often called in this view, we have to look on the modules imported.

**Comment by aravindm711** [comment]
> 90% of the initialization time of the topview window is by self.mpl.canvas.init_map https://github.com/Open-MSS/MSS/blob/develop/mslib/msui/topview.py#L221. I have also tried moving this to after the window is created but it doesn't seem to work. Is there something we can do about this?

![Screenshot 2021-05-20 at 12 35 40 AM](https://user-images.githubusercontent.com/29843489/118870636-66c31200-b904-11eb-9a8a-46ee71a319e4.png)

**Comment by Marilyth** [comment]
Indeed this is an issue with the time Basemap/MapCanvas needs to generate the requested map.

**Comment by Marilyth** [comment]
It is possible to just start the topview without the map and load it in the background like @aravindm711 suggested.
However I am unsure if it isn't aesthetically better to just wait for everything to load.
![topview_startup](https://user-images.githubusercontent.com/19623152/118974774-7ded1880-b973-11eb-8db2-8efc41a285fd.gif)

**Comment by ReimarBauer** [comment]
Empty it is much more  disturbing. I think we won't change this.

**Comment by ReimarBauer** [comment]
likly on the choosen map section and also the kind of projection it will take shorter or longer.

Should we show to the user that he clicked the button by a fast progressbar ?

**Comment by ReimarBauer** [comment]
If this did time span did not much exceed, we have to live with it.
