### ISSUE TITLE
some windows ui on OS windows 10 shows a "?"

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#930]
Some of the UIs show with windows 10 a "?"

![windows_ui](https://user-images.githubusercontent.com/278728/117402800-5889f480-af07-11eb-9538-55098d3f8c6e.png)

We should verify if we can provide a short help, or remove this "?"

**Comment by Jatin2020-24** [comment]
I think this problem is only with QDialog Box

**Comment by Jatin2020-24** [comment]
I am closing this PR, someone else with experience can take this.
