### ISSUE TITLE
msui start independent from mscolab_settings

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#933]
Just seen on the windows 10 system. msui is completly independent from the mscolab server. No need to try to load that config py script. We have to remove this dependency if possible.

```
python mslib\msui\mss_pyui.py
WARNING:root:Couldn't import mscolab_settings (ImportError:'No module named 'mscolab_settings''), using dummy config.
INFO: MSS Version: 3.0.2.
```

**Comment by aravindm711** [comment]
Hello @ReimarBauer, this is happening because of this import chain, msui/mscolab.py -> mscolabproject -> models -> conf, hence importing mscolab settings. We could solve this using dynamic imports. Would this be a feasible solution?
