### ISSUE TITLE
MSCOLAB login button disabled in spite of pre-filled login+password

### ISSUE THREAD

**Issue by joernu76** [Open-MSS/MSS#938]
Tested on current develop with just-merged-in-bugfixes from stable.

1. have username + password configured in JSON (probably works as well with entered one)
2. connect to server
3. disconnect from server
4. connect to server (username + password are still (correctly) filled!)

Desired state:
login button "press-able"

Is-State:
login button disabled.

**Comment by Jatin2020-24** [comment]
@joernu76  how can I reproduce this bug

**Comment by ReimarBauer** [comment]
use the vars in your mss_settings.json


```
"default_MSCOLAB": "http://localhost:8083",
"MSCOLAB_mailid": "your email",
"MSCOLAB_password": 'your password'
```

**Comment by ReimarBauer** [comment]
I can't reproduce this. I do prefer a test to show this behaviour. Because then we need more than this 

https://github.com/Open-MSS/MSS/pull/882/files

**Comment by joernu76** [comment]
I updated the description with a series of steps to reproduce the problem.

**Comment by joernu76** [comment]
I looked in the code. The "connect_handler" function disables the login button. This needs a check, if there is not already something entered in the login+password field or similar.

**Comment by ReimarBauer** [comment]
this can be because it is a toggle. It shows "Connect" for me when same time the Login is disabled. 

![example](https://user-images.githubusercontent.com/278728/117670496-3d89df80-b1a8-11eb-8009-2ac28e5c8f14.gif)

I removed all pyc files.
```
rm `find . | grep pyc$`
```

**Comment by joernu76** [comment]
I had a strange MSS version. Seemingly. Recreated clone and now it works.
