### ISSUE TITLE
eventlet==0.30.2 for "gunicorn --worker-class eventlet" mscolab needed

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#951]
There was recently a change in the API of eventlet described on Stackoverflow
https://stackoverflow.com/questions/67409452/gunicorn-importerror-cannot-import-name-already-handled-from-eventlet-wsgi

Currently we need

```
 mamba install eventlet==0.30.2
```

**Comment by ReimarBauer** [comment]
we don't have gunicorn and eventlet yet in the meta.yaml

**Comment by ReimarBauer** [comment]
This is mostly a documentation task on setting up e.g. supervisor, gunicorn, nginx

There are other deployments possible.

**Comment by Jatin2020-24** [comment]
I am closing this PR, someone else with experience can take this.

**Comment by ReimarBauer** [comment]
I first thought we have it in our meta.yaml, but we didn't add it. Not anyone is having servers. And then there are more than one option. We can describe the dependencies we have used and start with this. So these modules are optional.

**Comment by ReimarBauer** [comment]
we use this eventlet version currently also for testing
