### ISSUE TITLE
Docker images fail

### ISSUE THREAD

**Issue by Marilyth** [Open-MSS/MSS#955]
Yesterday all [docker images started to fail](https://github.com/Open-MSS/dockerhub/runs/2575571121?check_suite_focus=true), probably due to a package update.
Difference between working and failing images:

# New package
`dataclasses 0.8 pyhc8e2a94_1 conda-forge`

# Changed package
`werkzeug 1.0.1 pyh9f0ad1d_0 conda-forge` -> `werkzeug 2.0.0 pyhd8ed1ab_0 conda-forge`

**Comment by ReimarBauer** [comment]
ok, I fixate that package to < 2.0.0 and start a new build process

**Comment by ReimarBauer** [comment]
The pallets projects released yesterday a bunch of packages used by us
https://palletsprojects.com/blog/flask-2-0-released/

We have to look on this again once all packages updated on conda-forge.

**Comment by ReimarBauer** [comment]
The tool chain is so wonderful! I can same time prepare a new build on conda-forge and verify same changes by the automated tests on the MSS github that it will work :)
