### ISSUE TITLE
Attribute Error in Qt while running mss_pyui.py in Windows

### ISSUE THREAD

**Issue by risehr** [Open-MSS/MSS#985]
When I start the mss application, it says, there is no such Qt attribute.

This is due to this line.
'application.setAttribute(QtCore.Qt.AA_DisableWindowContextHelpButton)' in mss_pyui.py file.
![image](https://user-images.githubusercontent.com/54763705/119225714-1249ad80-bb23-11eb-9ccf-68477b1772ee.png)

This line was written to remove the ? denoting help in windows.
May be this has something to do with the Qt version out there.

**Comment by ReimarBauer** [comment]
we have to fixate the QT modules >= 5.10
https://github.com/mantidproject/mantid/issues/26502

**Comment by joernu76** [comment]
Did this happen in a fresh install=

**Comment by ReimarBauer** [comment]
it happened on a install mamba install mss python=3 on windows

that found python 3.6 and ...
