### ISSUE TITLE
mscolab project list alphabetical sorted

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#986]
We should sort the project lists alphabetical in the project list of the main mscolab window

![current_unsorted](https://user-images.githubusercontent.com/278728/119229503-a9f5ce80-bb18-11eb-8f1c-ddcc801e5e81.png)

currently a simple list would be enough

**Comment by aravindm711** [comment]
do we want it sorted only with the project name or both project name and access level?
