### ISSUE TITLE
unify of project creation import and import plugin feature 

### ISSUE THREAD

**Issue by ReimarBauer** [Open-MSS/MSS#992]
we have currently three "import" features of a flightpath 

a) on project creation
b) import feature can use plugins
c) work locally import

all three should have same code and same features 

the import could also get extended by a textbox where we can copy paste a flightpath.

**Comment by ReimarBauer** [comment]
We also have kml import in the kml dockingwidget for topview.

probably also other formats e.g. ftml are interesting to be used for this import in the dockingwidget. the data needs to be converted to be visualized by the kml toolkit.

**Comment by joernu76** [comment]
resolved by gsoc2021
